# -*- coding: utf-8 -*-
"""Đề Tiếng Anh 7 giữa HK1 (Global Success) — nguồn Google Drive (Loigiaihay.com).

Chép nguyên văn 5 đề. Ghi chú các phần BỎ QUA / điều chỉnh:
- Phần LISTENING của cả 5 đề bị bỏ (không có file audio):
  Đề 1 Ex6 (câu 1-5 T/F), Đề 2 Ex7 (câu 31-35), Đề 3 Ex6-7 (câu 21-30),
  Đề 4 Part 1 (câu 1-5), Đề 5 Part 1 (câu 1-5).
- Phần gạch chân trong câu phát âm không giữ được qua PDF → ghi chữ cái gạch chân
  trong ngoặc đơn ngay trong câu hỏi, vd "c(o)ndition" (theo lời giải chi tiết của đề).
- Câu bị bỏ vì đáp án trong file mâu thuẫn / không chắc:
  Đề 2 câu 23 (B và C đều đúng theo bài đọc; bảng ghi C, lời giải ghi B),
  Đề 4 câu 22 (bảng ghi C, lời giải ghi A), Đề 4 câu 25 (đáp án C trong file rất đáng ngờ).
- Câu dùng đáp án theo LỜI GIẢI CHI TIẾT thay vì bảng đáp án (bảng ghi sai):
  Đề 4 câu 15 (B), Đề 4 câu 19 (B), Đề 5 câu 8 (C). Đề 5 câu 31 sửa thành False
  (bài đọc: "I like making cakes the most").
- Đáp án điền từ dùng dấu nháy đơn thẳng (') để học sinh gõ được; Đề 2 câu 26 lấy
  "occurs" (file ghi "happens/ occurs"); Đề 1 câu 10-11 có 2 chỗ trống → ghi "are - picking".
- Đề 5 câu 38-40: phần gạch chân không giữ được, ghi trong [ ] suy từ đáp án.
"""

DURATION = 60   # phút (đề gốc không ghi thời gian; đề 40 câu → 60 phút)

SOURCES = {
    1: "de-thi-giua-ki-1-tieng-anh-7-global-success-de-so-1.pdf (1r58luEBoIP5qBhVncD2E8Lk-0JgibQVe)",
    2: "de-thi-giua-ki-1-tieng-anh-7-global-success-de-so-2.pdf (1u5Peu7ulwGjlVPvR5sdomSbAQxWgu-J3)",
    3: "de-thi-giua-ki-1-tieng-anh-7-global-success-de-so-3.pdf (1tRx9NecggpkgkSL0rgbP7V1c1iBwE_70)",
    4: "de-thi-giua-ki-1-tieng-anh-7-global-success-de-so-4.pdf (1Dqi35cjvpMZYoFqwiO8eeXvR_N3NXrQI)",
    5: "de-thi-giua-ki-1-tieng-anh-7-global-success-de-so-5.pdf (1Nc0s7f8-0r3wOSwqJKoe61xQbjZG9FkJ)",
}

# ══════════════════════════════════════════════════════════════════════════════
# ĐỀ SỐ 1
# ══════════════════════════════════════════════════════════════════════════════
_DE_1 = [
    {"type": "choice", "topic": "Pronunciation",
     "section_start": "A. LANGUAGE FOCUS",
     "section_instruction": "Exercise 1: Choose the word whose underlined part is pronounced different from the others’.",
     "passage_text": None,
     "q": "1. Choose the word whose underlined part is pronounced differently: A. c(o)ndition B. pr(o)tect C. t(o)fu",
     "options": ["A. condition", "B. protect", "C. tofu"],
     "answer": "C. tofu",
     "explanation": "condition /kənˈdɪʃn/, protect /prəˈtekt/ (âm /ə/); tofu /ˈtəʊfuː/ (âm /əʊ/)."},
    {"type": "choice", "topic": "Pronunciation",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "2. Choose the word whose underlined part is pronounced differently: A. m(a)turity B. teen(a)ger C. orphan(a)ge",
     "options": ["A. maturity", "B. teenager", "C. orphanage"],
     "answer": "B. teenager",
     "explanation": "maturity /məˈtʃʊərəti/, orphanage /ˈɔːfənɪdʒ/ (âm /ə/); teenager /ˈtiːneɪdʒə/ (âm /eɪ/)."},
    {"type": "choice", "topic": "Pronunciation",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "3. Choose the word whose underlined part is pronounced differently: A. develop(ed) B. plant(ed) C. need(ed)",
     "options": ["A. developed", "B. planted", "C. needed"],
     "answer": "A. developed",
     "explanation": "developed: đuôi -ed đọc /t/; planted, needed: đọc /ɪd/."},
    {"type": "choice", "topic": "Pronunciation",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "4. Choose the word whose underlined part is pronounced differently: A. enjoy(ed) B. cook(ed) C. volunteer(ed)",
     "options": ["A. enjoyed", "B. cooked", "C. volunteered"],
     "answer": "B. cooked",
     "explanation": "cooked: đuôi -ed đọc /t/; enjoyed, volunteered: đọc /d/."},

    {"type": "fill", "topic": "Grammar",
     "section_start": None,
     "section_instruction": "Exercise 2: Fill each blank with the present simple, present continuous or past simple form of the verb in brackets.",
     "passage_text": None,
     "q": "5. When Tom was a teenager, his hobby ___________ (be) horse riding.",
     "answer": "was",
     "explanation": "Quá khứ đơn (When Tom was …); his hobby là danh từ số ít → was."},
    {"type": "fill", "topic": "Grammar",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "6. Alice often does judo at 5 p.m. every day, but today she ___________ (do) some homework.",
     "answer": "is doing",
     "explanation": "Hiện tại tiếp diễn: diễn tả sự thay đổi so với thói quen (today)."},
    {"type": "fill", "topic": "Grammar",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "7. Do you know that the sun always ___________ (rise) in the East?",
     "answer": "rises",
     "explanation": "Hiện tại đơn: chân lý hiển nhiên; dấu hiệu always."},
    {"type": "fill", "topic": "Grammar",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "8. Look! Toby ___________ (have) some fast food again!",
     "answer": "is having",
     "explanation": "Hiện tại tiếp diễn: hành động đang diễn ra; dấu hiệu Look!"},
    {"type": "fill", "topic": "Grammar",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "9. When I was in Nha Trang last month, I ___________ (collect) some beautiful seashells.",
     "answer": "collected",
     "explanation": "Quá khứ đơn: last month."},
    {"type": "fill", "topic": "Grammar",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "10. - Look at you! Why ___________ you ___________ (pick) up litter? - To save the environment. (2 chỗ trống: ghi 2 từ cách nhau bằng dấu \" - \")",
     "answer": "are - picking",
     "explanation": "Hiện tại tiếp diễn (Look at you!): Why are you picking up litter? → ghi: are - picking"},
    {"type": "fill", "topic": "Grammar",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "11. ___________ Jenny ___________ (volunteer) in the local hospital last summer? (2 chỗ trống: ghi 2 từ cách nhau bằng dấu \" - \")",
     "answer": "Did - volunteer",
     "explanation": "Quá khứ đơn (last summer): Did Jenny volunteer …? → ghi: Did - volunteer"},
    {"type": "fill", "topic": "Grammar",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "12. Trung never ___________ (watch) TV before finishing all his homework.",
     "answer": "watches",
     "explanation": "Hiện tại đơn: thói quen (never); chủ ngữ số ít → watches."},
    {"type": "fill", "topic": "Grammar",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "13. I ______________ (not study) now because I feel very tired.",
     "answer": "am not studying",
     "explanation": "Hiện tại tiếp diễn (now), phủ định."},
    {"type": "fill", "topic": "Grammar",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "14. Someone ___________ (throw) away a pile of rubbish on the pavement yesterday.",
     "answer": "threw",
     "explanation": "Quá khứ đơn: yesterday; throw → threw."},

    {"type": "choice", "topic": "Vocabulary",
     "section_start": None,
     "section_instruction": "Exercise 3: Choose the best option to complete each sentence. Circle A, B, or C.",
     "passage_text": None,
     "q": "15. You can use this ____ to stick these pieces of color paper to decorate your dollhouse.",
     "options": ["A. nail", "B. glue", "C. model"],
     "answer": "B. glue",
     "explanation": "glue: keo dán."},
    {"type": "choice", "topic": "Vocabulary",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "16. When children take care of their pets, they learn how to take on ___________.",
     "options": ["A. happiness", "B. maturity", "C. responsibility"],
     "answer": "C. responsibility",
     "explanation": "take on responsibility: gánh vác trách nhiệm."},
    {"type": "choice", "topic": "Vocabulary",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "17. Some hobbies can help students learn to be ___________ with their work.",
     "options": ["A. patient", "B. popular", "C. valuable"],
     "answer": "A. patient",
     "explanation": "patient (adj): kiên nhẫn."},
    {"type": "choice", "topic": "Vocabulary",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "18. Tom is having a lot of fast food! He needs to change his ___________.",
     "options": ["A. hobby", "B. diet", "C. condition"],
     "answer": "B. diet",
     "explanation": "diet (n): chế độ ăn."},
    {"type": "choice", "topic": "Vocabulary",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "19. – What is tofu? – It’s a ___________ from soybeans.",
     "options": ["A. produce", "B. product", "C. producer"],
     "answer": "B. product",
     "explanation": "product (n): sản phẩm."},
    {"type": "choice", "topic": "Vocabulary",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "20. Look at those students. They are picking _________ used bottles to help save the environment.",
     "options": ["A. over", "B. in", "C. up"],
     "answer": "C. up",
     "explanation": "pick up sth: nhặt cái gì."},

    {"type": "choice", "topic": "Reading",
     "section_start": "B. READING",
     "section_instruction": "Exercise 4: Read the passage. Circle the best answer A, B, or C to each of the questions.",
     "passage_text": "Judo, one of the most popular martial arts, comes from Japan and it is quite well-known in Viet Nam. When we do judo, we will learn some basic techniques in throwing, grappling, and striking. We learn them carefully and steps by steps so that we do not have to worry too much about injuries. Judo teaches us how to train our bodies and minds as well as how to use our energy in the best way. It first appeared in the Olympic Games in Tokyo in 1964 and since 1972 it has been an official event in the Olympic Games. Vietnamese judokas – people who do judo – have won some international recognition and are trying their best to win first medals in the Olympic Games.",
     "q": "21. What is the passage mainly about?",
     "options": ["A. The development of judo.", "B. The development and benefits of judo.", "C. The development of judo in Viet Nam."],
     "answer": "B. The development and benefits of judo.",
     "explanation": "Đoạn văn nói về sự phát triển và lợi ích của judo."},
    {"type": "choice", "topic": "Reading",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "22. What does the word It in bold in the paragraph mean? (\"It first appeared in the Olympic Games…\")",
     "options": ["A. Energy.", "B. Mind.", "C. Judo."],
     "answer": "C. Judo.",
     "explanation": "It = Judo (It first appeared in the Olympic Games in Tokyo in 1964)."},
    {"type": "choice", "topic": "Reading",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "23. What is one of the benefits of practising judo?",
     "options": ["A. Knowing how to throw people.", "B. Learning to control our bodies.", "C. Winning medals in competitions."],
     "answer": "B. Learning to control our bodies.",
     "explanation": "Judo teaches us how to train our bodies and minds."},
    {"type": "choice", "topic": "Reading",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "24. When did Judo first appear in the Olympic Games?",
     "options": ["A. In 1954.", "B. In 1964.", "C. In 1968."],
     "answer": "B. In 1964.",
     "explanation": "It first appeared in the Olympic Games in Tokyo in 1964."},
    {"type": "choice", "topic": "Reading",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "25. How many Olympic medals did Vietnamese judokas win in 1972?",
     "options": ["A. None.", "B. One", "C. Two."],
     "answer": "A. None.",
     "explanation": "Judokas Việt Nam vẫn đang cố gắng giành huy chương đầu tiên ở Olympic → chưa có."},

    {"type": "fill", "topic": "Cloze",
     "section_start": None,
     "section_instruction": "Exercise 5: Complete the reading passage. Write ONE suitable word in each blank.",
     "passage_text": "A Grade 7 student and his friends have an idea of collecting (26) ___________ for homeless children in his town. They call it the “Book Birthday Party”. Every month they will select a birthday of a friend in his class or a child in his neighbourhood to celebrate (27) ___________ special birthday party. It is just a simple party. Everyone who comes to the party should bring some healthy food, drink, and a book (28) ___________ any kinds: storybook, textbook, notebook, comic, etc. Those who cannot bring books will help with the collecting and sending books to the homeless children. They believe that the healthy food and drink will help them stay (29) __________ and the books will help homeless children with their study. Everyone will be (30) ___________!",
     "q": "26. collecting (26) ___________ for homeless children",
     "answer": "books",
     "explanation": "Tên bữa tiệc là “Book Birthday Party” → books."},
    {"type": "fill", "topic": "Cloze",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "27. to celebrate (27) ___________ special birthday party",
     "answer": "a",
     "explanation": "Mạo từ không xác định a trước cụm danh từ lần đầu xuất hiện."},
    {"type": "fill", "topic": "Cloze",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "28. a book (28) ___________ any kinds",
     "answer": "of",
     "explanation": "a book of any kinds."},
    {"type": "fill", "topic": "Cloze",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "29. help them stay (29) __________",
     "answer": "healthy",
     "explanation": "stay healthy: giữ sức khỏe."},
    {"type": "fill", "topic": "Cloze",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "30. Everyone will be (30) ___________!",
     "answer": "happy",
     "explanation": "Cần tính từ mang nghĩa tích cực → happy."},

    {"type": "fill", "topic": "Writing",
     "section_start": "D. WRITING",
     "section_instruction": "Exercise 7: For each question, complete the second sentence so that it means the same as the first one. Use the word in brackets and do not change it. Write NO MORE THAN THREE WORDS.",
     "passage_text": None,
     "q": "36. My father often collects stamps in his free time. (HOBBY) → My ____________________ collecting stamps.",
     "answer": "father's hobby",
     "explanation": "My father's hobby is collecting stamps."},
    {"type": "fill", "topic": "Writing",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "37. It often takes her hours to draw pictures every Sunday. (SPENDS) → She often ____________________ pictures every Sunday.",
     "answer": "spends hours drawing",
     "explanation": "It takes sb time to V = S spend(s) time V-ing."},
    {"type": "fill", "topic": "Writing",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "38. The Japanese have a healthy diet so they live long lives. (OF) → The Japanese live long lives ____________________ healthy diet.",
     "answer": "because of their",
     "explanation": "because of + cụm danh từ."},
    {"type": "fill", "topic": "Writing",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "39. We donate these clothes to children who have no home. (HOMELESS) → We give these clothes ____________________.",
     "answer": "to homeless children",
     "explanation": "children who have no home = homeless children."},
    {"type": "fill", "topic": "Writing",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "40. My mother began to teach English in 1996. (WORKING) → My mother started ____________________ English teacher in 1996.",
     "answer": "working as an",
     "explanation": "start V-ing; work as a/an + nghề nghiệp."},
]

# ══════════════════════════════════════════════════════════════════════════════
# ĐỀ SỐ 2
# ══════════════════════════════════════════════════════════════════════════════
_DE_2 = [
    {"type": "choice", "topic": "Pronunciation",
     "section_start": "A. LANGUAGE FOCUS",
     "section_instruction": "Exercise 1: Circle the word whose underlined part is pronounced differently from the others’.",
     "passage_text": None,
     "q": "1. Choose the word whose underlined part is pronounced differently: A. s(a)fety B. vit(a)min C. p(a)rade",
     "options": ["A. safety", "B. vitamin", "C. parade"],
     "answer": "B. vitamin",
     "explanation": "safety /ˈseɪfti/, parade /pəˈreɪd/ (âm /eɪ/); vitamin /ˈvɪtəmɪn/ (âm /ɪ/)."},
    {"type": "choice", "topic": "Pronunciation",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "2. Choose the word whose underlined part is pronounced differently: A. veh(i)cle B. f(i)ne C. s(i)gn",
     "options": ["A. vehicle", "B. fine", "C. sign"],
     "answer": "A. vehicle",
     "explanation": "vehicle /ˈviːəkl/ (âm /iː/); fine, sign (âm /aɪ/)."},
    {"type": "choice", "topic": "Stress",
     "section_start": None,
     "section_instruction": "Exercise 2: Circle the word which has a different stress pattern from that of the others’.",
     "passage_text": None,
     "q": "3. Choose the word which has a different stress pattern: A. candy B. seatbelt C. perform",
     "options": ["A. candy", "B. seatbelt", "C. perform"],
     "answer": "C. perform",
     "explanation": "perform /pəˈfɔːm/ trọng âm âm tiết 2; candy, seatbelt trọng âm âm tiết 1."},
    {"type": "choice", "topic": "Stress",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "4. Choose the word which has a different stress pattern: A. parade B. display C. crossing",
     "options": ["A. parade", "B. display", "C. crossing"],
     "answer": "C. crossing",
     "explanation": "crossing /ˈkrɒsɪŋ/ trọng âm âm tiết 1; parade, display trọng âm âm tiết 2."},

    {"type": "fill", "topic": "Grammar",
     "section_start": None,
     "section_instruction": "Exercise 3: Fill each blank with the correct form of the verb in brackets.",
     "passage_text": None,
     "q": "5. Tom: How do you go to school every day? Eden: I ___________ (go) to school by bicycle. It helps to reduce pollution.",
     "answer": "go",
     "explanation": "Hiện tại đơn: every day."},
    {"type": "fill", "topic": "Grammar",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "6. The horror film ___________ (be) so boring that we almost fell asleep at the cinema yesterday.",
     "answer": "was",
     "explanation": "Quá khứ đơn: yesterday."},
    {"type": "fill", "topic": "Grammar",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "7. Alice is quite lazy and she rarely ___________ (go) to the gym.",
     "answer": "goes",
     "explanation": "Hiện tại đơn: rarely; chủ ngữ she → goes."},
    {"type": "fill", "topic": "Grammar",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "8. Last Christmas, my family ___________ (spend) our times in Maldives and took part in a special festival.",
     "answer": "spent",
     "explanation": "Quá khứ đơn: Last Christmas."},
    {"type": "fill", "topic": "Grammar",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "9. Lisa: Hey, we ____________ (prepare) some moon cakes, do you want to join? Rose: Sounds great.",
     "answer": "are preparing",
     "explanation": "Hiện tại tiếp diễn: hành động đang xảy ra tại thời điểm nói."},
    {"type": "fill", "topic": "Grammar",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "10. We usually ___________ (have) banh chung and banh day on Tet holidays.",
     "answer": "have",
     "explanation": "Hiện tại đơn: usually."},
    {"type": "fill", "topic": "Grammar",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "11. I ___________ (take) a lot of photos when I visited the flower festival in the Netherlands.",
     "answer": "took",
     "explanation": "Quá khứ đơn: when I visited…"},
    {"type": "fill", "topic": "Grammar",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "12. Samantha ___________ (stew) pork soup in the kitchen, so don’t bother her.",
     "answer": "is stewing",
     "explanation": "Hiện tại tiếp diễn: hành động đang xảy ra."},
    {"type": "fill", "topic": "Grammar",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "13. John ___________ (leave) for Noi Bai Airport yesterday morning.",
     "answer": "left",
     "explanation": "Quá khứ đơn: yesterday morning."},
    {"type": "fill", "topic": "Grammar",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "14. My mother and I ___________ (not be) keen on horror films.",
     "answer": "aren't",
     "explanation": "Hiện tại đơn, chủ ngữ số nhiều → aren't (are not)."},

    {"type": "choice", "topic": "Vocabulary",
     "section_start": None,
     "section_instruction": "Exercise 4: Choose the best option to complete each of the following sentences.",
     "passage_text": None,
     "q": "15. It’s crucial for ___________ to walk only on the pavement or footpath.",
     "options": ["A. passengers", "B. pedestrians", "C. models"],
     "answer": "B. pedestrians",
     "explanation": "pedestrians: người đi bộ."},
    {"type": "choice", "topic": "Vocabulary",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "16. ___________ need to obey the traffic rules by not carrying more than one passenger.",
     "options": ["A. Pedestrians", "B. Elder people", "C. Cyclists"],
     "answer": "C. Cyclists",
     "explanation": "Cyclists: người đi xe đạp (không chở quá một người)."},
    {"type": "choice", "topic": "Vocabulary",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "17. “Transformer” is a _________ film which can help us know more about future robots.",
     "options": ["A. science fiction", "B. historical", "C. romance"],
     "answer": "A. science fiction",
     "explanation": "science fiction: khoa học viễn tưởng."},
    {"type": "choice", "topic": "Vocabulary",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "18. It is an honor for those actors who can take part ___________ Cannes Film Festival.",
     "options": ["A. on", "B. in", "C. over"],
     "answer": "B. in",
     "explanation": "take part in: tham gia."},
    {"type": "choice", "topic": "Grammar",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "19. ___________ that documentary is boring, I still love the main character in it.",
     "options": ["A. However", "B. Although", "C. Because"],
     "answer": "B. Although",
     "explanation": "Although + mệnh đề: mặc dù."},
    {"type": "choice", "topic": "Vocabulary",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "20. ___________ is one of special festivals for children in most Asian countries.",
     "options": ["A. Tulip festival", "B. Halloween", "C. Mid-Autumn Festival"],
     "answer": "C. Mid-Autumn Festival",
     "explanation": "Mid-Autumn Festival: Tết Trung thu."},

    {"type": "choice", "topic": "Reading",
     "section_start": "B. READING",
     "section_instruction": "Exercise 5: Read the passage. Circle the best answer A, B or C to each of the questions.",
     "passage_text": "Harry Potter and the Chamber of Secrets is the second of the fantasy film series based on the same novel by J. K. Rowling. After the success of the first one, Chris Columbus is still the director of this film. Meanwhile, the main cast of the first film remains in the second one. The film tells the story about the great efforts of Harry to save his friends at Hogwarts, especially Ron’s sister Ginny, from the attacks of a basilisk. It’s a giant snake under the control of the ghostly memory of the sixteen-year-old Tom Riddle, one piece of Lord Voldemort’s soul preserved in an enchanted diary. In the end, he kills the basilisk, saves everybody and frees Dobby – a kind of house-elf. The film is a really must-see. It also has lots of gripping images, soundtracks and visual effects.",
     "q": "21. What is the passage mainly about?",
     "options": ["A. A famous director with his successful fantasy film.", "B. A young wizard who kills a monster in his magic school.", "C. A film based on the second novel of a fantasy series by J. K. Rowling."],
     "answer": "C. A film based on the second novel of a fantasy series by J. K. Rowling.",
     "explanation": "Đoạn văn giới thiệu bộ phim dựa trên tiểu thuyết thứ hai của J. K. Rowling."},
    {"type": "choice", "topic": "Reading",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "22. Who is the author of the book series?",
     "options": ["A. Chris Columbus.", "B. J. K. Rowling.", "C. Harry Potter."],
     "answer": "B. J. K. Rowling.",
     "explanation": "based on the same novel by J. K. Rowling."},
    {"type": "choice", "topic": "Reading",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "24. What does the word It in line 9 mean? (\"It also has lots of gripping images…\")",
     "options": ["A. The film.", "B. The kind house-elf.", "C. The basilisk."],
     "answer": "A. The film.",
     "explanation": "The film is a really must-see. It also has lots of gripping images → It = the film."},
    {"type": "choice", "topic": "Reading",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "25. How are the visual effects of the film?",
     "options": ["A. Extremely interesting.", "B. Rather boring.", "C. Very colourful."],
     "answer": "A. Extremely interesting.",
     "explanation": "It also has lots of gripping images, soundtracks and visual effects."},

    {"type": "fill", "topic": "Cloze",
     "section_start": None,
     "section_instruction": "Exercise 6: Complete the passage. Write ONE suitable word in each blank.",
     "passage_text": "Diwali is one of the biggest and most important festivals in India. It usually (26) ______________ between October and November. Nowadays this festival is celebrated by both Hindu and non-Hindu communities and lasts (27) ___________ about five days. During the time of festival, Indians clean their houses and buy gold or kitchen utensils to help bring good luck. Then, they decorate their homes with clay lamps, which are the symbol of the inner light protecting from spiritual darkness. (28) ___________ the busy days of preparation, family members gather together for prayers to their own goddess, delicious feasts and colourful fireworks (29) ___________. They also visit their friends and relatives and (30) ___________ each other many gifts and best wishes.",
     "q": "26. It usually (26) ______________ between October and November.",
     "answer": "occurs",
     "explanation": "Đáp án đề: happens/ occurs (chấp nhận happens)."},
    {"type": "fill", "topic": "Cloze",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "27. lasts (27) ___________ about five days",
     "answer": "for",
     "explanation": "last for + khoảng thời gian."},
    {"type": "fill", "topic": "Cloze",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "28. (28) ___________ the busy days of preparation, family members gather together…",
     "answer": "After",
     "explanation": "After the busy days of preparation: sau những ngày chuẩn bị bận rộn."},
    {"type": "fill", "topic": "Cloze",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "29. delicious feasts and colourful fireworks (29) ___________.",
     "answer": "displays",
     "explanation": "fireworks displays: màn trình diễn pháo hoa (số nhiều)."},
    {"type": "fill", "topic": "Cloze",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "30. They also visit their friends and relatives and (30) ___________ each other many gifts and best wishes.",
     "answer": "give",
     "explanation": "visit … and give: động từ song hành, nguyên thể."},

    {"type": "fill", "topic": "Writing",
     "section_start": "D. WRITING",
     "section_instruction": "Exercise 8: For each question, complete the second sentence so that it means the same as the first one. Use the word in brackets and do not change it. Write NO MORE THAN THREE WORDS.",
     "passage_text": None,
     "q": "36. I will not watch that film because it is very scary. (TOO) → The film is ____________________ me to watch.",
     "answer": "too scary for",
     "explanation": "be too + adj + for sb to V."},
    {"type": "fill", "topic": "Writing",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "37. The film is very frightening, but it is interesting. (THOUGH) → The film is interesting ____________________ frightening.",
     "answer": "though it is",
     "explanation": "though + mệnh đề."},
    {"type": "fill", "topic": "Writing",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "38. You cannot park your car here as it’s against the law. (MUST) → You ____________________ your car here.",
     "answer": "mustn't park",
     "explanation": "mustn't + V: không được phép."},
    {"type": "fill", "topic": "Writing",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "39. Are these moon cakes delicious? (THINK) → ____________________ these moon cakes are delicious?",
     "answer": "Do you think",
     "explanation": "Do you think + mệnh đề?"},
    {"type": "fill", "topic": "Writing",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "40. The main soundtrack of The Hunger Game interested me when I heard it for the first time. (WAS) → I ____________________ the main soundtrack of The Hunger Game when I heard it for the first time.",
     "answer": "was interested in",
     "explanation": "be interested in + N."},
]

# ══════════════════════════════════════════════════════════════════════════════
# ĐỀ SỐ 3
# ══════════════════════════════════════════════════════════════════════════════
_DE_3 = [
    {"type": "choice", "topic": "Pronunciation",
     "section_start": "A. LANGUAGE FOCUS",
     "section_instruction": "Exercise 1: Circle the word whose underlined part is pronounced differently from the others’.",
     "passage_text": None,
     "q": "1. Choose the word whose underlined part is pronounced differently: A. backa(ch)e B. (ch)annel C. (ch)ildren",
     "options": ["A. backache", "B. channel", "C. children"],
     "answer": "A. backache",
     "explanation": "backache /ˈbækeɪk/ ch đọc /k/; channel, children ch đọc /tʃ/."},
    {"type": "choice", "topic": "Pronunciation",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "2. Choose the word whose underlined part is pronounced differently: A. th(ir)sty B. s(ur)f C. all(er)gy",
     "options": ["A. thirsty", "B. surf", "C. allergy"],
     "answer": "C. allergy",
     "explanation": "thirsty, surf đọc /ɜː/; allergy /ˈælədʒi/ đọc /ə/."},
    {"type": "choice", "topic": "Stress",
     "section_start": None,
     "section_instruction": "Exercise 2: Circle the word which has a different stress pattern from that of the others’.",
     "passage_text": None,
     "q": "3. Choose the word which has a different stress pattern: A. allergy B. volunteer C. energy",
     "options": ["A. allergy", "B. volunteer", "C. energy"],
     "answer": "B. volunteer",
     "explanation": "volunteer /ˌvɒlənˈtɪə/ trọng âm âm tiết 3; allergy, energy trọng âm âm tiết 1."},
    {"type": "choice", "topic": "Stress",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "4. Choose the word which has a different stress pattern: A. collect B. donate C. cycle",
     "options": ["A. collect", "B. donate", "C. cycle"],
     "answer": "C. cycle",
     "explanation": "cycle /ˈsaɪkl/ trọng âm âm tiết 1; collect, donate trọng âm âm tiết 2."},

    {"type": "choice", "topic": "Grammar",
     "section_start": None,
     "section_instruction": "Exercise 3: Fill each blank with the correct form of the verb in brackets.",
     "passage_text": None,
     "q": "5. She loves her job because she enjoys __________ people.",
     "options": ["A. meet", "B. to meet", "C. meeting"],
     "answer": "C. meeting",
     "explanation": "enjoy + V-ing."},
    {"type": "choice", "topic": "Grammar",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "6. We __________ to this nursing home every week.",
     "options": ["A. come", "B. comes", "C. coming"],
     "answer": "A. come",
     "explanation": "Hiện tại đơn, chủ ngữ We → come."},
    {"type": "choice", "topic": "Vocabulary",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "7. James eats a lot of fast food and he __________weight.",
     "options": ["A. puts on", "B. gets in", "C. take up"],
     "answer": "A. puts on",
     "explanation": "put on weight: tăng cân."},
    {"type": "choice", "topic": "Vocabulary",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "8. __________ is the condition of having painful red skin that is caused by staying in the sun for too long.",
     "options": ["A. Obesity", "B. Sunburn", "C. Cough"],
     "answer": "B. Sunburn",
     "explanation": "Sunburn: cháy nắng."},
    {"type": "choice", "topic": "Communication",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "9. Jessica: “Would you like a cup of coffee?” Kim: “__________”",
     "options": ["A. No, thanks.", "B. I feel itchy.", "C. I do like."],
     "answer": "A. No, thanks.",
     "explanation": "Từ chối lời mời lịch sự: No, thanks."},
    {"type": "choice", "topic": "Communication",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "10. Ben: “Let’s go camping.” Joe: “__________. I worked all night yesterday.”",
     "options": ["A. No problem", "B. Just bring yourself", "C. Oh, count me out"],
     "answer": "C. Oh, count me out",
     "explanation": "count me out: đừng tính tôi vào (từ chối)."},

    {"type": "choice", "topic": "Cloze",
     "section_start": "B. READING",
     "section_instruction": "Exercise 4: Choose the correct answer A, B, C or D for each gap to complete the following passage.",
     "passage_text": "Hoa has several hobbies such as knitting, cooking, (11) __________ to music and so on. However, she likes (12) __________ books the most, which makes her comfortable after school. It also helps her to improve her knowledge. Sometimes, she plays sports (13) __________ her sisters in the front yard. In the morning, she usually (14) __________ up early to go cycling. It helps her to (15) __________ her health and enjoy fresh air in the morning.",
     "q": "11. knitting, cooking, (11) __________ to music",
     "options": ["A. listen", "B. listens", "C. listening"],
     "answer": "C. listening",
     "explanation": "Song hành với các danh động từ knitting, cooking → listening."},
    {"type": "choice", "topic": "Cloze",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "12. she likes (12) __________ books the most",
     "options": ["A. read", "B. reading", "C. reads"],
     "answer": "B. reading",
     "explanation": "like + V-ing."},
    {"type": "choice", "topic": "Cloze",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "13. she plays sports (13) __________ her sisters",
     "options": ["A. with", "B. to", "C. for"],
     "answer": "A. with",
     "explanation": "play with sb: chơi cùng ai."},
    {"type": "choice", "topic": "Cloze",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "14. she usually (14) __________ up early to go cycling",
     "options": ["A. got", "B. get", "C. gets"],
     "answer": "C. gets",
     "explanation": "Hiện tại đơn (usually), chủ ngữ she → gets."},
    {"type": "choice", "topic": "Cloze",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "15. It helps her to (15) __________ her health",
     "options": ["A. donate", "B. improve", "C. provide"],
     "answer": "B. improve",
     "explanation": "improve her health: cải thiện sức khỏe."},

    {"type": "choice", "topic": "Reading",
     "section_start": None,
     "section_instruction": "Exercise 5: Read the passage. Circle the best answer A, B or C to each of the questions.",
     "passage_text": "The secrets to a long life\nWhy can some people live to over a hundred, while most of us die much sooner? How long you live depends on where you live. A person who lives in a city in Australia will probably live longer than a person living in a poor part of Africa. So, what can you do to live longer? You can make healthy choices. That means eating healthy foods and getting enough exercise.\nBeing overweight may make your life shorter because you have a higher chance to have health problems. You can start by changing what you eat. Eat less red meat instead of chicken or fish. Fish is really good for helping you live a longer life. You should eat lots of vegetables, so you can get a lot of the vitamins you need.\nYou also need to get enough exercise. There are different types of exercises. Some exercise is good for the heart. Other types of exercise is good for making you stronger. Lifting weights is a good example. Along with taking care of your body, you also have to take care of your mind. Don’t work too hard. Try to relax and do something fun each day. If you follow these simple rules, you will have a good chance of living a long time.",
     "q": "16. What is the reading text about?",
     "options": ["A. How to live a long life.", "B. You live longer thanks to the place you live.", "C. Being overweight makes your life shorter."],
     "answer": "A. How to live a long life.",
     "explanation": "Bài đọc về cách để sống lâu."},
    {"type": "choice", "topic": "Reading",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "17. What are healthy choices?",
     "options": ["A. Eating healthy foods", "B. Getting enough exercise", "C. A and B"],
     "answer": "C. A and B",
     "explanation": "That means eating healthy foods and getting enough exercise."},
    {"type": "choice", "topic": "Reading",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "18. Why should you eat vegetables?",
     "options": ["A. Because vegetables are better for your health than meat.", "B. Because vegetables are easy to make healthy dishes.", "C. Because vegetables helps you get a lot of the vitamins you need."],
     "answer": "C. Because vegetables helps you get a lot of the vitamins you need.",
     "explanation": "You should eat lots of vegetables, so you can get a lot of the vitamins you need."},
    {"type": "choice", "topic": "Reading",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "19. How is lifting weights good for you?",
     "options": ["A. It makes your heart stronger.", "B. It makes you stronger.", "C. It makes you lose weight."],
     "answer": "B. It makes you stronger.",
     "explanation": "Other types of exercise is good for making you stronger. Lifting weights is a good example."},
    {"type": "choice", "topic": "Reading",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "20. Which statement is NOT mentioned in the text?",
     "options": ["A. Mental health is also important.", "B. Fish and chicken are better for your health than red meat.", "C. One of the secrets to a long life is to eat lots of vegetables instead of doing exercise."],
     "answer": "C. One of the secrets to a long life is to eat lots of vegetables instead of doing exercise.",
     "explanation": "Bài đọc nói cần cả ăn rau và tập thể dục, không phải ăn rau thay cho tập thể dục."},

    {"type": "fill", "topic": "Writing",
     "section_start": "D. WRITING",
     "section_instruction": "Exercise 8: Put the given words in good order to make meaningful sentences.",
     "passage_text": None,
     "q": "31. He/ summer/ in/ climbing/ goes/ mountain/ the/ usually/.",
     "answer": "He usually goes mountain climbing in the summer.",
     "explanation": ""},
    {"type": "fill", "topic": "Writing",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "32. it/ boring/ because/ finds/ time/ models/ Jim/ takes/ lots of/ making/.",
     "answer": "Jim finds making models boring because it takes lots of time.",
     "explanation": ""},
    {"type": "fill", "topic": "Writing",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "33. cold/ I/ sore throat/ love/ a /,/ drinks/ but/ have/ I/.",
     "answer": "I love cold drinks but I have a sore throat.",
     "explanation": ""},
    {"type": "fill", "topic": "Writing",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "34. Alex/ usually/ fishing/ so/,/ loves/ goes/ in/ near/ he/ his house/ fishing/ the lake/.",
     "answer": "Alex loves fishing, so he usually goes fishing in the lake near his house.",
     "explanation": ""},
    {"type": "fill", "topic": "Writing",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "35. Smoking/ harmful/ is/ costs/ it/ and/ a lot/ of/ money/./,/",
     "answer": "Smoking is harmful, and it costs a lot of money.",
     "explanation": ""},

    {"type": "fill", "topic": "Writing",
     "section_start": None,
     "section_instruction": "Exercise 9: Complete the second sentence so that it has the same meaning as the first one.",
     "passage_text": None,
     "q": "36. Joana doesn't eat much in order not to be overweight. → Joana doesn't eat much because ___",
     "answer": "she doesn't want to be overweight.",
     "explanation": "Joana doesn't eat much because she doesn't want to be overweight."},
    {"type": "fill", "topic": "Writing",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "37. She likes arranging flowers. → Arranging flowers ___",
     "answer": "is her hobby.",
     "explanation": "Arranging flowers is her hobby."},
    {"type": "fill", "topic": "Writing",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "38. Linda thinks mountain climbing is dangerous. → Linda finds ___",
     "answer": "mountain climbing dangerous.",
     "explanation": "find + O + adj: Linda finds mountain climbing dangerous."},
    {"type": "fill", "topic": "Writing",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "39. Why don't we go swimming this afternoon? → What about ___",
     "answer": "going swimming this afternoon?",
     "explanation": "What about + V-ing?"},
    {"type": "fill", "topic": "Writing",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "40. How about going to the movies tonight? → Let’s ___",
     "answer": "go to the movies tonight.",
     "explanation": "Let's + V."},
]

# ══════════════════════════════════════════════════════════════════════════════
# ĐỀ SỐ 4
# ══════════════════════════════════════════════════════════════════════════════
_DE_4 = [
    {"type": "choice", "topic": "Pronunciation",
     "section_start": "PART 2. LANGUAGE",
     "section_instruction": "Mark the letter A, B, C or D to indicate the word whose underline part differs from the other three in pronunciation in each of the following questions.",
     "passage_text": None,
     "q": "6. Choose the word whose underlined part is pronounced differently: A. n(ur)sing B. f(ur)ther C. s(ur)fing D. s(ur)vive",
     "options": ["A. nursing", "B. further", "C. surfing", "D. survive"],
     "answer": "D. survive",
     "explanation": "survive /sərˈvaɪv/ ur đọc /ə/; các từ còn lại đọc /ɜː/."},
    {"type": "choice", "topic": "Pronunciation",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "7. Choose the word whose underlined part is pronounced differently: A. l(ear)ner B. (ear)plug C. (Ear)th D. (ear)ly",
     "options": ["A. learner", "B. earplug", "C. Earth", "D. early"],
     "answer": "B. earplug",
     "explanation": "earplug /ˈɪrplʌɡ/ ear đọc /ɪə/; các từ còn lại đọc /ɜː/."},
    {"type": "choice", "topic": "Pronunciation",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "8. Choose the word whose underlined part is pronounced differently: A. plou(gh) B. cou(gh) C. lau(gh)ter D. enou(gh)",
     "options": ["A. plough", "B. cough", "C. laughter", "D. enough"],
     "answer": "A. plough",
     "explanation": "plough /plaʊ/ gh câm; các từ còn lại gh đọc /f/."},
    {"type": "choice", "topic": "Pronunciation",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "9. Choose the word whose underlined part is pronounced differently: A. attend(ed) B. listen(ed) C. enjoy(ed) D. repair(ed)",
     "options": ["A. attended", "B. listened", "C. enjoyed", "D. repaired"],
     "answer": "A. attended",
     "explanation": "attended đọc /ɪd/; các từ còn lại đọc /d/."},
    {"type": "choice", "topic": "Pronunciation",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "10. Choose the word whose underlined part is pronounced differently: A. collect(ed) B. creat(ed) C. climb(ed) D. need(ed)",
     "options": ["A. collected", "B. created", "C. climbed", "D. needed"],
     "answer": "C. climbed",
     "explanation": "climbed đọc /d/; các từ còn lại đọc /ɪd/."},

    {"type": "choice", "topic": "Grammar",
     "section_start": None,
     "section_instruction": "Mark the letter A, B, C or D to indicate the underlined part that needs correction in each of the following questions.",
     "passage_text": None,
     "q": "11. Some of my students collect old clothes for homeless people last Sunday.",
     "options": ["A. of", "B. homeless", "C. collect", "D. for"],
     "answer": "C. collect",
     "explanation": "last Sunday → quá khứ đơn: collected."},
    {"type": "choice", "topic": "Grammar",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "12. Because I have a toothache, I will going to the dentist tomorrow.",
     "options": ["A. toothache", "B. have", "C. dentist", "D. going"],
     "answer": "D. going",
     "explanation": "will + V nguyên mẫu: will go."},
    {"type": "choice", "topic": "Grammar",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "13. What will do you buy for your best friend for his birthday?",
     "options": ["A. his", "B. buy", "C. will do", "D. for"],
     "answer": "C. will do",
     "explanation": "Câu hỏi Wh- tương lai đơn: What will you buy …? (không cần do)."},
    {"type": "choice", "topic": "Grammar",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "14. My family will have a trip to the beach next summer. I think it is very wonderful.",
     "options": ["A. the", "B. will have", "C. to", "D. is"],
     "answer": "D. is",
     "explanation": "Việc chưa xảy ra → tương lai đơn: it will be very wonderful."},
    {"type": "choice", "topic": "Grammar",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "15. Unless we continue to use non-renewable resources, we pollute the environment.",
     "options": ["A. non-renewable", "B. Unless", "C. pollute", "D. continue"],
     "answer": "B. Unless",
     "explanation": "Unless = If … not làm câu vô lý → phải dùng If. (Bảng đáp án trong file ghi D nhưng lời giải chi tiết chỉ rõ lỗi sai là “Unless”.)"},

    {"type": "choice", "topic": "Vocabulary",
     "section_start": None,
     "section_instruction": "Mark the letter A, B, C, or D to indicate the correct answers to each of the following questions.",
     "passage_text": None,
     "q": "16. There are many ways to __________money for charity.",
     "options": ["A. buy", "B. collect", "C. raise", "D. recycle"],
     "answer": "C. raise",
     "explanation": "raise money: gây quỹ."},
    {"type": "choice", "topic": "Vocabulary",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "17. My teacher is teaching us about ___________ as a way to keep fit.",
     "options": ["A. talking", "B. running", "C. littering", "D. donation"],
     "answer": "B. running",
     "explanation": "running: chạy bộ – cách giữ dáng."},
    {"type": "choice", "topic": "Vocabulary",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "18. We're going to ___________ a clean-up activity at the beach this weekend.",
     "options": ["A. join", "B. make", "C. take part", "D. donate"],
     "answer": "A. join",
     "explanation": "join: tham gia (take part thiếu in)."},
    {"type": "choice", "topic": "Vocabulary",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "19. Today we learned a lesson about _________ at school. Our teacher emphasizes that eating healthily was a good way to avoid diseases.",
     "options": ["A. parties", "B. diet", "C. restaurants", "D. meals"],
     "answer": "B. diet",
     "explanation": "diet: chế độ ăn. (Bảng đáp án trong file ghi C nhưng lời giải chi tiết viết “a lesson about diet”.)"},
    {"type": "choice", "topic": "Vocabulary",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "20. To take care of skin with acne, don’t ___________.",
     "options": ["A. eat much healthy food", "B. pop spots", "C. go to bed early", "D. drink enough water"],
     "answer": "B. pop spots",
     "explanation": "pop spots: nặn mụn."},

    {"type": "choice", "topic": "Communication",
     "section_start": None,
     "section_instruction": "Mark the letter A, B, C, or D to indicate the option that best completes each of the following exchanges.",
     "passage_text": None,
     "q": "21. Sean: Do you like dancing? - Emma: __________",
     "options": ["A. Yes, I prefer outdoor activities.", "B. Oh, I'd love to. Thanks", "C. Yes, a lot. Dancing is great!", "D. I'm going to join a dance club."],
     "answer": "C. Yes, a lot. Dancing is great!",
     "explanation": "Trả lời câu hỏi Do you like …? → Yes, a lot."},
    {"type": "choice", "topic": "Communication",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "23. Ross: A lot of people are infected with this flu virus. How can I avoid it? - Mike: __________",
     "options": ["A. You should cover your mouth and nose with your hands.", "B. You should eat a lot of chocolate every day. It's good for your health.", "C. You should eat a lot of meat and cheese.", "D. You should wear a mask when going out."],
     "answer": "D. You should wear a mask when going out.",
     "explanation": "Đeo khẩu trang khi ra ngoài để tránh cúm."},
    {"type": "choice", "topic": "Communication",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "24. Huong: You should wash your hands before eating. - Lan: ____________",
     "options": ["A. Sorry, I don't mind.", "B. Not at all.", "C. Better next time.", "D. Oh, that's right. I'll do it."],
     "answer": "D. Oh, that's right. I'll do it.",
     "explanation": "Đáp lại lời khuyên: Oh, that's right. I'll do it."},

    {"type": "fill", "topic": "Cloze",
     "section_start": "PART 3. READING",
     "section_instruction": "Read the following passage and choose the correct word or phrase given in the box to fill in each of the numbered blanks. There is ONE extra word or phrase you do not need to use. [Box: skip – prepare – Therefore – energy – high in nutrients – Because]",
     "passage_text": "[skip / prepare / Therefore / energy / high in nutrients / Because]\nLike many people, I never miss breakfast. I try to get up early to (26) __________ a meal every morning. Having breakfast provides me with a lot of (27) __________ throughout the morning. (28) __________, I can concentrate on my work and study better. If I don't eat breakfast, I will feel tired and sleepy. I often have scrambled eggs, buttered toast, or noodles for breakfast because they are easy to make and (29) ____________. I think breakfast is the most important meal of the day, so people should not (30) ______________ it.\n(Adapted from Great writing 2: Great paragraphs, p.17, 2nd edition)",
     "q": "26. I try to get up early to (26) __________ a meal every morning.",
     "answer": "prepare",
     "explanation": "prepare a meal: chuẩn bị bữa ăn."},
    {"type": "fill", "topic": "Cloze",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "27. Having breakfast provides me with a lot of (27) __________ throughout the morning.",
     "answer": "energy",
     "explanation": "a lot of + danh từ: energy."},
    {"type": "fill", "topic": "Cloze",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "28. (28) __________, I can concentrate on my work and study better.",
     "answer": "Therefore",
     "explanation": "Therefore, … : vì vậy."},
    {"type": "fill", "topic": "Cloze",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "29. because they are easy to make and (29) ____________.",
     "answer": "high in nutrients",
     "explanation": "high in nutrients: giàu dinh dưỡng."},
    {"type": "fill", "topic": "Cloze",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "30. so people should not (30) ______________ it.",
     "answer": "skip",
     "explanation": "skip breakfast: bỏ bữa sáng."},

    {"type": "choice", "topic": "Reading",
     "section_start": None,
     "section_instruction": "Read the following passage and decide whether the following statements are true (T) or false (F).",
     "passage_text": "A hobby is something that people do for fun. When they have free time from work or school, lots of people pursue their interests. Common hobbies include creating websites, collecting baseball cards, and drawing. Most hobbies involve creating something, enjoying the scenery, collecting items or using special equipment. It can be collecting things like stamps, coins, seashells, or even action figures. Some creative people prefer to draw paintings, make crafts, or build models. People who love nature may enjoy bird-watching or gardening. For hobbies like amateur radio, photography, and computer programming, equipment is necessary.\nBefore the 1900s most people spent nearly all their time working and caring for their families. Only the rich people could pursue hobbies. After the Industrial Revolution, people had more time to develop their hobbies. Today, a lot of people use their free time to play video games and surf the Internet.\n(Adapted from https://kids.britannica.com/kids/article/hobby/390767)",
     "q": "31. Drawing is not a common hobby.",
     "options": ["A. True", "B. False"],
     "answer": "B. False",
     "explanation": "Common hobbies include creating websites, collecting baseball cards, and drawing."},
    {"type": "choice", "topic": "Reading",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "32. Building models is the preference of all creative people.",
     "options": ["A. True", "B. False"],
     "answer": "B. False",
     "explanation": "Some creative people prefer to … build models (chỉ một số)."},
    {"type": "choice", "topic": "Reading",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "33. Bird-watching is suitable for nature lovers.",
     "options": ["A. True", "B. False"],
     "answer": "A. True",
     "explanation": "People who love nature may enjoy bird-watching or gardening."},
    {"type": "choice", "topic": "Reading",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "34. The poor people could follow their interests before the 1990s.",
     "options": ["A. True", "B. False"],
     "answer": "B. False",
     "explanation": "Only the rich people could pursue hobbies."},
    {"type": "choice", "topic": "Reading",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "35. Playing computer games is one of the popular hobbies today.",
     "options": ["A. True", "B. False"],
     "answer": "A. True",
     "explanation": "Today, a lot of people use their free time to play video games and surf the Internet."},

    {"type": "fill", "topic": "Writing",
     "section_start": "PART 4. WRITING",
     "section_instruction": "Reorder the words and phrases to make complete sentences.",
     "passage_text": None,
     "q": "36. favourite / are / my / painting / and / Drawing / hobbies.",
     "answer": "Drawing and painting are my favourite hobbies.",
     "explanation": ""},
    {"type": "fill", "topic": "Writing",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "37. works / a doctor / a big hospital / My father / in / in the city. / as",
     "answer": "My father works as a doctor in a big hospital in the city.",
     "explanation": ""},
    {"type": "fill", "topic": "Writing",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "38. my sister / an essay. / watching / a comedy / is writing / while / I’m",
     "answer": "I'm watching a comedy while my sister is writing an essay.",
     "explanation": ""},
    {"type": "fill", "topic": "Writing",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "39. Eating / regular exercise / for a long life. / doing / healthily / and / are important",
     "answer": "Eating healthily and doing regular exercise are important for a long life.",
     "explanation": ""},
    {"type": "fill", "topic": "Writing",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "40. vitamins / contain / lots of / Fruit and / vegetables / and minerals. / essential",
     "answer": "Fruit and vegetables contain lots of essential vitamins and minerals.",
     "explanation": ""},
]

# ══════════════════════════════════════════════════════════════════════════════
# ĐỀ SỐ 5
# ══════════════════════════════════════════════════════════════════════════════
_DE_5 = [
    {"type": "choice", "topic": "Pronunciation",
     "section_start": "PART 2. LANGUAGE",
     "section_instruction": "Choose the word that has the underlined part pronounced differently from the others.",
     "passage_text": None,
     "q": "6. Choose the word whose underlined part is pronounced differently: A. m(a)n B. c(a)t C. d(a)y D. p(a)n",
     "options": ["A. man", "B. cat", "C. day", "D. pan"],
     "answer": "C. day",
     "explanation": "day /deɪ/; man, cat, pan đọc /æ/."},
    {"type": "choice", "topic": "Pronunciation",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "7. Choose the word whose underlined part is pronounced differently: A. l(e)tter B. s(e)ntence C. tw(e)nty D. f(e)ver",
     "options": ["A. letter", "B. sentence", "C. twenty", "D. fever"],
     "answer": "D. fever",
     "explanation": "fever /ˈfiːvə/ đọc /iː/; các từ còn lại đọc /e/."},
    {"type": "choice", "topic": "Pronunciation",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "8. Choose the word whose underlined part is pronounced differently: A. stop(s) B. hit(s) C. jog(s) D. work(s)",
     "options": ["A. stops", "B. hits", "C. jogs", "D. works"],
     "answer": "C. jogs",
     "explanation": "jogs /dʒɒɡz/ đuôi -s đọc /z/; stops, hits, works đọc /s/. (Bảng đáp án trong file ghi B nhưng lời giải chi tiết chỉ rõ C là /z/.)"},
    {"type": "choice", "topic": "Stress",
     "section_start": None,
     "section_instruction": "Choose the word whose main stress is different from the others.",
     "passage_text": None,
     "q": "9. Choose the word whose main stress is different: A. dollhouse B. cardboard C. collect D. common",
     "options": ["A. dollhouse", "B. cardboard", "C. collect", "D. common"],
     "answer": "C. collect",
     "explanation": "collect /kəˈlekt/ trọng âm âm tiết 2; các từ còn lại trọng âm âm tiết 1."},
    {"type": "choice", "topic": "Stress",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "10. Choose the word whose main stress is different: A. amazing B. gardening C. healthy D. timetable",
     "options": ["A. amazing", "B. gardening", "C. healthy", "D. timetable"],
     "answer": "A. amazing",
     "explanation": "amazing /əˈmeɪzɪŋ/ trọng âm âm tiết 2; các từ còn lại trọng âm âm tiết 1."},

    {"type": "choice", "topic": "Grammar",
     "section_start": None,
     "section_instruction": "Choose the correct options.",
     "passage_text": None,
     "q": "11. She ________ watching fashion shows on TV. She thinks they are boring.",
     "options": ["A. likes", "B. don’t like", "C. like", "D. doesn’t like"],
     "answer": "D. doesn’t like",
     "explanation": "She + doesn't like (câu sau: they are boring)."},
    {"type": "choice", "topic": "Grammar",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "12. She doesn’t like to take __________ medicine when she is sick.",
     "options": ["A. any", "B. many", "C. a lot", "D. some"],
     "answer": "A. any",
     "explanation": "any dùng trong câu phủ định với danh từ không đếm được (medicine)."},
    {"type": "choice", "topic": "Grammar",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "13. Mary and Lucy _________ listening to K-pop.",
     "options": ["A. like", "B. likes", "C. are like", "D. doesn’t like"],
     "answer": "A. like",
     "explanation": "Chủ ngữ số nhiều → like."},
    {"type": "choice", "topic": "Vocabulary",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "14. I like playing bowling at the __________.",
     "options": ["A. water park", "B. fair", "C. bowling alley", "D. market"],
     "answer": "C. bowling alley",
     "explanation": "bowling alley: sân chơi bowling."},
    {"type": "choice", "topic": "Vocabulary",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "15. Bob enjoys loud music, such as rock and __________.",
     "options": ["A. heavy metal", "B. country", "C. hip hop", "D. jazz"],
     "answer": "A. heavy metal",
     "explanation": "heavy metal: nhạc rock mạnh, âm lượng lớn."},
    {"type": "choice", "topic": "Grammar",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "16. Let’s meet ___________ midday ___________ Friday.",
     "options": ["A. at / at", "B. in / on", "C. at / on", "D. in / at"],
     "answer": "C. at / on",
     "explanation": "at midday; on Friday."},
    {"type": "choice", "topic": "Grammar",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "17. Bob Seger is _________ favorite rock singer. _________ songs are wonderful.",
     "options": ["A. my – His", "B. I – His", "C. my – He", "D. I – He"],
     "answer": "A. my – His",
     "explanation": "Tính từ sở hữu: my … His."},
    {"type": "choice", "topic": "Vocabulary",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "18. In Vietnam, it is impolite to __________ at people with your finger.",
     "options": ["A. shake", "B. point", "C. cross", "D. hug"],
     "answer": "B. point",
     "explanation": "point at: chỉ vào."},
    {"type": "choice", "topic": "Grammar",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "19. Anna: “________do you play football?” – Bob: “Twice a week.”",
     "options": ["A. How far", "B. When", "C. How often", "D. How long"],
     "answer": "C. How often",
     "explanation": "How often: hỏi tần suất (Twice a week)."},
    {"type": "choice", "topic": "Vocabulary",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "20. My sister is __________. She always tells the truth.",
     "options": ["A. popular", "B. selfish", "C. impatient", "D. honest"],
     "answer": "D. honest",
     "explanation": "honest: trung thực."},

    {"type": "choice", "topic": "Communication",
     "section_start": "PART 3. SPEAKING",
     "section_instruction": "Complete the conversation using the sentences in the boxes.",
     "passage_text": "A. You shouldn't eat too much unhealthy food.\nB. You should get enough sleep to get well soon.\nC. You should take some medicine to reduce the pain.\nD. You should drink more water.\nE. I feel tired, and I have a sore throat.\n\nDoctor: Good morning. How can I help you?\nPatient: (21) ___________\nDoctor: I see. Do you drink enough water every day?\nPatient: No. Sometimes, I drink too much coke.\nDoctor: (22) ___________ Do you eat fruit and vegetables?\nPatient: No, not really. I eat a lot of fast food such as French fries.\nDoctor: (23) ___________\nPatient: OK.\nDoctor: Do you sleep eight hours a night?\nPatient: Actually, I don’t.\nDoctor: (24) ___________\nPatient: Now, I can see that I have an unhealthy lifestyle. Should I take some medicine?\nDoctor: Yes. (25) ___________\nPatient: Thank you, Doctor.\nDoctor: You’re welcome.",
     "q": "21. Patient: (21) ___________",
     "options": ["A. You shouldn't eat too much unhealthy food.", "B. You should get enough sleep to get well soon.", "C. You should take some medicine to reduce the pain.", "D. You should drink more water.", "E. I feel tired, and I have a sore throat."],
     "answer": "E. I feel tired, and I have a sore throat.",
     "explanation": "Bệnh nhân trả lời câu hỏi How can I help you?"},
    {"type": "choice", "topic": "Communication",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "22. Doctor: (22) ___________ Do you eat fruit and vegetables?",
     "options": ["A. You shouldn't eat too much unhealthy food.", "B. You should get enough sleep to get well soon.", "C. You should take some medicine to reduce the pain.", "D. You should drink more water.", "E. I feel tired, and I have a sore throat."],
     "answer": "D. You should drink more water.",
     "explanation": "Bệnh nhân uống nhiều coke, ít nước → nên uống nhiều nước hơn."},
    {"type": "choice", "topic": "Communication",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "23. Doctor: (23) ___________ (sau khi bệnh nhân nói ăn nhiều fast food)",
     "options": ["A. You shouldn't eat too much unhealthy food.", "B. You should get enough sleep to get well soon.", "C. You should take some medicine to reduce the pain.", "D. You should drink more water.", "E. I feel tired, and I have a sore throat."],
     "answer": "A. You shouldn't eat too much unhealthy food.",
     "explanation": "Ăn nhiều fast food → không nên ăn nhiều đồ không lành mạnh."},
    {"type": "choice", "topic": "Communication",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "24. Doctor: (24) ___________ (sau khi bệnh nhân nói không ngủ đủ 8 tiếng)",
     "options": ["A. You shouldn't eat too much unhealthy food.", "B. You should get enough sleep to get well soon.", "C. You should take some medicine to reduce the pain.", "D. You should drink more water.", "E. I feel tired, and I have a sore throat."],
     "answer": "B. You should get enough sleep to get well soon.",
     "explanation": "Không ngủ đủ → nên ngủ đủ giấc."},
    {"type": "choice", "topic": "Communication",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "25. Doctor: Yes. (25) ___________",
     "options": ["A. You shouldn't eat too much unhealthy food.", "B. You should get enough sleep to get well soon.", "C. You should take some medicine to reduce the pain.", "D. You should drink more water.", "E. I feel tired, and I have a sore throat."],
     "answer": "C. You should take some medicine to reduce the pain.",
     "explanation": "Should I take some medicine? – Yes. You should take some medicine…"},

    {"type": "choice", "topic": "Cloze",
     "section_start": "PART 3. READING",
     "section_instruction": "Read Mr. Oaken's response to Wendy. Choose the correct options.",
     "passage_text": "Dear Wendy,\nI’m Darcy Oaken, Mayor of the county.\nThank you (26) ________ your letter. I agree that it is important to have good health. Fast food can be (27) ________, so it is difficult for young people to say no to it. However, eating fast food for a long period of time is not good for our health. According to official records, there are (28) ________ overweight people in the county. That is now a (29) ________. I agree that we should limit the number of fast-food restaurants and have more (30) ________ food stores throughout the county.\nThank you and let’s wait to see the changes.\nSincerely,\nDarcy Oaken",
     "q": "26. Thank you (26) ________ your letter.",
     "options": ["A. for", "B. to", "C. at", "D. in"],
     "answer": "A. for",
     "explanation": "Thank you for + N."},
    {"type": "choice", "topic": "Cloze",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "27. Fast food can be (27) ________, so it is difficult for young people to say no to it.",
     "options": ["A. difficult", "B. delicious", "C. hard", "D. easy"],
     "answer": "B. delicious",
     "explanation": "delicious: ngon."},
    {"type": "choice", "topic": "Cloze",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "28. there are (28) ________ overweight people in the county.",
     "options": ["A. much", "B. a lot of", "C. any", "D. a little"],
     "answer": "B. a lot of",
     "explanation": "a lot of + danh từ đếm được số nhiều, câu khẳng định."},
    {"type": "choice", "topic": "Cloze",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "29. That is now a (29) ________.",
     "options": ["A. key", "B. answer", "C. solution", "D. problem"],
     "answer": "D. problem",
     "explanation": "Nhiều người thừa cân → là một vấn đề (problem)."},
    {"type": "choice", "topic": "Cloze",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "30. have more (30) ________ food stores throughout the county.",
     "options": ["A. bad", "B. junk", "C. healthy", "D. unhealthy"],
     "answer": "C. healthy",
     "explanation": "healthy food stores: đối lập với fast-food restaurants."},

    {"type": "choice", "topic": "Reading",
     "section_start": None,
     "section_instruction": "Read Helen's blog post. Choose True or False.",
     "passage_text": "ABOUT ME\nHi all! My name’s Helen.\nThere are many activities to do in my free time, but I like making cakes the most. I learn how to make cakes by following instructions from the Internet and cookery books. They are really helpful. I can now make different kinds of cakes. They are delicious. My mother loves my cakes. I also like reading comics. My bookshelf contains Doraemon, Detective Conan, and many other comic series. I can learn many exciting things, such as fashion, lifestyle, or friendship. I can even draw characters in those books.\nWhat about you? What do you do in your free time?\nLeave a comment and let me know about your hobbies.",
     "q": "31. Reading comics is Helen’s favorite free time activity.",
     "options": ["A. True", "B. False"],
     "answer": "B. False",
     "explanation": "I like making cakes the most → sở thích yêu thích nhất là làm bánh. (Bảng đáp án trong file ghi True — sai so với bài đọc.)"},
    {"type": "choice", "topic": "Reading",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "32. Helen learns how to bake cakes from her mother.",
     "options": ["A. True", "B. False"],
     "answer": "B. False",
     "explanation": "I learn how to make cakes by following instructions from the Internet and cookery books."},
    {"type": "choice", "topic": "Reading",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "33. There are only some books on Helen’s bookshelf.",
     "options": ["A. True", "B. False"],
     "answer": "B. False",
     "explanation": "My bookshelf contains Doraemon, Detective Conan, and many other comic series."},
    {"type": "choice", "topic": "Reading",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "34. Helen can find a lot of useful knowledge in comics.",
     "options": ["A. True", "B. False"],
     "answer": "A. True",
     "explanation": "I can learn many exciting things, such as fashion, lifestyle, or friendship."},
    {"type": "choice", "topic": "Reading",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "35. People can write their hobbies in the comment box.",
     "options": ["A. True", "B. False"],
     "answer": "A. True",
     "explanation": "Leave a comment and let me know about your hobbies."},

    {"type": "fill", "topic": "Writing",
     "section_start": "PART 4. WRITING",
     "section_instruction": "Make complete sentences using the prompts.",
     "passage_text": None,
     "q": "36. I / go / gym / close friend / once / week.",
     "answer": "I go to the gym with my close friend once a week.",
     "explanation": ""},
    {"type": "fill", "topic": "Writing",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "37. The concert / not start / until 7:30 p.m.",
     "answer": "The concert does not start until 7:30 p.m.",
     "explanation": ""},
    {"type": "fill", "topic": "Writing",
     "section_start": None,
     "section_instruction": "Make a suitable question for the underlined words.",
     "passage_text": None,
     "q": "38. Nam is watching [a play] on television tonight. (phần gạch chân: a play)",
     "answer": "What is Nam watching on television tonight?",
     "explanation": "Hỏi về sự việc → What."},
    {"type": "fill", "topic": "Writing",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "39. Khoa is playing soccer at Thống Nhất Stadium [this afternoon]. (phần gạch chân: this afternoon)",
     "answer": "When is Khoa playing soccer at Thống Nhất Stadium?",
     "explanation": "Hỏi về thời gian → When."},
    {"type": "fill", "topic": "Writing",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "40. Kim is going bowling at the local sports center [with her brother]. (phần gạch chân: with her brother)",
     "answer": "Who is Kim going bowling with at the local sports center?",
     "explanation": "Hỏi về người → Who … with."},
]

EXAMS = {1: _DE_1, 2: _DE_2, 3: _DE_3, 4: _DE_4, 5: _DE_5}
