# -*- coding: utf-8 -*-
"""Đề Tiếng Anh 7 cuối HK1 (Global Success) — nguồn Google Drive (Loigiaihay.com).

Ghi chú:
- Chép nguyên văn từ 5 file PDF đề 1–5; đáp án lấy từ bảng "HƯỚNG DẪN GIẢI" trong file.
- BỎ QUA toàn bộ phần LISTENING (không có file audio): đề 1 câu 17–24, đề 2 câu 1–10,
  đề 3 câu 1–8, đề 4 câu 1–5, đề 5 câu 1–5. Số thứ tự câu giữ nguyên như đề gốc.
- PDF mất phần gạch chân: với câu phát âm, phần gạch chân (theo hướng dẫn giải) được
  đánh dấu trong ngoặc đơn, vd "wash(ed)"; với câu có từ gạch chân khác, ghi "(underlined: ...)".
- Đề 1 câu 4–5: đề gốc ghi "underlined part pronounced differently" nhưng hướng dẫn giải chấm
  theo trọng âm từ — giữ nguyên văn, topic "Stress", giải thích ghi rõ.
- Câu tự luận (viết lại câu, trả lời câu hỏi đọc hiểu, sắp xếp từ thành câu) dùng type "fill",
  đáp án là nguyên văn trong bảng đáp án; đề 2 và đề 3 bảng đáp án chỉ cho PHẦN điền thêm nên
  đáp án là phần đó (câu hỏi có ghi chú "chỉ điền phần còn thiếu").
- Không có câu nào cần hình ảnh. Thời gian làm bài không ghi trong đề gốc.
"""

DURATION = 60   # phút (đề gốc không ghi; mặc định 60)

SOURCES = {
    1: "de-thi-hoc-ki-1-tieng-anh-7-global-success-de-so-1-1668660407.pdf (1pF8N_HVG9z16v6Vykz_J58vNVpu2_bNV)",
    2: "de-thi-hoc-ki-1-tieng-anh-7-global-success-de-so-2-1672194571.pdf (1MxZJDK4kTr7MFMrbOOs9uPVjgfRaOMR_)",
    3: "de-thi-hoc-ki-1-tieng-anh-7-global-success-de-so-3-1668669444.pdf (1GbOqdpH5arQ3X4yZpTK0PWTL-GithEEk)",
    4: "de-thi-hoc-ki-1-tieng-anh-7-global-success-de-so-4-1672456373.pdf (1-N8OnEaEAsHa7y8u4alfZcoxd0huChWC)",
    5: "de-thi-hoc-ki-1-tieng-anh-7-global-success-de-so-5-1668755006.pdf (1mhFlTzFfGXaTDKHc-mh8lQ3M7Z2ABRRf)",
}

# =====================================================================
# ĐỀ SỐ 1
# =====================================================================
_DE_1 = [
    {"type": "choice", "topic": "Pronunciation",
     "section_start": "A. LANGUAGE FOCUS",
     "section_instruction": "Exercise 1: Circle the word whose underlined part is pronounced differently from the others’.",
     "passage_text": None,
     "q": "1. A. start(ed) B. wash(ed) C. decid(ed) D. visit(ed)",
     "options": ["A. started", "B. washed", "C. decided", "D. visited"],
     "answer": "B. washed",
     "explanation": "Đuôi -ed: washed /t/; started, decided, visited /ɪd/."},
    {"type": "choice", "topic": "Pronunciation",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "2. A. cou(gh) B. ni(gh)t C. fli(gh)t D. hi(gh)",
     "options": ["A. cough", "B. night", "C. flight", "D. high"],
     "answer": "A. cough",
     "explanation": "cough /kɒf/ – gh đọc /f/; night, flight, high – gh câm."},
    {"type": "choice", "topic": "Pronunciation",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "3. A. (a)way B. (a)round C. c(o)llection D. cl(a)ssmate",
     "options": ["A. away", "B. around", "C. collection", "D. classmate"],
     "answer": "D. classmate",
     "explanation": "classmate /ˈklɑːsmeɪt/ – /ɑː/; away, around, collection – /ə/."},
    {"type": "choice", "topic": "Stress",
     "section_start": None,
     "section_instruction": "Exercise 2: Choose the word whose underlined part is pronounced differently from the others’.",
     "passage_text": None,
     "q": "4. A. homeless B. healthy C. active D. disease",
     "options": ["A. homeless", "B. healthy", "C. active", "D. disease"],
     "answer": "D. disease",
     "explanation": "Hướng dẫn giải chấm theo trọng âm: disease /dɪˈziːz/ nhấn âm 2; các từ còn lại nhấn âm 1."},
    {"type": "choice", "topic": "Stress",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "5. A. water B. donate C. tutor D. hobby",
     "options": ["A. water", "B. donate", "C. tutor", "D. hobby"],
     "answer": "B. donate",
     "explanation": "Hướng dẫn giải chấm theo trọng âm: donate /dəʊˈneɪt/ nhấn âm 2; các từ còn lại nhấn âm 1."},
    {"type": "choice", "topic": "Communication",
     "section_start": None,
     "section_instruction": "Exercise 3: Choose the best option to complete each sentence. Circle A, B, C or D.",
     "passage_text": None,
     "q": "6. - Lisa: “Last summer, we provided food for homeless children in Ha Noi.” - Kim: “_____”",
     "options": ["A. Sounds like great work!", "B. Wonderful!", "C. I don’t agree with you.", "D. A and B are correct."],
     "answer": "D. A and B are correct.",
     "explanation": "Cả A và B đều là lời khen phù hợp."},
    {"type": "choice", "topic": "Vocabulary",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "7. Which word is CLOSEST in meaning to the underlined word? Eating too many sweets and fast food makes you gain weight. (underlined: gain)",
     "options": ["A. put on", "B. lose", "C. put off", "D. spend"],
     "answer": "A. put on",
     "explanation": "gain weight = put on weight: tăng cân."},
    {"type": "choice", "topic": "Grammar",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "8. My family enjoys _____ because we can sell flowers for money.",
     "options": ["A. garden", "B. to garden", "C. gardening", "D. to gardening"],
     "answer": "C. gardening",
     "explanation": "enjoy + V-ing."},
    {"type": "choice", "topic": "Grammar",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "9. We _____ vegetables to a nursery school last winter.",
     "options": ["A. donate", "B. was donate", "C. did donate", "D. donated"],
     "answer": "D. donated",
     "explanation": "Quá khứ đơn, dấu hiệu “last winter”."},
    {"type": "choice", "topic": "Grammar",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "10. You can help young children by ____ them to do homework before or after school.",
     "options": ["A. helping", "B. doing", "C. working", "D. offering"],
     "answer": "A. helping",
     "explanation": "by + V-ing: bằng cách…"},
    {"type": "choice", "topic": "Communication",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "11. Which is the best advice for the following situation: Linda wants beautiful healthy skin.",
     "options": ["A. She shouldn’t talk in the class.", "B. She should eat more fruit and vegetables.", "C. She shouldn’t drink much water.", "D. She should eat more sweets."],
     "answer": "B. She should eat more fruit and vegetables.",
     "explanation": "Nên ăn nhiều rau quả để có làn da đẹp."},
    {"type": "choice", "topic": "Grammar",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "12. I have to go to the market now. There isn’t _____ food for our dinner.",
     "options": ["A. some", "B. any", "C. few", "D. lots"],
     "answer": "B. any",
     "explanation": "Câu phủ định với danh từ không đếm được → any."},
    {"type": "choice", "topic": "Vocabulary",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "13. _____ is an abnormally high body temperature.",
     "options": ["A. Toothache", "B. Fever", "C. Sunburn", "D. Obesity"],
     "answer": "B. Fever",
     "explanation": "Fever: sốt."},
    {"type": "choice", "topic": "Grammar",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "14. Her new house is not ______ her old one.",
     "options": ["A. as big as", "B. biger than", "C. as big than", "D. bigger as"],
     "answer": "A. as big as",
     "explanation": "So sánh bằng: not as + adj + as."},
    {"type": "choice", "topic": "Vocabulary",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "15. Yesterday, we _____ litter around our area and recycled them.",
     "options": ["A. helped", "B. donated", "C. picked up", "D. sold"],
     "answer": "C. picked up",
     "explanation": "pick up litter: nhặt rác."},
    {"type": "choice", "topic": "Grammar",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "16. Which part of the sentence is the underlined part? We should do physical exercise. (underlined: physical exercise)",
     "options": ["A. Subject", "B. Verb", "C. Object", "D. Adverb"],
     "answer": "C. Object",
     "explanation": "“physical exercise” là tân ngữ của “do”."},
    # B. LISTENING (câu 17–24): bỏ qua, không có audio.
    {"type": "choice", "topic": "Reading",
     "section_start": "C. READING",
     "section_instruction": "Exercise 1: Read the passage and choose the best answer for each of the questions.",
     "passage_text": "Baking is one of my favourite hobbies. Baking allows me to be creative and hard-working. First, I can follow the recipe exactly as written, or I can change the recipe by adding new ingredients. The second reason why I like baking is because the entire process of baking brings me a lot of fun. I love to go to the grocery to shop for ingredients, and then combine them all together to make a product that many people enjoy. Being able to share things that I bake is another reason why. I love this hobby. Many of my friends look forward to the tasty treat that I share with them. These are just a few of the reasons why I am fond of baking.",
     "q": "25. It is obvious in the passage that _____.",
     "options": ["A. the author loves baking for many reasons", "B. the author likes baking because she likes eating delicious food", "C. baking is one kind of kitchen arts", "D. the author enjoys baking because she wants to be a chef"],
     "answer": "A. the author loves baking for many reasons",
     "explanation": "Đoạn văn nêu nhiều lý do tác giả thích nướng bánh."},
    {"type": "choice", "topic": "Reading",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "26. Why does the author love baking?",
     "options": ["A. She can change the recipe by adding new ingredients.", "B. She likes going to the grocery for buying ingredients and combining them to make a new product.", "C. She wants to share delicious meals with her friends.", "D. A, B and C are correct."],
     "answer": "D. A, B and C are correct.",
     "explanation": "Đoạn văn nêu cả 3 lý do A, B, C."},
    {"type": "choice", "topic": "Reading",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "27. Which statement is NOT true?",
     "options": ["A. The author becomes creative and lazy with cooking.", "B. The author likes shopping for ingredients.", "C. The author loves sharing good meals with her friends.", "D. The author finds baking interesting and funny."],
     "answer": "A. The author becomes creative and lazy with cooking.",
     "explanation": "“Baking allows me to be creative and hard-working” – không phải lazy."},
    {"type": "choice", "topic": "Reading",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "28. We understand from the passage that _____.",
     "options": ["A. the author loves baking, but she doesn’t like doing other activities", "B. the author loves doing many things", "C. the author not only loves baking but also enjoys painting", "D. baking is one of the author’s hobbies"],
     "answer": "D. baking is one of the author’s hobbies",
     "explanation": "“Baking is one of my favourite hobbies.”"},
    {"type": "choice", "topic": "Reading",
     "section_start": None,
     "section_instruction": "Exercise 2: Read the passage and decide whether the statements are True or False.",
     "passage_text": "FOOD FESTIVAL\nSarah works for a local charity organization that gives poor children an opportunity to taste “foreign” food. This year “Wish you were here” has organized a food festival to raise enough money to send to children in Cornwall. They are hoping to attract a lot of visitors and they have already decided that the food festival is popular, so it will take place every year.\nThere are many things to do and see at the festival. You can buy food from many restaurants and you don’t need to break the bank because meals are expensive. Children are welcome and their meals only cost nothing. Other events at the festival include face-painting and a competition which is open to participants from all age groups. Families will be especially pleased to see in an area when their children can have a meal.",
     "q": "29. The food festival is organized to raise money for children living in Cornwall.",
     "options": ["A. True", "B. False"],
     "answer": "A. True",
     "explanation": "“…to raise enough money to send to children in Cornwall.”"},
    {"type": "choice", "topic": "Reading",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "30. This festival is hoped to be held every month.",
     "options": ["A. True", "B. False"],
     "answer": "B. False",
     "explanation": "“…it will take place every year.”"},
    {"type": "choice", "topic": "Reading",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "31. Children attending this festival have to pay for their meal.",
     "options": ["A. True", "B. False"],
     "answer": "B. False",
     "explanation": "“Children are welcome and their meals only cost nothing.”"},
    {"type": "choice", "topic": "Reading",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "32. Parents are happy because they can see their children having a good meal.",
     "options": ["A. True", "B. False"],
     "answer": "A. True",
     "explanation": "“Families will be especially pleased to see … their children can have a meal.”"},
    {"type": "choice", "topic": "Writing",
     "section_start": "D. WRITING",
     "section_instruction": "Choose the sentence that is made from rearranging the words.",
     "passage_text": None,
     "q": "33. should/ We/ our bodies/ keep/ to/ avoid/ warm/ or/ flu/ cold/.",
     "options": ["A. We should keep our bodies cold to avoid flu or warm.", "B. We should keep our bodies warm to avoid flu or cold.", "C. We should keep our bodies to avoid flu or cold warm.", "D. We should warm keep our bodies to avoid flu or cold."],
     "answer": "B. We should keep our bodies warm to avoid flu or cold.",
     "explanation": "Chúng ta nên giữ ấm cơ thể để tránh cảm cúm hay cảm lạnh."},
    {"type": "choice", "topic": "Writing",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "34. you/ Do/ enjoy/ teddy bears/ collecting/?",
     "options": ["A. Do you enjoy collecting teddy bears?", "B. Do enjoy you collecting teddy bears?", "C. You do enjoy collecting teddy bears?", "D. You enjoy do collecting teddy bears?"],
     "answer": "A. Do you enjoy collecting teddy bears?",
     "explanation": "Câu hỏi Yes/No: Do + S + V?"},
    {"type": "choice", "topic": "Writing",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "35. We/ community/ activities/ join/ a/ twice/ year/.",
     "options": ["A. We join activities community twice a year.", "B. We join twice a year community activities.", "C. We join activities twice a year community.", "D. We join community activities twice a year."],
     "answer": "D. We join community activities twice a year.",
     "explanation": "S + V + O + trạng ngữ tần suất."},
    {"type": "choice", "topic": "Writing",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "36. often/ He/ reads/ ,/so/ his eyes/ books/ in/ dim light/ hurt/.",
     "options": ["A. His eyes hurt, so he often reads books in dim light.", "B. He often reads books in dim light, so his eyes hurt.", "C. He often reads books, so his eyes hurt in dim light.", "D. His eyes hurt in dim light, so he often reads books."],
     "answer": "B. He often reads books in dim light, so his eyes hurt.",
     "explanation": "Nguyên nhân (đọc sách nơi thiếu sáng) → kết quả (đau mắt)."},
    {"type": "choice", "topic": "Writing",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "37. The Japanese work hard, and they exercise regularly.",
     "options": ["A. The Japanese work hard and exercise regularly.", "B. The Japanese don’t work hard, so they exercise regularly.", "C. The Japanese work hard, but they don’t exercise regularly.", "D. The Japanese don’t work hard and exercise regularly."],
     "answer": "A. The Japanese work hard and exercise regularly.",
     "explanation": "Giữ nguyên nghĩa, rút gọn chủ ngữ trùng."},
    {"type": "choice", "topic": "Writing",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "38. My aunt really loves surfing the Internet in her free time.",
     "options": ["A. My aunt doesn’t like surfing the Internet in her free time.", "B. My aunt adores surfing the Internet in her free time.", "C. My aunt doesn’t mind surfing the Internet in her free time.", "D. My aunt prefers surfing the Internet to listening to music in her free time."],
     "answer": "B. My aunt adores surfing the Internet in her free time.",
     "explanation": "really love = adore."},
    {"type": "choice", "topic": "Writing",
     "section_start": None,
     "section_instruction": "Choose the second sentence that has the same meaning with the first.",
     "passage_text": None,
     "q": "39. Cindy had a temperature yesterday, but she went to school.",
     "options": ["A. Although Cindy had a temperature yesterday, she went to school.", "B. Cindy had a temperature yesterday because she went to school.", "C. Cindy went to school yesterday, so she had a temperature.", "D. Cindy went to school yesterday, and she had a temperature."],
     "answer": "A. Although Cindy had a temperature yesterday, she went to school.",
     "explanation": "but = although (mặc dù)."},
    {"type": "choice", "topic": "Writing",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "40. Jimmy’s hobby is horse riding.",
     "options": ["A. Jimmy rides horses as a hobby.", "B. Horse riding is not Jimmy’s favourite thing.", "C. Jimmy does not enjoy riding horses.", "D. Jimmy doesn’t mind riding horses."],
     "answer": "A. Jimmy rides horses as a hobby.",
     "explanation": "Sở thích của Jimmy là cưỡi ngựa."},
]

# =====================================================================
# ĐỀ SỐ 2
# =====================================================================
_DE_2 = [
    # LISTENING (câu 1–10): bỏ qua, không có audio.
    {"type": "choice", "topic": "Pronunciation",
     "section_start": "LANGUAGE FOCUS",
     "section_instruction": "Exercise 2: Choose the word whose underlined part is pronounced differently from the others’.",
     "passage_text": None,
     "q": "11. A. vi(s)ion B. plea(s)ure C. impre(ss)ion",
     "options": ["A. vision", "B. pleasure", "C. impression"],
     "answer": "C. impression",
     "explanation": "impression /ʃ/; vision, pleasure /ʒ/."},
    {"type": "choice", "topic": "Pronunciation",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "12. A. so(c)ial B. (c)ity C. (c)enter",
     "options": ["A. social", "B. city", "C. center"],
     "answer": "A. social",
     "explanation": "social /ʃ/; city, center /s/."},
    {"type": "choice", "topic": "Pronunciation",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "13. A. w(a)nt B. w(a)lk C. w(a)ter",
     "options": ["A. want", "B. walk", "C. water"],
     "answer": "A. want",
     "explanation": "want /ɒ/; walk, water /ɔː/."},
    {"type": "choice", "topic": "Pronunciation",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "14. A. p(o)p B. b(o)ttle C. r(o)ll",
     "options": ["A. pop", "B. bottle", "C. roll"],
     "answer": "C. roll",
     "explanation": "roll /əʊ/; pop, bottle /ɒ/."},
    {"type": "choice", "topic": "Pronunciation",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "15. A. (ch)emical B. tea(ch)er C. (ch)aracter",
     "options": ["A. chemical", "B. teacher", "C. character"],
     "answer": "B. teacher",
     "explanation": "teacher /tʃ/; chemical, character /k/."},
    {"type": "choice", "topic": "Pronunciation",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "16. A. (g)eneration B. ma(g)ic C. (g)rab",
     "options": ["A. generation", "B. magic", "C. grab"],
     "answer": "C. grab",
     "explanation": "grab /ɡ/; generation, magic /dʒ/."},
    {"type": "choice", "topic": "Grammar",
     "section_start": None,
     "section_instruction": "Exercise 3: Choose the best option to complete each sentence. Circle A, B, or C.",
     "passage_text": None,
     "q": "17. The famous singer’s newest album is not as _________ her old one.",
     "options": ["A. expensive", "B. more expensive", "C. expensive as"],
     "answer": "C. expensive as",
     "explanation": "So sánh bằng: as + adj + as."},
    {"type": "choice", "topic": "Vocabulary",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "18. I don’t think my grandmom cooked this dish. The taste is so _______ from her usual recipe.",
     "options": ["A. different", "B. same", "C. as"],
     "answer": "A. different",
     "explanation": "different from: khác với."},
    {"type": "choice", "topic": "Grammar",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "19. My best friend is a big fan of Imagine Dragons. He bought _______ CDs, posters and albums.",
     "options": ["A. a", "B. any", "C. a lot of"],
     "answer": "C. a lot of",
     "explanation": "Danh từ số nhiều, câu khẳng định → a lot of."},
    {"type": "choice", "topic": "Grammar",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "20. A: I’m hungry! - B: Would you like to eat _____ pasta?",
     "options": ["A. some", "B. a lot of", "C. any"],
     "answer": "A. some",
     "explanation": "Câu mời → some."},
    {"type": "choice", "topic": "Vocabulary",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "21. Trinh Cong Son is one of Viet Nam’s greatest _______.",
     "options": ["A. singers", "B. scientists", "C. composers"],
     "answer": "C. composers",
     "explanation": "composer: nhạc sĩ sáng tác."},
    {"type": "choice", "topic": "Vocabulary",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "22. The fruit tea is too sour. Let me add some ________.",
     "options": ["A. flour", "B. salt", "C. sugar"],
     "answer": "C. sugar",
     "explanation": "Trà chua quá → thêm đường."},
    {"type": "choice", "topic": "Vocabulary",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "23. The grade 9 students have to excellently _____ the entrance exam to enter this gifted school.",
     "options": ["A. perform", "B. pass", "C. study"],
     "answer": "B. pass",
     "explanation": "pass the exam: vượt qua kỳ thi."},
    {"type": "choice", "topic": "Grammar",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "24. What do you usually do _____ the summer holiday?",
     "options": ["A. at", "B. in", "C. on"],
     "answer": "B. in",
     "explanation": "in the summer holiday."},
    {"type": "choice", "topic": "Grammar",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "25. A: What is your address? B: It’s ______ 30 Tran Hung Dao Street.",
     "options": ["A. at", "B. in", "C. on"],
     "answer": "A. at",
     "explanation": "at + địa chỉ có số nhà."},
    {"type": "choice", "topic": "Grammar",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "26. You can see the music room _____ the second floor of the building over there.",
     "options": ["A. at", "B. in", "C. on"],
     "answer": "C. on",
     "explanation": "on + tầng."},
    {"type": "fill", "topic": "Grammar",
     "section_start": None,
     "section_instruction": "Exercise 4: Supply the correct form of the verbs in brackets.",
     "passage_text": None,
     "q": "27. Watch out! You ___________ (put) too much salt into the soup.",
     "answer": "are putting",
     "explanation": "Hiện tại tiếp diễn – hành động đang xảy ra (Watch out!)."},
    {"type": "fill", "topic": "Grammar",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "28. There _______ (be) a lot of chili sauce in my banh mi. It’s too much for me!",
     "answer": "is",
     "explanation": "chili sauce không đếm được → is."},
    {"type": "fill", "topic": "Grammar",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "29. This weekend, we ___________ (visit) my dream high school. I can’t wait!",
     "answer": "are visiting",
     "explanation": "Hiện tại tiếp diễn diễn tả kế hoạch tương lai."},
    {"type": "fill", "topic": "Grammar",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "30. I’m going to the supermarket now. Do you want me _______ (buy) anything for dinner?",
     "answer": "to buy",
     "explanation": "want sb to V."},
    {"type": "choice", "topic": "Reading",
     "section_start": "READING",
     "section_instruction": "Exercise 5: Read the passage. Circle the best answer A, B, or C to each of the questions.",
     "passage_text": "There are many different ways for people to discover and listen to music. British teenagers can enjoy listening to music on the Internet, on TV or they can go outside and enjoy live performances.\nThe O2 in London is the second largest live music arena in Europe. There you can see world-famous bands such as One Direction, Justin Bieber, Scissor Sisters, Prince, The Rolling Stones, Elton John, and Take That. This massive stadium has space for 20,000 people. It also has 548 toilets! Tickets are not cheap. You can pay more than £50 to see a concert at The O2.\nWhat about free live music? There are music festivals across Britain every year that are completely free of charge. Last year more than 150,000 people went to the Tramlines free music festival in Sheffield in the north of England. The two-day festival is held every July. Last year there were nine hundred performances in total including local bands as well as music from all over the world.",
     "q": "31. What is the passage mainly about?",
     "options": ["A. The expensive tickets in The O2", "B. The parks where British people can watch music performances", "C. Two ways for British people to enjoy live music"],
     "answer": "C. Two ways for British people to enjoy live music",
     "explanation": "Hai cách: The O2 (có phí) và lễ hội miễn phí."},
    {"type": "choice", "topic": "Reading",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "32. According to the passage, _______ is the place where some world-famous bands performed.",
     "options": ["A. The O2", "B. Tramlines", "C. Sheffield"],
     "answer": "A. The O2",
     "explanation": "“There you can see world-famous bands…”"},
    {"type": "choice", "topic": "Reading",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "33. How many people can enjoy the live music performances in the O2 stadium?",
     "options": ["A. 548", "B. 20,000", "C. 150,000"],
     "answer": "B. 20,000",
     "explanation": "“…has space for 20,000 people.”"},
    {"type": "choice", "topic": "Reading",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "34. How long does the Tramlines free music last every July?",
     "options": ["A. 1 week", "B. 2 days", "C. 2 months"],
     "answer": "B. 2 days",
     "explanation": "“The two-day festival is held every July.”"},
    {"type": "choice", "topic": "Reading",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "35. How many performances in Tramlines festival last year?",
     "options": ["A. 500", "B. 90", "C. 900"],
     "answer": "C. 900",
     "explanation": "“…nine hundred performances in total…”"},
    {"type": "fill", "topic": "Cloze",
     "section_start": None,
     "section_instruction": "Exercise 6: Complete the reading passage with the words or phrases in the box.",
     "passage_text": "Box: raise – than – Remember – much – heart problems\n\nPeople who eat a lot of fruit and vegetables are less likely to have (36)__________. You should eat at least five portions of fruit and vegetables a day. One portion is e.g. a banana, an apple, one slice of melon or pineapple or two plums. (37) ________ that potatoes are not included on that list.\nEating too much salt can (38) ______ your blood pressure. And people with high blood pressure are three times more likely to develop heart disease or have a stroke (39) ________ people with normal blood pressure. 75% of the salt we eat is already in the food we buy, such as breakfast cereals, soups, sauces. So you could easily be eating too (40) _________ salt without realising it.",
     "q": "36. People who eat a lot of fruit and vegetables are less likely to have (36)__________.",
     "answer": "heart problems",
     "explanation": "heart problems: các vấn đề tim mạch."},
    {"type": "fill", "topic": "Cloze",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "37. (37) ________ that potatoes are not included on that list.",
     "answer": "Remember",
     "explanation": "Remember that…: Hãy nhớ rằng…"},
    {"type": "fill", "topic": "Cloze",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "38. Eating too much salt can (38) ______ your blood pressure.",
     "answer": "raise",
     "explanation": "raise your blood pressure: làm tăng huyết áp."},
    {"type": "fill", "topic": "Cloze",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "39. …three times more likely to develop heart disease or have a stroke (39) ________ people with normal blood pressure.",
     "answer": "than",
     "explanation": "more … than."},
    {"type": "fill", "topic": "Cloze",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "40. So you could easily be eating too (40) _________ salt without realising it.",
     "answer": "much",
     "explanation": "too much + danh từ không đếm được."},
    {"type": "fill", "topic": "Writing",
     "section_start": "WRITING",
     "section_instruction": "Exercise 7: Complete the second sentence, using the words in brackets.",
     "passage_text": None,
     "q": "41. I think hip hop music is more exciting than jazz music. (as … as)\nI think jazz music is not ___________. (chỉ điền phần còn thiếu)",
     "answer": "as exciting as hip hop music.",
     "explanation": "Đáp án: I think jazz music is not as exciting as hip hop music."},
    {"type": "fill", "topic": "Writing",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "42. The poster in Jack’s room is not different from the poster in the store. (like)\nThe poster in the store ___________. (chỉ điền phần còn thiếu)",
     "answer": "is like the poster in Jack’s room.",
     "explanation": "Đáp án: The poster in the store is like the poster in Jack’s room."},
    {"type": "fill", "topic": "Writing",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "43. Baking cakes is Jane’s hobby. (interested)\nJane ___________. (chỉ điền phần còn thiếu)",
     "answer": "is interested in baking cakes.",
     "explanation": "Đáp án: Jane is interested in baking cakes."},
    {"type": "fill", "topic": "Writing",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "44. Because of the heavy rain yesterday, they did not go to school on time. (Because)\nBecause ___________. (chỉ điền phần còn thiếu)",
     "answer": "it rained heavily yesterday, they did not go to school on time.",
     "explanation": "Đáp án: Because it rained heavily yesterday, they did not go to school on time."},
    {"type": "fill", "topic": "Writing",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "45. Eating too much sugary food is not good for your health. (should)\nYou ___________. (chỉ điền phần còn thiếu)",
     "answer": "should not eat too much sugary food.",
     "explanation": "Đáp án: You should not eat too much sugary food."},
]

# =====================================================================
# ĐỀ SỐ 3
# =====================================================================
_DE_3 = [
    # LISTENING (câu 1–8): bỏ qua, không có audio.
    {"type": "choice", "topic": "Pronunciation",
     "section_start": "LANGUAGE FOCUS",
     "section_instruction": "Exercise 2: Choose the word whose underlined part is pronounced differently from the others’.",
     "passage_text": None,
     "q": "9. A. hu(g)e B. (g)eneral C. (g)roup",
     "options": ["A. huge", "B. general", "C. group"],
     "answer": "C. group",
     "explanation": "group /ɡ/; huge, general /dʒ/."},
    {"type": "choice", "topic": "Pronunciation",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "10. A. (s)cience B. (s)ure C. (S)panish",
     "options": ["A. science", "B. sure", "C. Spanish"],
     "answer": "B. sure",
     "explanation": "sure /ʃ/; science, Spanish /s/."},
    {"type": "choice", "topic": "Pronunciation",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "11. A. v(o)luntary B. c(o)nclusion C. c(o)mpare",
     "options": ["A. voluntary", "B. conclusion", "C. compare"],
     "answer": "A. voluntary",
     "explanation": "voluntary /ɒ/; conclusion, compare /ə/."},
    {"type": "choice", "topic": "Pronunciation",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "12. A. (ch)arity B. mu(ch) C. ma(ch)ine",
     "options": ["A. charity", "B. much", "C. machine"],
     "answer": "C. machine",
     "explanation": "machine /ʃ/; charity, much /tʃ/."},
    {"type": "choice", "topic": "Pronunciation",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "13. A. inf(or)mation B. f(or)get C. b(or)n",
     "options": ["A. information", "B. forget", "C. born"],
     "answer": "C. born",
     "explanation": "born /ɔː/; information, forget /ə/."},
    {"type": "choice", "topic": "Pronunciation",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "14. A. wat(ch) B. (ch)apter C. (ch)emical",
     "options": ["A. watch", "B. chapter", "C. chemical"],
     "answer": "C. chemical",
     "explanation": "chemical /k/; watch, chapter /tʃ/."},
    {"type": "choice", "topic": "Vocabulary",
     "section_start": None,
     "section_instruction": "Exercise 3: Choose the best option to complete each sentence. Circle A, B, or C.",
     "passage_text": None,
     "q": "15. Phan Boi Chau high school is for __________ students in the province.",
     "options": ["A. secondary", "B. present", "C. gifted"],
     "answer": "C. gifted",
     "explanation": "gifted students: học sinh năng khiếu."},
    {"type": "choice", "topic": "Vocabulary",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "16. A: How much yogurt do you need to buy? - B: _________.",
     "options": ["A. two tablespoons", "B. four cartons", "C. five bars"],
     "answer": "B. four cartons",
     "explanation": "carton: hộp (sữa chua)."},
    {"type": "choice", "topic": "Vocabulary",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "17. A: What would you like for the __________? B: I’d like the roasted fish, spring rolls, stir-fried vegetables and a bowl of canh chua, please!",
     "options": ["A. starter", "B. main course", "C. dessert"],
     "answer": "B. main course",
     "explanation": "main course: món chính."},
    {"type": "choice", "topic": "Vocabulary",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "18. Mona Lisa is a famous masterpiece, which was _______ by Leonardo da Vinci.",
     "options": ["A. painted", "B. composed", "C. directed"],
     "answer": "A. painted",
     "explanation": "painted: được vẽ."},
    {"type": "choice", "topic": "Vocabulary",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "19. I cannot watch _________ movies. They’re so scaring!",
     "options": ["A. action", "B. animated", "C. horror"],
     "answer": "C. horror",
     "explanation": "horror movies: phim kinh dị."},
    {"type": "choice", "topic": "Vocabulary",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "20. The eight-year-old Charlie Chaplin became a professional entertainer as a ________.",
     "options": ["A. actor", "B. dancer", "C. author"],
     "answer": "B. dancer",
     "explanation": "Sau “a” là danh từ bắt đầu bằng phụ âm → dancer."},
    {"type": "choice", "topic": "Grammar",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "21. A: ________ are we visiting Quoc Hoc Hue? - B: Next weekend.",
     "options": ["A. What", "B. When", "C. Where"],
     "answer": "B. When",
     "explanation": "Trả lời về thời gian → When."},
    {"type": "choice", "topic": "Grammar",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "22. Have you received any special gift ______ Christmas?",
     "options": ["A. at", "B. in", "C. on"],
     "answer": "A. at",
     "explanation": "at Christmas."},
    {"type": "choice", "topic": "Grammar",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "23. When you visit my school, you can see many modern facilities _______ the classrooms.",
     "options": ["A. at", "B. in", "C. on"],
     "answer": "B. in",
     "explanation": "in the classrooms."},
    {"type": "choice", "topic": "Grammar",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "24. ______ she wants to stay in shape, she tries to eat a healthier diet and do more exercise.",
     "options": ["A. Because of", "B. Although", "C. As"],
     "answer": "C. As",
     "explanation": "As + S + V: bởi vì."},
    {"type": "choice", "topic": "Grammar",
     "section_start": None,
     "section_instruction": "Exercise 4: Find a mistake (A, B, C or D) in each of the following sentences.",
     "passage_text": None,
     "q": "25. Breakfast is the most important meal in a day but you should eat many nutritious foods.",
     "options": ["A. most", "B. in", "C. but", "D. eat"],
     "answer": "C. but",
     "explanation": "but → so."},
    {"type": "choice", "topic": "Grammar",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "26. I would like to making chicken and mushroom soup tonight. Do you want to come over for dinner?",
     "options": ["A. making", "B. tonight", "C. to come", "D. dinner"],
     "answer": "A. making",
     "explanation": "would like to + V: making → make."},
    {"type": "choice", "topic": "Grammar",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "27. I usually go jogging in the early morning but today I stay at home because of the cold weather.",
     "options": ["A. usually", "B. in", "C. stay", "D. because of"],
     "answer": "C. stay",
     "explanation": "stay → am staying (hiện tại tiếp diễn, “today”)."},
    {"type": "choice", "topic": "Grammar",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "28. Do we have some potatoes left in the kitchen? I’d like to make some French fries.",
     "options": ["A. some", "B. left", "C. in", "D. to make"],
     "answer": "A. some",
     "explanation": "Câu hỏi → some → any."},
    {"type": "choice", "topic": "Reading",
     "section_start": "READING",
     "section_instruction": "Exercise 5: Read the passage. a. Circle the best answer A, B, or C to each of the questions.",
     "passage_text": "A school meal or school lunch is a meal provided to students and sometimes teachers at a school, typically in the middle or beginning of the school day. Countries around the world offer various kinds of school meal programs. Because it is important for children to eat nutritious and healthy food, school lunches around the world become one essential topic to discuss.\nJapan\nThis country is a world-wide known place of healthy eating. According to the teacher of English in one of the Japanese districts, students in Japan usually eat a bowl of rice, some fish, a salad made from pickles, some sort of soup and tofu added with vegetables and fruits. Japanese students are also given a bottle of milk for every school lunch. This variety of products is traditional for the Japanese people and represents quite a healthy and nutritious range of foods.\nThe United States\nThe typical school lunch in the USA is burger and chips, which is not as nutritious as expected. It leads to such health problems as obesity and overweight in the later years of life. However, recently, the American government has passed an act according to which school lunches should comprise of more nutritious and healthy foods. Hopefully, such measures will help to improve the quality of school lunches in the US.\nIndia\nSchools in India do not provide school lunches. Therefore, children in India typically eat lunch at home. There is also a service of providing fresh meals and delivering them to school. The containers from school lunches are then picked up by the servicemen. A typical school lunch in India comprises of flat bread known as “roti” and a meat or vegetable curry. Such lunch can be considered a nutritious option being beneficial for the health of children.\nSouth Korea\nPeople in this country care much about school lunch. The country’s government has actually banned the fast food advertisements because they might not be good for children and make them eat unhealthy foods. The typical school lunch in South Korea consists of “kimchi”, tofu, soybean sprouts and rice. Such lunch is absolutely healthy for children and sometimes look alike Japanese school lunches. South Koreans are known for taking much care about health and nutrition. So their school lunches definitely stand out compared to other countries.",
     "q": "29. What is the passage mainly about?",
     "options": ["A. Students in different countries", "B. Meals in different countries", "C. School lunches in many countries"],
     "answer": "C. School lunches in many countries",
     "explanation": "Bài nói về bữa trưa ở trường tại nhiều nước."},
    {"type": "choice", "topic": "Reading",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "30. When is school lunch typically served?",
     "options": ["A. in the beginning of the school day", "B. in the middle of the school day", "C. both A&B"],
     "answer": "C. both A&B",
     "explanation": "“…typically in the middle or beginning of the school day.”"},
    {"type": "choice", "topic": "Reading",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "31. Why do people all around the world dicuss about school lunches?",
     "options": ["A. Because eating healthy food is very essential for children", "B. Because both teachers and students need to eat at school", "C. Because the food in some schools are good and healthy"],
     "answer": "A. Because eating healthy food is very essential for children",
     "explanation": "“Because it is important for children to eat nutritious and healthy food…”"},
    {"type": "choice", "topic": "Reading",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "32. “Roti” is a food in _______ school lunches.",
     "options": ["A. American", "B. Indian", "C. Japanese"],
     "answer": "B. Indian",
     "explanation": "“A typical school lunch in India comprises of flat bread known as “roti”…”"},
    {"type": "choice", "topic": "Reading",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "33. According to the passage, which country has unhealthy school lunches?",
     "options": ["A. India", "B. The United States", "C. South Korea"],
     "answer": "B. The United States",
     "explanation": "“The typical school lunch in the USA is burger and chips, which is not as nutritious as expected.”"},
    {"type": "choice", "topic": "Reading",
     "section_start": None,
     "section_instruction": "b. Decide the statements below are True (T) or False (F).",
     "passage_text": None,
     "q": "34. Japanese students usually eat seafood, salad and vegetable soup with rice and fruits.",
     "options": ["A. True", "B. False"],
     "answer": "A. True",
     "explanation": "Theo đoạn Japan: cơm, cá, salad, súp, đậu phụ với rau và hoa quả."},
    {"type": "choice", "topic": "Reading",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "35. What students in England often have for their school lunches are burgers and chips.",
     "options": ["A. True", "B. False"],
     "answer": "B. False",
     "explanation": "Burger và chips là bữa trưa ở Mỹ (USA), không phải England."},
    {"type": "choice", "topic": "Reading",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "36. Eating too much fast food at lunch can lead to obesity among American children.",
     "options": ["A. True", "B. False"],
     "answer": "A. True",
     "explanation": "“It leads to such health problems as obesity and overweight…”"},
    {"type": "choice", "topic": "Reading",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "37. Many Indian children eat lunch at home, or have their lunches delivered to school by the servicemen.",
     "options": ["A. True", "B. False"],
     "answer": "A. True",
     "explanation": "“…children in India typically eat lunch at home. There is also a service of providing fresh meals and delivering them to school.”"},
    {"type": "choice", "topic": "Reading",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "38. Korean students rarely eat kimchi, tofu, soybean sprouts and rice for lunch.",
     "options": ["A. True", "B. False"],
     "answer": "B. False",
     "explanation": "“The typical school lunch in South Korea consists of “kimchi”, tofu, soybean sprouts and rice.”"},
    {"type": "fill", "topic": "Writing",
     "section_start": "WRITING",
     "section_instruction": "Exercise 6: Complete the second sentence, using the words in brackets.",
     "passage_text": None,
     "q": "39. Her favourite movies are not like mine. (from)\nHer ___________. (chỉ điền phần còn thiếu)",
     "answer": "favourite movies are different from mine.",
     "explanation": "Đáp án: Her favourite movies are different from mine."},
    {"type": "fill", "topic": "Writing",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "40. Minh is a better singer than Huyen. (as)\nHuyen can’t ___________. (chỉ điền phần còn thiếu)",
     "answer": "sing as well as Minh.",
     "explanation": "Đáp án: Huyen can’t sing as well as Minh."},
    {"type": "fill", "topic": "Writing",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "41. The music festival this year is not very good. Last year’s was better. (as)\nThe music festival this year ___________ last year’s. (chỉ điền phần còn thiếu)",
     "answer": "is not as good as",
     "explanation": "Đáp án: The music festival this year is not as good as last year’s."},
    {"type": "fill", "topic": "Writing",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "42. No other art museum in the world is as large as The Louvre in Paris. (the)\nThe Louvre in Paris ___________. (chỉ điền phần còn thiếu)",
     "answer": "is the largest art museum in the world.",
     "explanation": "Đáp án: The Louvre in Paris is the largest art museum in the world."},
    {"type": "fill", "topic": "Writing",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "43. You shouldn’t stay up too late. (good for)\nStaying ___________. (chỉ điền phần còn thiếu)",
     "answer": "up too late is not good for your health.",
     "explanation": "Đáp án: Staying up too late is not good for your health."},
]

# =====================================================================
# ĐỀ SỐ 4
# =====================================================================
_DE_4 = [
    # I. LISTENING (câu 1–5): bỏ qua, không có audio.
    {"type": "choice", "topic": "Pronunciation",
     "section_start": "II. PRONUNCIATION",
     "section_instruction": "II. Choose the word whose underlined part is pronounced differently.",
     "passage_text": None,
     "q": "6. A. (u)mbrella B. foc(u)s C. (u)nder D. m(u)shroom",
     "options": ["A. umbrella", "B. focus", "C. under", "D. mushroom"],
     "answer": "B. focus",
     "explanation": "focus /ə/; umbrella, under, mushroom /ʌ/."},
    {"type": "choice", "topic": "Pronunciation",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "7. A. cou(gh) B. enou(gh) C. throu(gh) D. lau(gh)",
     "options": ["A. cough", "B. enough", "C. through", "D. laugh"],
     "answer": "C. through",
     "explanation": "through – gh câm; cough, enough, laugh – gh đọc /f/."},
    {"type": "choice", "topic": "Pronunciation",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "8. A. start(ed) B. wash(ed) C. want(ed) D. visit(ed)",
     "options": ["A. started", "B. washed", "C. wanted", "D. visited"],
     "answer": "B. washed",
     "explanation": "washed /t/; started, wanted, visited /ɪd/."},
    {"type": "choice", "topic": "Pronunciation",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "9. A. (s)unburnt B. (s)culpture C. (s)ervice D. (s)ugar",
     "options": ["A. sunburnt", "B. sculpture", "C. service", "D. sugar"],
     "answer": "D. sugar",
     "explanation": "sugar /ʃ/; sunburnt, sculpture, service /s/."},
    {"type": "choice", "topic": "Pronunciation",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "10. A. u(s)ually B. compo(s)er C. lei(s)ure D. ver(s)ion",
     "options": ["A. usually", "B. composer", "C. leisure", "D. version"],
     "answer": "B. composer",
     "explanation": "composer /z/; usually, leisure, version /ʒ/."},
    {"type": "choice", "topic": "Grammar",
     "section_start": "III. VOCABULARY AND GRAMMAR",
     "section_instruction": "III. Choose the best answer A, B, C or D to complete these sentences.",
     "passage_text": None,
     "q": "11. People in the countryside have less stress, _______ they usually live longer.",
     "options": ["A. so", "B. and", "C. but", "D. or"],
     "answer": "A. so",
     "explanation": "so: vì vậy (kết quả)."},
    {"type": "choice", "topic": "Vocabulary",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "12. Vietnamese has some kinds of traditional _______ such as “Cheo” or “Cai luong”.",
     "options": ["A. music", "B. opera", "C. play", "D. instrument"],
     "answer": "A. music",
     "explanation": "traditional music: nhạc truyền thống."},
    {"type": "choice", "topic": "Vocabulary",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "13. Last Sunday, Tuan participated in _______ funds for street children.",
     "options": ["A. making", "B. taking", "C. raising", "D. gathering"],
     "answer": "C. raising",
     "explanation": "raise funds: gây quỹ."},
    {"type": "choice", "topic": "Communication",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "14. -“Would you like me to turn off your computer? - “ _______. I’ll do it myself.”",
     "options": ["A. No, thanks", "B. Yes, please", "C. Don’t do it", "D. Of course"],
     "answer": "A. No, thanks",
     "explanation": "Từ chối lịch sự: No, thanks. I’ll do it myself."},
    {"type": "choice", "topic": "Communication",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "15. Liz: I am afraid that I am putting on weight. - Tony: _______.",
     "options": ["A. Wash your hands more", "B. Eat less junk food", "C. Sleep more", "D. Sunbathe less"],
     "answer": "B. Eat less junk food",
     "explanation": "Lời khuyên cho người tăng cân: ăn ít đồ ăn vặt."},
    {"type": "choice", "topic": "Vocabulary",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "16. My father loved _______ horse-riding when he was young.",
     "options": ["A. doing", "B. going", "C. playing", "D. taking"],
     "answer": "B. going",
     "explanation": "go horse-riding."},
    {"type": "choice", "topic": "Grammar",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "17. He can teach me to cook some popular dishes. He has ________ free time today.",
     "options": ["A. any", "B. a lot of", "C. many", "D. some"],
     "answer": "B. a lot of",
     "explanation": "a lot of + danh từ không đếm được (free time)."},
    {"type": "choice", "topic": "Vocabulary",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "18. We can borrow books and magazines from the _________.",
     "options": ["A. school library", "B. school garden", "C. computer room", "D. school yard"],
     "answer": "A. school library",
     "explanation": "Mượn sách ở thư viện trường."},
    {"type": "choice", "topic": "Grammar",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "19. When I saw Hoa, she was holding a pocket English dictionary ________ her hands.",
     "options": ["A. at", "B. in", "C. on", "D. from"],
     "answer": "B. in",
     "explanation": "in her hands."},
    {"type": "choice", "topic": "Grammar",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "20. This painting is prettier, but it is not ______ the other one.",
     "options": ["A. as expensive than", "B. expensive than", "C. as expensive as", "D. much expensive as"],
     "answer": "C. as expensive as",
     "explanation": "So sánh bằng: not as + adj + as."},
    {"type": "choice", "topic": "Vocabulary",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "21. The lemonade isn't very sweet. I'll add some more ______ .",
     "options": ["A. salt", "B. pepper", "C. sugar", "D. lemon"],
     "answer": "C. sugar",
     "explanation": "Không ngọt → thêm đường."},
    {"type": "choice", "topic": "Vocabulary",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "22. Turn the TV off. The show is _____.",
     "options": ["A. exciting", "B. peaceful", "C. tiring", "D. boring"],
     "answer": "D. boring",
     "explanation": "boring: chán."},
    {"type": "fill", "topic": "Cloze",
     "section_start": "IV. READING (Cloze)",
     "section_instruction": "IV. Read and use the five words in the box to fill in the text. There is one extra word you don't need to use.",
     "passage_text": "Box: food – more – less – riding – calories – a lot\n\nWe need (23) __________ or energy to do the things we do every day such as walking, (24) __________ a bike and even sleeping! We get calories from the (25) __________ we eat. If we eat too many, we can get fat. If we don't eat enough we feel tired and weak.\nPeople should have between 1,600 and 2,500 calories a day to stay in shape. Sports and activities like riding a bike and running use (26) __________of calories. Sleeping and watching TV use (27) __________. Do you think you are eating more or less calories than you need?",
     "q": "23. We need (23) __________ or energy to do the things we do every day…",
     "answer": "calories",
     "explanation": "Sau “need” cần danh từ: calories."},
    {"type": "fill", "topic": "Cloze",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "24. …such as walking, (24) __________ a bike and even sleeping!",
     "answer": "riding",
     "explanation": "riding a bike (V-ing cùng dạng với walking, sleeping)."},
    {"type": "fill", "topic": "Cloze",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "25. We get calories from the (25) __________ we eat.",
     "answer": "food",
     "explanation": "the food we eat."},
    {"type": "fill", "topic": "Cloze",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "26. Sports and activities like riding a bike and running use (26) __________of calories.",
     "answer": "a lot",
     "explanation": "a lot of calories."},
    {"type": "fill", "topic": "Cloze",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "27. Sleeping and watching TV use (27) __________.",
     "answer": "less",
     "explanation": "use less: dùng ít hơn."},
    {"type": "fill", "topic": "Reading",
     "section_start": "V. READING",
     "section_instruction": "V. Read the passage then answer the questions. (Trả lời bằng câu đầy đủ như đáp án.)",
     "passage_text": "FAMILY VOLUNTEER DAY\nThe first reason why many families do volunteer work is that they feel satisfied and proud. The feeling of fulfillment comes from helping the community and other people. In addition, volunteering is a great way for families to have fun and feel closer. But many people say they don't have time to volunteer because they have to work and take care of their families. If that's the case, try rethinking some of your free time as a family. You can select just one or two projects a year and make them a family tradition. For instance, your family can make and donate gift baskets for the old homeless people on holidays. Your family can also spend only one Saturday morning a month collecting rubbish in your neighbourhood.",
     "q": "28. How do people often feel when they volunteer?",
     "answer": "They feel satisfied and proud.",
     "explanation": "“…they feel satisfied and proud.”"},
    {"type": "fill", "topic": "Reading",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "29. Why do some people lack time?",
     "answer": "Because they have to work and take care of their families.",
     "explanation": "“…because they have to work and take care of their families.”"},
    {"type": "fill", "topic": "Reading",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "30. Can you select just one or two projects a month and make them a family tradition?",
     "answer": "No, they can’t.",
     "explanation": "Bài đọc nói “a year”, không phải “a month”. Đáp án theo bảng đáp án: No, they can’t."},
    {"type": "fill", "topic": "Reading",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "31. How can your family help the old homeless people?",
     "answer": "They can make and donate gift baskets for the old homeless people on holidays.",
     "explanation": "“…your family can make and donate gift baskets for the old homeless people on holidays.”"},
    {"type": "fill", "topic": "Reading",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "32. What can your family do one Saturday morning a month?",
     "answer": "My family can collect rubbish in our neighbourhood.",
     "explanation": "“…spend only one Saturday morning a month collecting rubbish in your neighbourhood.”"},
    {"type": "fill", "topic": "Writing",
     "section_start": "VI. WRITING",
     "section_instruction": "VI. Use the words and phrases given to complete the informal letter of invitation. (Dear Peter, I’m glad to hear you are in Ha Noi again. … Let’s meet at 7.15 outside the theater. … Looking forward to seeing you there. Have a nice day! Cheers, Nam)",
     "passage_text": None,
     "q": "33. This time,/ how about/ watch/ water puppet show?/",
     "answer": "This time, how about watching a water puppet show?",
     "explanation": "How about + V-ing?"},
    {"type": "fill", "topic": "Writing",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "34. Saturday evening/ OK/ you?/",
     "answer": "Is Saturday evening OK for you?",
     "explanation": "Câu hỏi Yes/No với to be."},
    {"type": "fill", "topic": "Writing",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "35. show/ begin/ 7.30 p.m./ 57B Dinh Tien Hoang St./",
     "answer": "The show begins at 7.30 p.m. at 57B Dinh Tien Hoang St.",
     "explanation": "Hiện tại đơn cho lịch trình; at + giờ, at + địa chỉ."},
    {"type": "fill", "topic": "Writing",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "36. I/ hope/ we/ have/ happy time/ together./",
     "answer": "I hope we will have a happy time together.",
     "explanation": "S + hope + S + will + V."},
    {"type": "choice", "topic": "Grammar",
     "section_start": "VII. ERROR IDENTIFICATION",
     "section_instruction": "VII. Find a mistake (A, B, C, or D) in each of the following sentences and correct it.",
     "passage_text": None,
     "q": "37. Although this motorbike is more expensive as that one, many people prefer to buy it.",
     "options": ["A. Although", "B. motorbike", "C. as", "D. prefer"],
     "answer": "C. as",
     "explanation": "more expensive than: as → than."},
    {"type": "choice", "topic": "Grammar",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "38. Mai asked me: \"How are you going to school every day?\"",
     "options": ["A. asked", "B. are you going", "C. to", "D. every"],
     "answer": "B. are you going",
     "explanation": "every day → hiện tại đơn: are you going → do you go."},
    {"type": "choice", "topic": "Grammar",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "39. The English summer course will start at June 2nd and finish in August.",
     "options": ["A. The", "B. will", "C. at", "D. in"],
     "answer": "C. at",
     "explanation": "on + ngày tháng: at → on."},
    {"type": "choice", "topic": "Grammar",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "40. There was a lot of people trying to enter the stadium to see the football match.",
     "options": ["A. was", "B. people", "C. to enter", "D. the"],
     "answer": "A. was",
     "explanation": "a lot of people (số nhiều): was → were."},
]

# =====================================================================
# ĐỀ SỐ 5
# =====================================================================
_DE_5 = [
    # I. LISTENING (câu 1–5): bỏ qua, không có audio.
    {"type": "choice", "topic": "Pronunciation",
     "section_start": "II. PRONUNCIATION",
     "section_instruction": "II. Find the word which has a different sound in the part underlined.",
     "passage_text": None,
     "q": "6. A. h(e)lp B. b(e)nefit C. (e)lderly D. gard(e)n",
     "options": ["A. help", "B. benefit", "C. elderly", "D. garden"],
     "answer": "D. garden",
     "explanation": "garden /ˈɡɑːdn/ – e câm; help, benefit, elderly /e/."},
    {"type": "choice", "topic": "Pronunciation",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "7. A. kit(ch)en B. (ch)arity C. ma(ch)ine D. sandwi(ch)",
     "options": ["A. kitchen", "B. charity", "C. machine", "D. sandwich"],
     "answer": "C. machine",
     "explanation": "machine /ʃ/; kitchen, charity, sandwich /tʃ/."},
    {"type": "choice", "topic": "Pronunciation",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "8. A. c(o)ntrol B. b(o)ttle C. v(o)lunteer D. c(o)ncentrate",
     "options": ["A. control", "B. bottle", "C. volunteer", "D. concentrate"],
     "answer": "A. control",
     "explanation": "control /ə/; bottle, volunteer, concentrate /ɒ/."},
    {"type": "choice", "topic": "Pronunciation",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "9. A. finish(ed) B. report(ed) C. land(ed) D. succeed(ed)",
     "options": ["A. finished", "B. reported", "C. landed", "D. succeeded"],
     "answer": "A. finished",
     "explanation": "finished /t/; reported, landed, succeeded /ɪd/."},
    {"type": "choice", "topic": "Grammar",
     "section_start": "III. VOCABULARY AND GRAMMAR",
     "section_instruction": "III. Choose the best answer A, B, C or D to complete these sentences.",
     "passage_text": None,
     "q": "10. He ate a lot of fried food, so he _________ fat quickly.",
     "options": ["A. got", "B. get", "C. gets", "D. will get"],
     "answer": "A. got",
     "explanation": "Quá khứ đơn (ate … so he got)."},
    {"type": "choice", "topic": "Grammar",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "11. _________ you like to go to the movies with me? - Yes, I’d love to.",
     "options": ["A. Will", "B. Would", "C. Are", "D. Could"],
     "answer": "B. Would",
     "explanation": "Would you like to V?"},
    {"type": "choice", "topic": "Grammar",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "12. My sister is very good _________ Literature, so she always gets good marks.",
     "options": ["A. in", "B. at", "C. of", "D. on"],
     "answer": "B. at",
     "explanation": "be good at."},
    {"type": "choice", "topic": "Vocabulary",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "13. My sister likes beef. It’s her favourite _________.",
     "options": ["A. meat", "B. drink", "C. vegetable", "D. fruit"],
     "answer": "A. meat",
     "explanation": "beef là một loại thịt (meat)."},
    {"type": "choice", "topic": "Vocabulary",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "14. Viet Duc High School in Ha Noi is one of the oldest schools in Viet Nam. They _____ it in 1897.",
     "options": ["A. built", "B. got", "C. made", "D. did"],
     "answer": "A. built",
     "explanation": "built: đã xây."},
    {"type": "choice", "topic": "Grammar",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "15. I want to pass the test, _________ I’m studying hard.",
     "options": ["A. but", "B. because", "C. so", "D. although"],
     "answer": "C. so",
     "explanation": "so: vì vậy."},
    {"type": "choice", "topic": "Vocabulary",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "16. The person who directs the performance of an orchestra is the _________.",
     "options": ["A. conductor", "B. director", "C. composer", "D. musician"],
     "answer": "A. conductor",
     "explanation": "conductor: nhạc trưởng."},
    {"type": "choice", "topic": "Grammar",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "17. We have _________ rice and fish for lunch.",
     "options": ["A. some", "B. any", "C. a", "D. an"],
     "answer": "A. some",
     "explanation": "Câu khẳng định, danh từ không đếm được → some."},
    {"type": "fill", "topic": "Word form",
     "section_start": "IV. WORD FORM",
     "section_instruction": "IV. Complete each sentence below by filling in each blank with the correct form of the word provided.",
     "passage_text": None,
     "q": "18. My dad enjoys_______stamps, and he has a big stamp collection. (COLLECT)",
     "answer": "collecting",
     "explanation": "enjoy + V-ing."},
    {"type": "fill", "topic": "Word form",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "19. Having a pet helps children take on more_______. (RESPONSIBLE)",
     "answer": "responsibility",
     "explanation": "Sau “more” cần danh từ: responsibility."},
    {"type": "fill", "topic": "Word form",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "20. _______vegetables are very good for your health. (COLOUR)",
     "answer": "Coloured",
     "explanation": "Trước danh từ cần tính từ: coloured."},
    {"type": "fill", "topic": "Word form",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "21. Did you read books to the _______in the nursing home last Sunday? (ELDER)",
     "answer": "elderly",
     "explanation": "the elderly: người cao tuổi."},
    {"type": "fill", "topic": "Word form",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "22. At this school fair, you can exchange_______paper for notebooks. (USE)",
     "answer": "used",
     "explanation": "used paper: giấy đã qua sử dụng."},
    {"type": "choice", "topic": "Grammar",
     "section_start": "V. ERROR IDENTIFICATION",
     "section_instruction": "V. Find the mistake and correct it.",
     "passage_text": None,
     "q": "23. There are (A) any oranges (B) on the (C) table in (D) the kitchen. We need to buy some.",
     "options": ["A. are (A)", "B. oranges (B)", "C. the (C)", "D. in (D)"],
     "answer": "A. are (A)",
     "explanation": "are → aren’t (any dùng trong câu phủ định)."},
    {"type": "choice", "topic": "Grammar",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "24. How much (A) sandwiches do (B) you want to buy (C)? – Just (D) two.",
     "options": ["A. How much (A)", "B. do (B)", "C. buy (C)", "D. Just (D)"],
     "answer": "A. How much (A)",
     "explanation": "sandwiches đếm được → How much → How many."},
    {"type": "choice", "topic": "Reading",
     "section_start": "VI. READING",
     "section_instruction": "VI. Read the passage, then choose the best answer A, B, C or D.",
     "passage_text": "English is my mother tongue. Besides, I can speak French and Spanish. I studied the two languages when I was at high school. Now, I am still learning Spanish at the University. As for me, mastering a foreign language is not easy. After studying a language, practice is very necessary and useful. Travelling to the country where the target language is spoken is very helpful, but if you cannot speak the language well enough you will certainly have troubles. I also frequently go to the movies, watch television, listen to the radio in the language I am trying to learn. Reading is another good way to learn. Books are good, but I personally think newspapers and magazines are better. However, getting some knowledge of the language is the most important thing. Grammar and vocabulary should be mastered first.",
     "q": "25. How many languages can the writer speak?",
     "options": ["A. 1", "B. 2", "C. 3", "D. 4"],
     "answer": "C. 3",
     "explanation": "English, French, Spanish."},
    {"type": "choice", "topic": "Reading",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "26. The writer has learnt Spanish _______.",
     "options": ["A. in Spain", "B. at high school", "C. in other countries", "D. at home"],
     "answer": "B. at high school",
     "explanation": "“I studied the two languages when I was at high school.”"},
    {"type": "choice", "topic": "Reading",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "27. Travelling may cause troubles if _______.",
     "options": ["A. you cannot speak the language well enough.", "B. you can speak the language well enough.", "C. you can speak the language bad enough.", "D. you can communicate in the target language."],
     "answer": "A. you cannot speak the language well enough.",
     "explanation": "“…if you cannot speak the language well enough you will certainly have troubles.”"},
    {"type": "choice", "topic": "Reading",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "28. Some useful ways to practise your target language are _______",
     "options": ["A. listening to the radio and watching TV in the language.", "B. reading books in the language.", "C. seeing films in the language.", "D. all are correct."],
     "answer": "D. all are correct.",
     "explanation": "Bài nêu cả xem phim, xem TV, nghe radio, đọc sách."},
    {"type": "choice", "topic": "Reading",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "29. According to the writer, what should be mastered first?",
     "options": ["A. Vocabulary", "B. Vocabulary and grammar", "C. Writing skill", "D. Reading skill"],
     "answer": "B. Vocabulary and grammar",
     "explanation": "“Grammar and vocabulary should be mastered first.”"},
    {"type": "fill", "topic": "Cloze",
     "section_start": "VII. READING (Cloze)",
     "section_instruction": "VII. Fill in each blank with one suitable from the box to complete the passage. There are some extra words.",
     "passage_text": "Box: on – eggs – my – dropped – ingredients – mixed – so – in\n\nEnglish is my mother tongue, you’ll love this story! Last month, my Mum bought me a recipe book. The recipe looked very easy, (30) _________ I decided to make pizza for dinner one evening.\nI bought the (31) _________ and then I started to make the bread for the pizza. I (32) _________ flour, salt and water in a bowl. I was listening to music (33) _________ the radio. It was very loud, so I didn’t hear my brother come into the kitchen. He shouted my name and scared me. I (34) _________ the bowl. The flour and water went all over the table, the floor and my trousers.",
     "q": "30. The recipe looked very easy, (30) _________ I decided to make pizza for dinner one evening.",
     "answer": "so",
     "explanation": "so: vì vậy."},
    {"type": "fill", "topic": "Cloze",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "31. I bought the (31) _________ and then I started to make the bread for the pizza.",
     "answer": "ingredients",
     "explanation": "the ingredients: nguyên liệu."},
    {"type": "fill", "topic": "Cloze",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "32. I (32) _________ flour, salt and water in a bowl.",
     "answer": "mixed",
     "explanation": "mixed: trộn (quá khứ đơn)."},
    {"type": "fill", "topic": "Cloze",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "33. I was listening to music (33) _________ the radio.",
     "answer": "on",
     "explanation": "on the radio."},
    {"type": "fill", "topic": "Cloze",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "34. He shouted my name and scared me. I (34) _________ the bowl.",
     "answer": "dropped",
     "explanation": "dropped: đánh rơi."},
    {"type": "fill", "topic": "Writing",
     "section_start": "VIII. WRITING",
     "section_instruction": "VIII. Rewrite the following sentences in a way that their original meanings do not change. (Viết lại cả câu như đáp án.)",
     "passage_text": None,
     "q": "35. What is the price of the bicycle?\n=> How much _______________?",
     "answer": "How much is the bicycle?",
     "explanation": "Đáp án: How much is the bicycle? (hoặc: How much does the bicycle cost?)"},
    {"type": "fill", "topic": "Writing",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "36. The Louvre in Paris is the largest art museum in the world.\n=> No other art museum in the world is as ___________.",
     "answer": "No other art museum in the world is as large as the Louvre in Paris.",
     "explanation": "So sánh nhất → No other … as + adj + as."},
    {"type": "fill", "topic": "Writing",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "37. This film is not like the others: It is educational and informative.\n=> This film is different ___________.",
     "answer": "This film is different from the others.",
     "explanation": "be not like = be different from."},
    {"type": "fill", "topic": "Writing",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "38. Collecting and trying recipes from foreign countries is one of Jane's interests.\nJane is ___________.",
     "answer": "Jane is interested in collecting and trying recipes from foreign countries.",
     "explanation": "be interested in + V-ing."},
    {"type": "fill", "topic": "Writing",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "39. Because of the heavy rain, they didn't go camping yesterday.\nBecause it ___________.",
     "answer": "Because it rained heavily, they didn't go camping yesterday.",
     "explanation": "Because of + N = Because + S + V."},
    {"type": "fill", "topic": "Writing",
     "section_start": None,
     "section_instruction": None,
     "passage_text": None,
     "q": "40. I much prefer country life to city life.\nI think living in the country is ___________.",
     "answer": "I think living in the country is better than living in the city.",
     "explanation": "prefer A to B = think A is better than B."},
]

EXAMS = {1: _DE_1, 2: _DE_2, 3: _DE_3, 4: _DE_4, 5: _DE_5}
