# -*- coding: utf-8 -*-
"""Đề Toán 7 giữa HK1 — nguồn Drive (chép nguyên văn, chương trình 2018 / sách CTST).

Nguồn text thô: tools/raw_lop79/de_toan_7_giua_hk1/*.txt
  - "Toan 7 Giua HK 1.pdf"  (fileId 1FnLK3pFViWvkX6O05ECih1s_6afkNnvZ): tập đề tham khảo giữa HK1
    Toán 7 của các trường Quận 3 TP.HCM (Á Châu, Bàn Cờ, Colette, Đoàn Thị Điểm, Hai Bà Trưng,
    Kiến Thiết, Lê Lợi, Lê Quý Đôn, Phan Sào Nam, Tây Úc, Thăng Long).
  - "7 - 2.pdf" (fileId 1uX4Q62df753uTcEzQ7AJAp8YGiNMLKi9): tập đề tham khảo giữa HK1 Toán 7
    TP. Thủ Đức (Xuân Trường, Trường Thạnh, Tăng Nhơn Phú B, Bình Chiểu, Nguyễn Văn Trỗi,
    Tam Bình, Nguyễn Thị Định, Linh Trung, Hoa Lư, Nguyễn Văn Bá, Hiệp Bình...).
  - "7 - 3.pdf" (fileId 1ViZdlK_y8XWp0rfY_XmRIus_PHVvGeyY): 16 đề giữa HK1 Toán 7 huyện Hóc Môn —
    text mất toàn bộ dấu gạch phân số / dấu trừ / ký hiệu tập hợp và KHÔNG có đáp án → không dùng.
  - "7 -4.pdf"  (fileId 1mk0cw3JY7TxdK9p_gvhdTDOpriCgGONj): 2 đề giữa HK1 Toán 7 THCS Chu Văn An
    2023-2024 (bản scan, OCR vỡ công thức) → không dùng.

Quy ước chép: công thức trong PDF bị tách thành số rời (tử/mẫu), chỉ giữ các câu mà cả đề lẫn
hướng dẫn chấm cho phép khôi phục chắc chắn; mọi câu dựa vào hình vẽ, hoặc có lựa chọn/biểu thức
không khôi phục được, đều BỎ QUA (liệt kê dưới đây). Thời lượng gốc ghi trong SOURCES.

Câu bị bỏ qua:
 Đề 1 (Lê Lợi): TN câu 2 (ký hiệu ℕ/ℤ/ℚ mất), câu 3 (phân số vỡ), câu 4 (trục số – hình);
   TL câu 1b (thứ tự phép tính không rõ), câu 2c (biểu thức vỡ), câu 5 (kích thước chỉ có trên hình).
 Đề 2 (Á Châu): TN câu 2 (phương án A vỡ), câu 3 (ký hiệu tập hợp mất), câu 7, 12 (hình);
   TL câu 1 (hình), câu 2b, 2c (biểu thức vỡ), câu 5 (chiều dài thùng xe chỉ có trên hình).
 Đề 3 (Hoa Lư): TN câu 2 (ký hiệu tập hợp mất), câu 3 (dấu trừ trong các lựa chọn A, C không khôi phục được), câu 7 (hình); TL câu 1c, 1d (biểu thức vỡ),
   câu 2c (đề và đáp án mâu thuẫn: 33/8 : 11/2 = 3/4 nhưng đáp án dùng 4/3).
 Đề 4 (Nguyễn Thị Định): TN câu 1, 2 (ký hiệu tập hợp mất), câu 3, 4 (phân số/dấu vỡ),
   câu 5, 10, 11, 12 (hình); TL câu 1b (không rõ 8/11 hay 11/8).
 Đề 5 (Nguyễn Văn Trỗi): TN câu 1 và câu 5 (đáp án trong file mâu thuẫn với nội dung câu hỏi),
   câu 3, 12 (hình), câu 8 (phân số vỡ); TL câu 1a, 1b (biểu thức vỡ), câu 3 (kích thước trên hình).
"""

DURATION = 90   # phút, theo đề gốc (đề 2 và đề 5 là 90 phút; đề 1, 3, 4 gốc 60 phút)

SOURCES = {
    1: "THCS Lê Lợi, Quận 3 – KT giữa HK1 2023-2024, đề A, 60 phút — 'Toan 7 Giua HK 1.pdf' (1FnLK3pFViWvkX6O05ECih1s_6afkNnvZ)",
    2: "TH, THCS và THPT Quốc tế Á Châu, TP.HCM – đề tham khảo giữa HK1 2024-2025, 90 phút — 'Toan 7 Giua HK 1.pdf' (1FnLK3pFViWvkX6O05ECih1s_6afkNnvZ)",
    3: "THCS Hoa Lư, TP. Thủ Đức – đề tham khảo giữa HK1 2024-2025 (SGK CTST), 60 phút — '7 - 2.pdf' (1uX4Q62df753uTcEzQ7AJAp8YGiNMLKi9)",
    4: "THCS Nguyễn Thị Định, TP. Thủ Đức – đề tham khảo giữa HK1 2024-2025 (SGK CTST), 60 phút — '7 - 2.pdf' (1uX4Q62df753uTcEzQ7AJAp8YGiNMLKi9)",
    5: "THCS Nguyễn Văn Trỗi, TP. Thủ Đức – đề tham khảo giữa HK1 2024-2025 (SGK CTST), 90 phút — '7 - 2.pdf' (1uX4Q62df753uTcEzQ7AJAp8YGiNMLKi9)",
}

_FILL_FRAC = "Nhập kết quả dạng phân số tối giản (ví dụ -3/4) hoặc số nguyên."
_FILL_NUM = "Nhập số (không ghi đơn vị, không dùng dấu chấm/phẩy ngăn cách hàng nghìn)."

# ───────────────────────────── ĐỀ 1 — THCS LÊ LỢI (Q3) 2023-2024 ─────────────────────────────
_DE_1 = [
    {"type": "choice", "topic": "Số hữu tỉ",
     "section_start": "I. PHẦN TRẮC NGHIỆM (2,0 ĐIỂM)",
     "section_instruction": "Mỗi câu sau đây có 4 lựa chọn, trong đó chỉ có một phương án đúng. Em hãy ghi vào bài làm phương án mà em cho là đúng.",
     "passage_text": None,
     "q": "Câu 1. Khẳng định nào dưới đây sai?",
     "options": ["A. Số 23 là một số tự nhiên", "B. Số −5 là một số nguyên âm",
                 "C. Số −15/23 là một số hữu tỉ", "D. Số 0 là một số hữu tỉ dương"],
     "answer": "D. Số 0 là một số hữu tỉ dương",
     "explanation": "Số 0 không là số hữu tỉ dương cũng không là số hữu tỉ âm."},
    {"type": "choice", "topic": "Hình hộp chữ nhật – hình lập phương",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Câu 5. Các mặt của hình lập phương đều là:",
     "options": ["A. Hình thoi", "B. Hình chữ nhật", "C. Hình tam giác", "D. Hình vuông"],
     "answer": "D. Hình vuông", "explanation": "Hình lập phương có 6 mặt đều là hình vuông."},
    {"type": "choice", "topic": "Hình hộp chữ nhật – hình lập phương",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Câu 6. Cho hình hộp chữ nhật ABCD.A’B’C’D’ có BC = 7 cm. Khẳng định nào sau đây đúng?",
     "options": ["A. A’B’ = 7 cm", "B. CD = 7 cm", "C. AD = 7 cm", "D. AB = 7 cm"],
     "answer": "C. AD = 7 cm",
     "explanation": "Trong hình hộp chữ nhật, AD và BC là hai cạnh đối của mặt đáy ABCD nên AD = BC = 7 cm."},
    {"type": "choice", "topic": "Hình lăng trụ đứng",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Câu 7. Cho hình lăng trụ đứng tam giác ABC.DEF. Hai mặt đáy của hình lăng trụ đứng tam giác là hai mặt nào?",
     "options": ["A. ABED và CBEF", "B. ABC và DEF", "C. ACFD và BCFE", "D. CADF và BADE"],
     "answer": "B. ABC và DEF", "explanation": "Hai mặt đáy là hai tam giác ABC và DEF."},
    {"type": "choice", "topic": "Hình lăng trụ đứng",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Câu 8. Cho hình lăng trụ đứng tứ giác ABCD.A’B’C’D’. Các mặt bên của hình lăng trụ là hình gì?",
     "options": ["A. Hình chữ nhật", "B. Hình bình hành", "C. Hình tam giác", "D. Hình thoi"],
     "answer": "A. Hình chữ nhật", "explanation": "Các mặt bên của hình lăng trụ đứng đều là hình chữ nhật."},
    # ── TỰ LUẬN ──
    {"type": "fill", "topic": "Lũy thừa của số hữu tỉ",
     "section_start": "II. PHẦN TỰ LUẬN (8,0 ĐIỂM)",
     "section_instruction": "Câu 1 (2,5 điểm). Thực hiện phép tính (bằng cách hợp lí nếu có thể).",
     "passage_text": None,
     "q": "Câu 1a. a) (−6/5)⁷ · (−6/5)⁸ · (−6/5)⁹. Viết kết quả dưới dạng lũy thừa (−6/5)ⁿ. Nhập số mũ n.",
     "answer": "24",
     "explanation": "(−6/5)⁷ · (−6/5)⁸ · (−6/5)⁹ = (−6/5)^(7+8+9) = (−6/5)²⁴."},
    {"type": "fill", "topic": "Số hữu tỉ",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Câu 1c. c) 3/4 · 2/9 − 3/4 · 11/9. " + _FILL_FRAC,
     "answer": "-3/4",
     "explanation": "= 3/4 · (2/9 − 11/9) = 3/4 · (−1) = −3/4."},
    {"type": "fill", "topic": "Lũy thừa của số hữu tỉ",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Câu 1d. d) (25⁸ · 81⁵) / (125⁶ · 9⁹). " + _FILL_FRAC,
     "answer": "9/25",
     "explanation": "= (5²)⁸ · (3⁴)⁵ / [(5³)⁶ · (3²)⁹] = 5¹⁶ · 3²⁰ / (5¹⁸ · 3¹⁸) = 3² / 5² = 9/25."},
    {"type": "fill", "topic": "Số hữu tỉ",
     "section_start": None,
     "section_instruction": "Câu 2 (2,0 điểm). Tìm số hữu tỉ x, biết:",
     "passage_text": None,
     "q": "Câu 2a. a) −3/5 · x = 12/25. Nhập x. " + _FILL_FRAC,
     "answer": "-4/5",
     "explanation": "x = 12/25 : (−3/5) = 12/25 · (−5/3) = −4/5."},
    {"type": "fill", "topic": "Số hữu tỉ",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Câu 2b. b) x + 1/9 = 5/3 : 3. Nhập x. " + _FILL_FRAC,
     "answer": "4/9",
     "explanation": "5/3 : 3 = 5/9; x = 5/9 − 1/9 = 4/9."},
    {"type": "fill", "topic": "Số hữu tỉ – toán thực tế",
     "section_start": None,
     "section_instruction": "Câu 3 (1,0 điểm). Một cửa hàng có 120 kg đường.",
     "passage_text": None,
     "q": "Câu 3a. Một cửa hàng có 120 kg đường. a) Buổi sáng cửa hàng đó bán được 275/8 kg. Hỏi cửa hàng còn lại bao nhiêu kg đường? " + _FILL_FRAC,
     "answer": "685/8",
     "explanation": "Số kg đường còn lại sau buổi sáng: 120 − 275/8 = 960/8 − 275/8 = 685/8 (kg)."},
    {"type": "fill", "topic": "Số hữu tỉ – toán thực tế",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Câu 3b. Một cửa hàng có 120 kg đường. Buổi sáng cửa hàng đó bán được 275/8 kg. b) Buổi chiều cửa hàng lại nhập thêm 121/2 kg. Hỏi số kg đường hiện có trong cửa hàng? " + _FILL_FRAC,
     "answer": "1169/8",
     "explanation": "685/8 + 121/2 = 685/8 + 484/8 = 1169/8 (kg)."},
    {"type": "fill", "topic": "Hình hộp chữ nhật – thể tích",
     "section_start": None,
     "section_instruction": "Câu 4 (1,0 điểm).",
     "passage_text": None,
     "q": "Câu 4a. Một bể cá dạng hình hộp chữ nhật làm bằng kính (không có nắp) có chiều dài 80 cm, chiều rộng 50 cm. Người ta đổ một lượng nước vào trong bể cao 35 cm. a) Tính thể tích nước trong bể cá đó (cm³). " + _FILL_NUM,
     "answer": "140000",
     "explanation": "Thể tích nước: 80 · 50 · 35 = 140000 (cm³)."},
    {"type": "fill", "topic": "Hình hộp chữ nhật – thể tích",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Câu 4b. Một bể cá dạng hình hộp chữ nhật làm bằng kính (không có nắp) có chiều dài 80 cm, chiều rộng 50 cm. Người ta đổ một lượng nước vào trong bể cao 35 cm. b) Người ta cho vào bể một hòn đá thì thấy mực nước trong bể cao thêm 7 cm. Tính thể tích của hòn đá (cm³). " + _FILL_NUM,
     "answer": "28000",
     "explanation": "Thể tích hòn đá bằng thể tích phần nước dâng lên: 80 · 50 · 7 = 28000 (cm³)."},
    {"type": "fill", "topic": "Toán thực tế – tiền điện",
     "section_start": None,
     "section_instruction": "Câu 6 (0,5 điểm). Định mức giá điện sinh hoạt năm 2023 như sau: Bậc 1: từ 0 – 50 kWh: 1 549 đồng/kWh; Bậc 2: từ 51 – 100 kWh: 1 600 đồng/kWh; Bậc 3: từ 101 – 200 kWh: 1 858 đồng/kWh; Bậc 4: từ 201 – 300 kWh: 2 340 đồng/kWh; Bậc 5: từ 301 – 400 kWh: 2 834 đồng/kWh; Bậc 6: từ 401 trở lên: 2 927 đồng/kWh.",
     "passage_text": None,
     "q": "Câu 6a. Định mức giá điện sinh hoạt năm 2023: bậc 1 (0 – 50 kWh) 1 549 đồng/kWh; bậc 2 (51 – 100 kWh) 1 600 đồng/kWh; bậc 3 (101 – 200 kWh) 1 858 đồng/kWh; bậc 4 (201 – 300 kWh) 2 340 đồng/kWh; bậc 5 (301 – 400 kWh) 2 834 đồng/kWh; bậc 6 (từ 401 trở lên) 2 927 đồng/kWh. Trong tháng 9/2023, nhà bạn Dung sử dụng hết 154 kWh điện. a) Tính số tiền điện nhà bạn Dung phải trả (đồng)? " + _FILL_NUM,
     "answer": "257782",
     "explanation": "50 · 1549 + 50 · 1600 + 54 · 1858 = 257782 (đồng)."},
    {"type": "fill", "topic": "Toán thực tế – tiền điện",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Câu 6b. (Giá điện như câu 6a.) Trong tháng 9/2023, nhà bạn Dung sử dụng hết 154 kWh điện. b) Tính số tiền điện nhà bạn Dung phải trả sau khi tính thuế 10% (đồng)? Nhập số thập phân dùng dấu phẩy (ví dụ 1234,5).",
     "answer": "283560,2",
     "explanation": "257782 · (100% + 10%) = 283560,2 (đồng)."},
]

# ───────────────────── ĐỀ 2 — TH, THCS VÀ THPT QUỐC TẾ Á CHÂU 2024-2025 ─────────────────────
_DE_2 = [
    {"type": "choice", "topic": "Số hữu tỉ",
     "section_start": "PHẦN I: TRẮC NGHIỆM (3,0 ĐIỂM)",
     "section_instruction": None, "passage_text": None,
     "q": "Câu 1: Trong các số −1/3; 0; 1,5; −(−1/2), các số hữu tỉ âm là:",
     "options": ["A. 1,5; 0", "B. −1/3", "C. −1/3; −(−1/2)", "D. −(−1/2)"],
     "answer": "B. −1/3",
     "explanation": "−(−1/2) = 1/2 > 0, nên chỉ có −1/3 là số hữu tỉ âm."},
    {"type": "choice", "topic": "Lũy thừa của số hữu tỉ",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Câu 4: Cho số hữu tỉ x. Chọn khẳng định đúng?",
     "options": ["A. xᵐ · xⁿ = xᵐ·ⁿ",
                 "B. xⁿ = x + x + x + … + x (n số hạng, n ∈ ℕ, n > 1)",
                 "C. xᵐ : xⁿ = xᵐ⁻ⁿ (x ≠ 0; m ≥ n)",
                 "D. (xᵐ)ⁿ = xᵐ⁺ⁿ"],
     "answer": "C. xᵐ : xⁿ = xᵐ⁻ⁿ (x ≠ 0; m ≥ n)",
     "explanation": "Thương hai lũy thừa cùng cơ số: xᵐ : xⁿ = xᵐ⁻ⁿ."},
    {"type": "choice", "topic": "Hình hộp chữ nhật – hình lập phương",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Câu 5: Phát biểu nào sau đây đúng về hình lập phương ABCD.MNPQ.",
     "options": ["A. Bốn đường chéo AP, BP, CM, DB.",
                 "B. Ba góc vuông ở đỉnh A: góc DAB, góc DAM, góc MAB.",
                 "C. AM = AB = AD = AC.",
                 "D. Bốn mặt bên là ABCD, MNPQ, AMNB, BNPC."],
     "answer": "B. Ba góc vuông ở đỉnh A: góc DAB, góc DAM, góc MAB.",
     "explanation": "Tại mỗi đỉnh của hình lập phương có ba góc vuông; AC là đường chéo mặt nên AC ≠ AB; ABCD, MNPQ là hai mặt đáy."},
    {"type": "choice", "topic": "Hình hộp chữ nhật – diện tích xung quanh",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Câu 6: Diện tích xung quanh của hình hộp chữ nhật có độ dài hai đáy là 6 cm; 8 cm và chiều cao 10 cm là:",
     "options": ["A. 6.8.10 (cm²)", "B. (6 + 8).10 (cm²)", "C. (6 + 8 + 10) (cm²)", "D. 2.(6 + 8).10 (cm²)"],
     "answer": "D. 2.(6 + 8).10 (cm²)",
     "explanation": "Sxq = (chu vi đáy) · chiều cao = 2.(6 + 8).10."},
    {"type": "choice", "topic": "Hình lăng trụ đứng",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Câu 8: Cho hình lăng trụ đứng tam giác ABC.DEF. Phát biểu nào sau đây sai?",
     "options": ["A. A, B, C, D, E, F gọi là các đỉnh.",
                 "B. Ba mặt ABED, BEFC, ACFD là các hình chữ nhật.",
                 "C. AB, BC, CF là các cạnh bên.",
                 "D. Mặt ABC và mặt DEF là hai mặt đáy."],
     "answer": "C. AB, BC, CF là các cạnh bên.",
     "explanation": "Các cạnh bên là AD, BE, CF; AB, BC là cạnh đáy."},
    {"type": "choice", "topic": "Hình lăng trụ đứng",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Câu 9: Cho hình lăng trụ đứng có chu vi đáy, diện tích đáy và chiều cao lần lượt là Cđáy, Sđáy, h. Chọn khẳng định đúng.",
     "options": ["A. Sxq = Cđáy . h", "B. V = Cđáy . Sđáy", "C. V = Cđáy . h", "D. V = Sxq . h"],
     "answer": "A. Sxq = Cđáy . h",
     "explanation": "Sxq = Cđáy · h; V = Sđáy · h."},
    {"type": "choice", "topic": "Góc – hai góc kề bù, đối đỉnh",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Câu 10: Cho các khẳng định sau: (I) Hai góc đối đỉnh thì bằng nhau. (II) Hai góc bù nhau là hai góc có tổng số đo bằng 90°. (III) Hai góc kề nhau là hai góc có một cạnh chung và không có điểm trong chung. (IV) Hai góc vừa kề nhau, vừa bù nhau gọi là hai góc kề bù. Số khẳng định đúng trong các khẳng định trên là?",
     "options": ["A. 2", "B. 4", "C. 1", "D. 3"],
     "answer": "D. 3",
     "explanation": "(II) sai vì hai góc bù nhau có tổng số đo 180°; (I), (III), (IV) đúng."},
    {"type": "choice", "topic": "Hình lăng trụ đứng",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Câu 11: Cho hình lăng trụ đứng tứ giác ABCD.EFGH có đáy là hình thang. Các mặt bên của hình lăng trụ đứng trên là.",
     "options": ["A. ABCD, EFGH", "B. ABFE, BCGF, CDHG, ADHE", "C. ADHE, ABCD, CDHG, EFGH", "D. ADHE, BCGF, CDHG, EFGH"],
     "answer": "B. ABFE, BCGF, CDHG, ADHE",
     "explanation": "ABCD và EFGH là hai mặt đáy; bốn mặt bên là ABFE, BCGF, CDHG, ADHE."},
    # ── TỰ LUẬN ──
    {"type": "fill", "topic": "Số hữu tỉ",
     "section_start": "PHẦN II: TỰ LUẬN (7,0 ĐIỂM)",
     "section_instruction": "Câu 2: (1,5 điểm) Thực hiện phép tính (tính hợp lí nếu có thể):",
     "passage_text": None,
     "q": "Câu 2a. a) −1,25 − 1/3 : 2/3. " + _FILL_FRAC,
     "answer": "-7/4",
     "explanation": "= −5/4 − 1/3 · 3/2 = −5/4 − 1/2 = −5/4 − 2/4 = −7/4."},
    {"type": "fill", "topic": "Số hữu tỉ",
     "section_start": None,
     "section_instruction": "Câu 3: (1,5 điểm) Tìm x, biết:",
     "passage_text": None,
     "q": "Câu 3a. a) 3/2 · x = 1 1/8 − 2 3/4 (hỗn số). Nhập x. " + _FILL_FRAC,
     "answer": "-13/12",
     "explanation": "3/2 · x = 9/8 − 11/4 = 9/8 − 22/8 = −13/8; x = −13/8 : 3/2 = −13/12."},
    {"type": "fill", "topic": "Số hữu tỉ",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Câu 3b. b) 11/12 − (2/5 + x) = 2/3. Nhập x. " + _FILL_FRAC,
     "answer": "-3/20",
     "explanation": "2/5 + x = 11/12 − 2/3 = 1/4; x = 1/4 − 2/5 = 5/20 − 8/20 = −3/20."},
    {"type": "fill", "topic": "Hình hộp chữ nhật – diện tích xung quanh",
     "section_start": None,
     "section_instruction": "Câu 4: (1,5 điểm) Bác Nam muốn làm một bể cá bằng kính có dạng hình hộp chữ nhật với kích thước lần lượt là chiều dài 12 dm, chiều rộng 5 dm, chiều cao 7 dm. Biết đáy bể cũng làm bằng kính.",
     "passage_text": None,
     "q": "Câu 4a-1. Bác Nam muốn làm một bể cá bằng kính có dạng hình hộp chữ nhật với kích thước lần lượt là chiều dài 12 dm, chiều rộng 5 dm, chiều cao 7 dm. Biết đáy bể cũng làm bằng kính. a) Tính diện tích xung quanh của bể cá (dm²). " + _FILL_NUM,
     "answer": "238",
     "explanation": "Sxq = 2.(12 + 5).7 = 238 (dm²)."},
    {"type": "fill", "topic": "Hình hộp chữ nhật – thể tích",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Câu 4a-2. (Bể cá hình hộp chữ nhật dài 12 dm, rộng 5 dm, cao 7 dm.) a) Tính thể tích của bể cá (dm³). " + _FILL_NUM,
     "answer": "420",
     "explanation": "V = 12.5.7 = 420 (dm³)."},
    {"type": "fill", "topic": "Hình hộp chữ nhật – toán thực tế",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Câu 4b. (Bể cá hình hộp chữ nhật dài 12 dm, rộng 5 dm, cao 7 dm; đáy bể cũng làm bằng kính.) b) Tính chi phí để bác Nam làm bể cá đó (đồng). Biết giá 1 m² kính là 150 000 đồng. " + _FILL_NUM,
     "answer": "447000",
     "explanation": "Diện tích kính: 238 + 12.5 = 298 (dm²) = 2,98 m²; chi phí: 2,98 · 150000 = 447000 (đồng)."},
    {"type": "fill", "topic": "Toán thực tế – phần trăm",
     "section_start": None,
     "section_instruction": "Câu 6: (1,0 điểm)",
     "passage_text": None,
     "q": "Câu 6. Một cửa hàng điện tử nhập về lô hàng gồm 50 chiếc điện thoại, giá tiền của một chiếc điện thoại khi nhập về là 10 000 000 đồng. Sau khi đã bán được 40 chiếc điện thoại với giá bằng 120% giá vốn mua ban đầu thì lượng khách hàng mua sản phẩm giảm xuống nên cửa hàng đã thực hiện chương trình giảm giá đặc biệt dành cho 10 chiếc điện thoại cuối cùng để thu hút khách hàng. Hỏi sau khi bán hết lô hàng trên, cửa hàng kỳ vọng lãi được 70 000 000 đồng thì phải giảm giá bao nhiêu phần trăm cho 10 chiếc điện thoại cuối cùng so với giá bán 40 chiếc điện thoại trước đó. Nhập số phần trăm (chỉ nhập số).",
     "answer": "25",
     "explanation": "Vốn: 500 000 000; bán 40 chiếc giá 12 000 000: 480 000 000; cần thu thêm 500 000 000 + 70 000 000 − 480 000 000 = 90 000 000 → mỗi chiếc 9 000 000 = 75% của 12 000 000 → giảm 25%."},
]

# ───────────────────────── ĐỀ 3 — THCS HOA LƯ (TP. THỦ ĐỨC) 2024-2025 ─────────────────────────
_DE_3 = [
    {"type": "choice", "topic": "Số hữu tỉ",
     "section_start": "A. TRẮC NGHIỆM (2 điểm)",
     "section_instruction": None, "passage_text": None,
     "q": "Câu 1. Trong các số −3/5; −0,3; −1/−3; 0; −5/2; 0,15 có bao nhiêu số hữu tỉ âm?",
     "options": ["A. 1.", "B. 2.", "C. 3.", "D. 4."],
     "answer": "C. 3.",
     "explanation": "−3/5; −0,3; −5/2 là số hữu tỉ âm (−1/−3 = 1/3 > 0)."},
    {"type": "choice", "topic": "Hình hộp chữ nhật – hình lập phương",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Câu 4. Hình lập phương ABCD.A’B’C’D’ có một đường chéo tên là:",
     "options": ["A. A’C’.", "B. BA’.", "C. AC’.", "D. BD."],
     "answer": "C. AC’.",
     "explanation": "Đường chéo của hình lập phương nối hai đỉnh không cùng thuộc một mặt: AC’, BD’, CA’, DB’."},
    {"type": "choice", "topic": "Hình lăng trụ đứng",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Câu 5. Cho hình lăng trụ đứng tam giác như hình bên (các mặt ABDE, AEFC, ABC, BCFD). Mặt đáy của lăng trụ đứng là:",
     "options": ["A. ABDE.", "B. AEFC.", "C. ABC.", "D. BCFD."],
     "answer": "C. ABC.",
     "explanation": "Mặt đáy của lăng trụ đứng tam giác là mặt tam giác ABC."},
    {"type": "choice", "topic": "Hình hộp chữ nhật – hình lập phương",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Câu 6. Hình nào có tất cả các mặt đều là hình vuông:",
     "options": ["A. Hình lập phương.", "B. Hình hộp chữ nhật.", "C. Hình lăng trụ đứng tam giác.", "D. Hình lăng trụ đứng tứ giác."],
     "answer": "A. Hình lập phương.", "explanation": "Hình lập phương có 6 mặt đều là hình vuông."},
    {"type": "choice", "topic": "Hình hộp chữ nhật – hình lập phương",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Câu 8. Khẳng định nào dưới đây là đúng?",
     "options": ["A. Hình hộp chữ nhật có 12 đỉnh, 8 cạnh và 4 đường chéo.",
                 "B. Hình hộp chữ nhật có 8 đỉnh, 12 cạnh và 6 đường chéo.",
                 "C. Hình hộp chữ nhật có 8 đỉnh, 12 cạnh và 4 đường chéo.",
                 "D. Hình hộp chữ nhật có 12 đỉnh, 8 cạnh và 6 đường chéo."],
     "answer": "C. Hình hộp chữ nhật có 8 đỉnh, 12 cạnh và 4 đường chéo.",
     "explanation": "Hình hộp chữ nhật có 8 đỉnh, 12 cạnh, 6 mặt và 4 đường chéo."},
    # ── TỰ LUẬN ──
    {"type": "fill", "topic": "Số hữu tỉ",
     "section_start": "B. TỰ LUẬN (8 điểm)",
     "section_instruction": "Bài 1. (3 đ) Thực hiện phép tính:",
     "passage_text": None,
     "q": "Bài 1a. a) 3/4 + (−7/12) − 2/3. " + _FILL_FRAC,
     "answer": "-1/2",
     "explanation": "= 9/12 − 7/12 − 8/12 = −6/12 = −1/2."},
    {"type": "fill", "topic": "Lũy thừa của số hữu tỉ",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Bài 1b. b) 1/2 − [(2/3)⁹ : (2/3)⁷] + 5/6. " + _FILL_FRAC,
     "answer": "8/9",
     "explanation": "= 1/2 − (2/3)² + 5/6 = 1/2 − 4/9 + 5/6 = (9 − 8 + 15)/18 = 16/18 = 8/9."},
    {"type": "fill", "topic": "Số hữu tỉ",
     "section_start": None,
     "section_instruction": "Bài 2. (2,25 đ) Tìm x, biết:",
     "passage_text": None,
     "q": "Bài 2a. a) x + 1 1/3 = 3/4 (1 1/3 là hỗn số). Nhập x. " + _FILL_FRAC,
     "answer": "-7/12",
     "explanation": "x = 3/4 − 4/3 = 9/12 − 16/12 = −7/12."},
    {"type": "fill", "topic": "Số hữu tỉ",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Bài 2b. b) 4/3 − 5/3 · x = −1/2. Nhập x. " + _FILL_FRAC,
     "answer": "11/10",
     "explanation": "5/3 · x = 4/3 − (−1/2) = 4/3 + 1/2 = 11/6; x = 11/6 : 5/3 = 11/10."},
    {"type": "fill", "topic": "Toán thực tế – phần trăm",
     "section_start": None,
     "section_instruction": "Bài 3. (1,25 điểm)",
     "passage_text": None,
     "q": "Bài 3. Cô Mai khởi nghiệp mua 200 cái áo với giá mua 1 cái áo là 140000 đồng. Cô đã bán 80 cái áo, mỗi cái áo so với giá mua lãi được 20%. Với 30 cái áo kế tiếp, cô bán giá 1 cái áo bằng với giá vốn. 90 áo còn lại, mỗi cái phải bán lỗ so với giá vốn 10%. Hỏi sau việc mua và bán 200 cái áo, cô Mai lãi hay lỗ bao nhiêu tiền? Nhập số tiền lãi (đồng); nếu lỗ nhập số âm. " + _FILL_NUM,
     "answer": "980000",
     "explanation": "Lãi 80 áo: 140000 · 20% · 80 = 2240000 (đồng). Lỗ 90 áo: 140000 · 10% · 90 = 1260000 (đồng). Vì 2240000 > 1260000 nên cô Mai lãi 2240000 − 1260000 = 980000 (đồng)."},
    {"type": "fill", "topic": "Hình hộp chữ nhật – thể tích",
     "section_start": None,
     "section_instruction": "Bài 4. (1,5 điểm) Một hồ bơi dạng hình hộp chữ nhật với các kích thước trong lòng hồ như sau: chiều dài 20 m, chiều rộng 8 m và sâu 2,5 m.",
     "passage_text": None,
     "q": "Bài 4a. Một hồ bơi dạng hình hộp chữ nhật với các kích thước trong lòng hồ như sau: chiều dài 20 m, chiều rộng 8 m và sâu 2,5 m. a) Tính thể tích của hồ bơi (m³)? " + _FILL_NUM,
     "answer": "400",
     "explanation": "V = 20 · 8 · 2,5 = 400 (m³)."},
    {"type": "fill", "topic": "Hình hộp chữ nhật – diện tích xung quanh",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Bài 4b. (Hồ bơi hình hộp chữ nhật dài 20 m, rộng 8 m, sâu 2,5 m.) b) Người ta cần lát gạch toàn bộ bề mặt bên trong lòng hồ. Hãy tính diện tích cần lát gạch (m²)? " + _FILL_NUM,
     "answer": "300",
     "explanation": "Diện tích cần lát = Sxq + Sđáy = (20 + 8) · 2 · 2,5 + 20 · 8 = 220 + 80 = 300 (m²)."},
    {"type": "fill", "topic": "Hình hộp chữ nhật – toán thực tế",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Bài 4c. (Hồ bơi hình hộp chữ nhật dài 20 m, rộng 8 m, sâu 2,5 m; diện tích cần lát gạch là toàn bộ bề mặt bên trong lòng hồ.) c) Người ta sử dụng các viên gạch hình vuông có cạnh 40 cm để lát toàn bộ bên trong lòng hồ. Biết rằng giá gạch là 40000 đồng/viên. Hãy tính số tiền mua gạch để lát toàn bộ lòng hồ bơi đó (đồng)? (biết rằng khi lát, diện tích các mạch vữa là không đáng kể) " + _FILL_NUM,
     "answer": "75000000",
     "explanation": "Số viên gạch: 300 : (0,4)² = 1875 viên; số tiền: 1875 · 40000 = 75000000 (đồng)."},
]

# ───────────────────── ĐỀ 4 — THCS NGUYỄN THỊ ĐỊNH (TP. THỦ ĐỨC) 2024-2025 ─────────────────────
_DE_4 = [
    {"type": "choice", "topic": "Lũy thừa của số hữu tỉ",
     "section_start": "A. TRẮC NGHIỆM (3,0 ĐIỂM)",
     "section_instruction": None, "passage_text": None,
     "q": "Câu 6. Chọn khẳng định đúng.",
     "options": ["A. (−2/3)² · (−2/3)⁴ = (−2/3)⁸", "B. (2,5)⁹ : (2,5)³ = (2,5)³",
                 "C. [(−1,15)²]³ = (−1,15)⁵", "D. (4/3) · (4/3)⁵ = (4/3)⁶"],
     "answer": "D. (4/3) · (4/3)⁵ = (4/3)⁶",
     "explanation": "xᵐ · xⁿ = xᵐ⁺ⁿ nên (4/3)¹ · (4/3)⁵ = (4/3)⁶. A phải là mũ 6, B mũ 6, C mũ 6."},
    {"type": "choice", "topic": "Hình hộp chữ nhật – hình lập phương",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Câu 7. Cho hình lập phương EFGH.MNPQ có cạnh EF = 5 cm. Tính GP",
     "options": ["A. GP = 10 cm", "B. GP = 5 cm", "C. GP = 15 cm", "D. GP = 20 cm"],
     "answer": "B. GP = 5 cm",
     "explanation": "Hình lập phương có các cạnh bằng nhau nên GP = EF = 5 cm."},
    {"type": "choice", "topic": "Hình hộp chữ nhật – hình lăng trụ đứng",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Câu 8. Khẳng định nào sai?",
     "options": ["A. Hình hộp chữ nhật có 12 cạnh bằng nhau.",
                 "B. Hình hộp chữ nhật là hình lăng trụ đứng tứ giác.",
                 "C. Hình lập phương có 6 mặt là hình vuông.",
                 "D. Hình lăng trụ đứng tam giác có 3 mặt bên là hình chữ nhật."],
     "answer": "A. Hình hộp chữ nhật có 12 cạnh bằng nhau.",
     "explanation": "Hình hộp chữ nhật có 12 cạnh nhưng không nhất thiết bằng nhau (chỉ hình lập phương mới có 12 cạnh bằng nhau)."},
    {"type": "choice", "topic": "Hình hộp chữ nhật – hình lập phương",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Câu 9. Mặt đáy của hình lập phương là:",
     "options": ["A. Hình thoi", "B. Tam giác đều", "C. Hình chữ nhật", "D. Hình vuông."],
     "answer": "D. Hình vuông.", "explanation": "Mọi mặt của hình lập phương đều là hình vuông."},
    # ── TỰ LUẬN ──
    {"type": "fill", "topic": "Số hữu tỉ",
     "section_start": "B. TỰ LUẬN (7 ĐIỂM)",
     "section_instruction": "Bài 1. (2,0 điểm) Thực hiện phép tính:",
     "passage_text": None,
     "q": "Bài 1a. a) 5/4 + (−3/7) · 15/8. " + _FILL_FRAC,
     "answer": "25/56",
     "explanation": "= 5/4 + (−45/56) = 70/56 − 45/56 = 25/56."},
    {"type": "fill", "topic": "Lũy thừa của số hữu tỉ",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Bài 1c. c) (2² · 25³) / (16 · 5⁷). " + _FILL_FRAC,
     "answer": "1/20",
     "explanation": "= 2² · 5⁶ / (2⁴ · 5⁷) = 1 / (2² · 5) = 1/20."},
    {"type": "fill", "topic": "Số hữu tỉ",
     "section_start": None,
     "section_instruction": "Bài 2. (2,0 điểm) Tìm x, biết:",
     "passage_text": None,
     "q": "Bài 2a. a) 5/2 + x = 1/3. Nhập x. " + _FILL_FRAC,
     "answer": "-13/6",
     "explanation": "x = 1/3 − 5/2 = 2/6 − 15/6 = −13/6."},
    {"type": "fill", "topic": "Số hữu tỉ",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Bài 2b. b) 2/3 · x − 1 2/5 = 0,6 (1 2/5 là hỗn số). Nhập x. " + _FILL_FRAC,
     "answer": "3",
     "explanation": "2/3 · x − 7/5 = 3/5 ⇒ 2/3 · x = 3/5 + 7/5 = 2 ⇒ x = 2 : 2/3 = 3."},
    {"type": "fill", "topic": "Hình lăng trụ đứng – thể tích",
     "section_start": None,
     "section_instruction": "Bài 3. (1,0 điểm)",
     "passage_text": None,
     "q": "Bài 3. Cho hình lăng trụ đứng ABC.A’B’C’ có tam giác ABC vuông tại A. Biết AB = 5 cm, AC = 8 cm, AA’ = 13 cm. Tính thể tích của lăng trụ (cm³). " + _FILL_NUM,
     "answer": "260",
     "explanation": "Sđáy = 5 · 8 : 2 = 20 (cm²); V = Sđáy · h = 20 · 13 = 260 (cm³)."},
    {"type": "fill", "topic": "Hình hộp chữ nhật – thể tích",
     "section_start": None,
     "section_instruction": "Bài 4. (1,0 điểm) Một bể bơi có chiều dài 12 m, chiều rộng 5 m và chiều cao 2,75 m.",
     "passage_text": None,
     "q": "Bài 4a. Một bể bơi có chiều dài 12 m, chiều rộng 5 m và chiều cao 2,75 m. a) Tính thể tích của hồ bơi (m³). " + _FILL_NUM,
     "answer": "165",
     "explanation": "V = 12 · 5 · 2,75 = 165 (m³)."},
    {"type": "fill", "topic": "Hình hộp chữ nhật – toán thực tế",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Bài 4b. (Bể bơi hình hộp chữ nhật dài 12 m, rộng 5 m, cao 2,75 m.) b) Bác An muốn lát đáy và xung quanh bể bơi bằng những viên gạch có diện tích 0,05 m² (diện tích mạch vữa lát không đáng kể). Tính chi phí bác An phải bỏ ra để lát đáy và xung quanh bể biết mỗi viên gạch có giá 17500 đồng? " + _FILL_NUM,
     "answer": "53725000",
     "explanation": "Sxq = 2 · (5 + 12) · 2,75 = 93,5 (m²); Sđáy = 5 · 12 = 60 (m²); diện tích lát: 153,5 m²; số gạch: 153,5 : 0,05 = 3070 viên; chi phí: 3070 · 17500 = 53725000 (đồng)."},
    {"type": "fill", "topic": "Toán thực tế – phần trăm",
     "section_start": None,
     "section_instruction": "Bài 5. (1,0 điểm) Một cửa hàng bán giày thể thao giảm giá 25% cho tất cả các sản phẩm. Bạn An mua một đôi giày với giá sau khi giảm là 500 000 đồng.",
     "passage_text": None,
     "q": "Bài 5a. Một cửa hàng bán giày thể thao giảm giá 25% cho tất cả các sản phẩm. Bạn An mua một đôi giày với giá sau khi giảm là 500 000 đồng. a) Tính giá niêm yết của đôi giày (đồng, làm tròn đến hàng ngàn). " + _FILL_NUM,
     "answer": "667000",
     "explanation": "Giá niêm yết: 500 000 : 75% ≈ 666 667 ≈ 667 000 (đồng) (theo hướng dẫn chấm)."},
    {"type": "fill", "topic": "Toán thực tế – phần trăm",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Bài 5b. (Cửa hàng giảm giá 25%; bạn An mua một đôi giày với giá sau khi giảm là 500 000 đồng.) b) Nếu cửa hàng giảm giá thêm 10% trên giá đã giảm thì bạn An phải trả bao nhiêu tiền (đồng)? (Kết quả làm tròn đến hàng ngàn) " + _FILL_NUM,
     "answer": "450000",
     "explanation": "Số tiền giảm thêm: 500 000 · 10% = 50 000; số tiền phải trả: 500 000 − 50 000 = 450 000 (đồng)."},
]

# ───────────────────── ĐỀ 5 — THCS NGUYỄN VĂN TRỖI (TP. THỦ ĐỨC) 2024-2025 ─────────────────────
_DE_5 = [
    {"type": "choice", "topic": "Số hữu tỉ",
     "section_start": "A. TRẮC NGHIỆM (3đ)",
     "section_instruction": None, "passage_text": None,
     "q": "Câu 2. Khẳng định nào dưới đây sai?",
     "options": ["A. Số 19 là một số tự nhiên.", "B. Số −5 là một số nguyên âm.",
                 "C. Số −15/19 là một số hữu tỉ.", "D. Số 0 là một số hữu tỉ dương."],
     "answer": "D. Số 0 là một số hữu tỉ dương.",
     "explanation": "Số 0 không là số hữu tỉ dương cũng không là số hữu tỉ âm."},
    {"type": "choice", "topic": "Số hữu tỉ – so sánh",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Câu 4. Khẳng định nào dưới đây đúng?",
     "options": ["A. −3/5 < 0", "B. 3/10 < 0", "C. −1/2 > 3", "D. −2/3 > 2/3"],
     "answer": "A. −3/5 < 0",
     "explanation": "Số hữu tỉ âm luôn nhỏ hơn 0."},
    {"type": "choice", "topic": "Số hữu tỉ – số đối",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Câu 6. Số đối của 7/9 là",
     "options": ["A. 7/9", "B. 9/7", "C. −7/9", "D. −9/7"],
     "answer": "C. −7/9", "explanation": "Số đối của a là −a."},
    {"type": "choice", "topic": "Lũy thừa của số hữu tỉ",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Câu 7. Kết quả của phép tính (1/3)²⁰²² : (1/3)²⁰²⁰ là",
     "options": ["A. 1/3", "B. 0", "C. 1/9", "D. 2/3"],
     "answer": "C. 1/9", "explanation": "= (1/3)^(2022−2020) = (1/3)² = 1/9."},
    {"type": "choice", "topic": "Hình hộp chữ nhật – hình lập phương",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Câu 9. Hình lập phương có bao nhiêu đường chéo?",
     "options": ["A. 2", "B. 3", "C. 4", "D. 5"],
     "answer": "C. 4", "explanation": "Hình lập phương (và hình hộp chữ nhật) có 4 đường chéo."},
    {"type": "choice", "topic": "Hình lăng trụ đứng",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Câu 10. Khẳng định nào sai?",
     "options": ["A. Hình lập phương là hình lăng trụ đứng.",
                 "B. Hình hộp chữ nhật là hình lăng trụ đứng.",
                 "C. Hình lăng trụ tam giác có đáy là tam giác.",
                 "D. Hình lăng trụ đứng là hình hộp chữ nhật."],
     "answer": "D. Hình lăng trụ đứng là hình hộp chữ nhật.",
     "explanation": "Hình lăng trụ đứng nói chung có đáy là đa giác bất kì, không nhất thiết là hình hộp chữ nhật."},
    {"type": "choice", "topic": "Hình hộp chữ nhật – hình lăng trụ đứng",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Câu 11. Lăng trụ đứng, đáy là hình chữ nhật có",
     "options": ["A. 8 mặt, 8 đỉnh, 12 cạnh.", "B. 6 mặt, 8 đỉnh, 12 cạnh", "C. 8 mặt, 6 đỉnh, 12 cạnh.", "D. 8 mặt, 8 đỉnh, 8 cạnh."],
     "answer": "B. 6 mặt, 8 đỉnh, 12 cạnh",
     "explanation": "Đó là hình hộp chữ nhật: 6 mặt, 8 đỉnh, 12 cạnh."},
    # ── TỰ LUẬN ──
    {"type": "fill", "topic": "Lũy thừa của số hữu tỉ",
     "section_start": "B. TỰ LUẬN (7đ)",
     "section_instruction": "Bài 1. (2,0 điểm) Thực hiện phép tính",
     "passage_text": None,
     "q": "Bài 1c. c) (2⁷ · 9³) / (6⁵ · 8²). " + _FILL_FRAC,
     "answer": "3/16",
     "explanation": "= 2⁷ · 3⁶ / (2⁵ · 3⁵ · 2⁶) = 3 / 2⁴ = 3/16."},
    {"type": "fill", "topic": "Số hữu tỉ",
     "section_start": None,
     "section_instruction": "Bài 2. (2,0 điểm) Tìm x biết",
     "passage_text": None,
     "q": "Bài 2a. a) x + 4,5 = 7,5. Nhập x.",
     "answer": "3",
     "explanation": "x = 7,5 − 4,5 = 3."},
    {"type": "fill", "topic": "Số hữu tỉ",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Bài 2b. b) x − 3/10 = 7/15 · 3/5. Nhập x. " + _FILL_FRAC,
     "answer": "29/50",
     "explanation": "7/15 · 3/5 = 7/25; x = 7/25 + 3/10 = 14/50 + 15/50 = 29/50."},
    {"type": "fill", "topic": "Số hữu tỉ",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Bài 2c. c) 2/3 · x + 1/5 = 7/10. Nhập x. " + _FILL_FRAC,
     "answer": "3/4",
     "explanation": "2/3 · x = 7/10 − 1/5 = 1/2; x = 1/2 : 2/3 = 3/4."},
    {"type": "fill", "topic": "Hình hộp chữ nhật – thể tích",
     "section_start": None,
     "section_instruction": "Bài 4. (1,0 điểm) Một bể cá có dạng hình hộp chữ nhật có chiều dài 4,2 m, chiều rộng 5/2 m, chiều cao 1 2/3 m.",
     "passage_text": None,
     "q": "Bài 4a. Một bể cá có dạng hình hộp chữ nhật có chiều dài 4,2 m, chiều rộng 5/2 m, chiều cao 1 2/3 m (hỗn số). a) Tính thể tích của bể cá đó (m³). Biết V = dài · rộng · cao. Nhập số thập phân dùng dấu phẩy (ví dụ 12,5).",
     "answer": "17,5",
     "explanation": "V = 4,2 · 5/2 · 5/3 = 17,5 (m³)."},
    {"type": "fill", "topic": "Hình hộp chữ nhật – thể tích",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Bài 4b. (Bể cá hình hộp chữ nhật dài 4,2 m, rộng 5/2 m, cao 1 2/3 m.) b) Hỏi, người ta phải đổ vào bể bao nhiêu mét khối nước để lượng nước trong bể bằng 3/5 thể tích của bể (cho biết bể ban đầu không chứa nước). Nhập số thập phân dùng dấu phẩy.",
     "answer": "10,5",
     "explanation": "17,5 · 3/5 = 10,5 (m³)."},
    {"type": "essay", "topic": "Toán thực tế – phần trăm",
     "section_start": None,
     "section_instruction": "Bài 5. (1,0 điểm)",
     "passage_text": None,
     "q": "Bài 5. Một cửa hàng bán đồ nướng mở hai chương trình khuyến mãi: + Hình thức 1: đi 4 tính tiền 3. + Hình thức 2: giảm 15% cho tổng hóa đơn. Biết giá vé cho 1 người là 299 000 đồng (giá chưa bao gồm thuế VAT 10%). Hỏi nếu gia đình bạn An có 5 người thì nên lựa chọn hình thức nào để có lợi hơn.",
     "essay_lines": 8, "essay_word_min": None, "essay_word_max": None,
     "answer": "(Bài làm tự chấm tay)",
     "explanation": "Hướng dẫn chấm: Hình thức 1: … (0,25đ); Hình thức 2: … (0,25đ); An nên chọn hình thức 1 (0,5đ). Gợi ý: hình thức 1 trả tiền 4 người: 4 · 299000 · 110% = 1 315 600 đồng; hình thức 2: 5 · 299000 · 85% · 110% = 1 397 825 đồng; hình thức 1 lợi hơn."},
]

EXAMS = {1: _DE_1, 2: _DE_2, 3: _DE_3, 4: _DE_4, 5: _DE_5}
