# -*- coding: utf-8 -*-
"""Đề Toán 7 cuối HK1 — nguồn Drive (5 đề, chép nguyên văn từ PDF, đáp án theo hướng dẫn chấm trong file).

Text thô đối chiếu: tools/raw_lop79/de_toan_7_hk1/de_<n>.txt

Các câu bị BỎ QUA (lý do):
- Đề 1 (THCS Colette, Quận 3): TN Câu 6 (cần hình lăng trụ); Bài 5b diện tích inox (HDC in ra bị lỗi, không
  đối chiếu được).
- Đề 2 (PGD TP Thái Bình): TN Câu 1 (các dãy số trong option bị mất ký hiệu), Câu 5 (biểu thức bị mất ký hiệu),
  Câu 10 (cần hình); Bài 1.1a, 1.1b (phép tính mất dấu, không khôi phục chắc chắn).
- Đề 3 (PGD Nông Cống, Đề A): Câu 7c (biểu thức mất ký hiệu trị tuyệt đối/phân số).
- Đề 4 (PGD Kiến Xương): TN Câu 1 (ký hiệu tập hợp mất), Câu 4 (cần hình lều trại); Bài 4 (cần hình vẽ).
- Đề 5 (THCS Tào Xuyên, TP Thanh Hóa): TN Câu 8 (dấu trị tuyệt đối mất, hai option trùng nhau), Câu 11 (cần hình);
  Câu 13a (HDC lỗi, không khớp đề); Câu 15 (cần biểu đồ đoạn thẳng).
- Một số câu bị mất ký hiệu (√, | |, phân số, số mũ) đã được khôi phục dựa vào hướng dẫn chấm; ghi chú trong
  "explanation".
File Drive không dùng: Marie Curie (text cụt trang 1, không đáp án), Lomonoxop (text cụt, garbled), Hóc Môn
(16 đề, không đáp án, công thức mất gần hết).
"""

DURATION = 90   # phút, theo đề gốc

SOURCES = {
    1: "Trường THCS Colette, Quận 3, TP.HCM — Đề tham khảo cuối HK1 2024-2025 (1F7HKGUIw3mF1X8GxUlmFHvfLTxN1bXnR)",
    2: "Phòng GD&ĐT TP Thái Bình — Khảo sát chất lượng HK1 2023-2024 (1bANYb7Hb4kWMuEmDeLLj8L-mqQjoFrP9)",
    3: "Phòng GD&ĐT Nông Cống, Thanh Hóa — Khảo sát chất lượng HK1 2023-2024, Đề A (1vyyGpAXWtr_zRqDNL8b5XluGn8QER74T)",
    4: "Phòng GD&ĐT Kiến Xương, Thái Bình — Khảo sát chất lượng HK1 2023-2024 (1uG_e81wbW23lxKEl2KwTVPghMAKSCYJw)",
    5: "Trường THCS Tào Xuyên, TP Thanh Hóa — Kiểm tra HK1 2023-2024 (1CJMTInQjj9WKYdquV1N7yrzk5giYkUJc)",
}

# ═════════════════════════════════════════════════════════════════════════════
# ĐỀ 1 — THCS COLETTE (QUẬN 3, TP.HCM) — ĐỀ THAM KHẢO HK1 2024-2025
# Đáp án TN theo HDC: 1B 2C 3A 4D 5A 6D 7C 8B
# ═════════════════════════════════════════════════════════════════════════════
_DE_1 = [
    {"type": "choice", "topic": "Số hữu tỉ",
     "section_start": "A. TRẮC NGHIỆM (2,0 điểm)",
     "section_instruction": "Hãy chọn đáp án đúng nhất ở mỗi câu bên dưới (mỗi câu 0,25 điểm).",
     "passage_text": None,
     "q": "Câu 1. Kết quả của phép tính: 0,6⁵ : 0,6³ là:",
     "options": ["A. 0,6⁸", "B. 0,6²", "C. 0,6¹⁵", "D. 0,6³"],
     "answer": "B. 0,6²",
     "explanation": "0,6⁵ : 0,6³ = 0,6⁵⁻³ = 0,6². (Số mũ khôi phục từ text thô '0,65:0,63', 'A. 0,68 B. 0,62 C. 0,615 D. 0,63'.)"},
    {"type": "choice", "topic": "Số hữu tỉ",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Câu 2. Tập hợp số hữu tỉ được kí hiệu là:",
     "options": ["A. Z", "B. I", "C. Q", "D. R"],
     "answer": "C. Q",
     "explanation": "Tập hợp số hữu tỉ kí hiệu là Q."},
    {"type": "choice", "topic": "Số thực",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Câu 3. Căn bậc hai số học của 81 là:",
     "options": ["A. 9", "B. 8", "C. 7", "D. 6"],
     "answer": "A. 9",
     "explanation": "√81 = 9 vì 9² = 81 và 9 > 0."},
    {"type": "choice", "topic": "Số thực",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Câu 4. Làm tròn số 7,128 đến hàng phần trăm. Kết quả là:",
     "options": ["A. 7,128", "B. 7,12", "C. 7,14", "D. 7,13"],
     "answer": "D. 7,13",
     "explanation": "Chữ số hàng phần nghìn là 8 ≥ 5 nên làm tròn lên: 7,13."},
    {"type": "choice", "topic": "Hình khối",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Câu 5. Cho hình hộp chữ nhật có chiều dài là 4cm, chiều rộng là 3cm và chiều cao là 5 cm. Khi đó thể tích hình hộp chữ nhật trên là:",
     "options": ["A. 60 cm³", "B. 90 cm³", "C. 120 cm³", "D. 150 cm³"],
     "answer": "A. 60 cm³",
     "explanation": "V = 4 · 3 · 5 = 60 cm³."},
    {"type": "choice", "topic": "Tam giác",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Câu 7. Cho △ABC có ∠C < ∠A < ∠B. Khẳng định nào sau đây đúng?",
     "options": ["A. BC > AC > AB", "B. AB > BC > CA", "C. AC > BC > BA", "D. AC > BA > CB"],
     "answer": "C. AC > BC > BA",
     "explanation": "Góc lớn hơn đối diện cạnh lớn hơn: ∠B lớn nhất → AC lớn nhất; ∠C nhỏ nhất → AB nhỏ nhất. Vậy AC > BC > BA."},
    {"type": "choice", "topic": "Tam giác",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Câu 8. Nếu △ABC = △DEF và ∠A = 100°, AC = 5 cm. Phát biểu nào sau đây là sai?",
     "options": ["A. ∠D = 100°", "B. ∠E = 100°", "C. DF = 5 cm", "D. AB = DE"],
     "answer": "B. ∠E = 100°",
     "explanation": "△ABC = △DEF nên ∠D = ∠A = 100°, DF = AC = 5 cm, DE = AB. ∠E tương ứng với ∠B, không suy ra được bằng 100°."},
    # ── PHẦN TỰ LUẬN ─────────────────────────────────────────────────────────
    {"type": "fill", "topic": "Số thực",
     "section_start": "B. TỰ LUẬN (8,0 điểm)",
     "section_instruction": None, "passage_text": None,
     "q": "Bài 1. (0,5 điểm) Tìm số đối của các số thực sau: 5,12; −√2.\n(Ý 1) Nhập số đối của 5,12.",
     "answer": "-5,12",
     "explanation": "Số đối của 5,12 là −5,12."},
    {"type": "fill", "topic": "Số thực",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Bài 1. (0,5 điểm) Tìm số đối của các số thực sau: 5,12; −√2.\n(Ý 2) Nhập số đối của −√2 (gõ ký tự √, ví dụ √5).",
     "answer": "√2",
     "explanation": "Số đối của −√2 là √2."},
    {"type": "fill", "topic": "Số thực",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Bài 2. (0,5 điểm) Dùng máy tính cầm tay để tính các căn bậc hai số học sau: √676; √3969.\n(Ý 1) Nhập √676.",
     "answer": "26",
     "explanation": "√676 = 26."},
    {"type": "fill", "topic": "Số thực",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Bài 2. (0,5 điểm) Dùng máy tính cầm tay để tính các căn bậc hai số học sau: √676; √3969.\n(Ý 2) Nhập √3969.",
     "answer": "63",
     "explanation": "√3969 = 63."},
    {"type": "fill", "topic": "Số hữu tỉ",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Bài 3. (1,5 điểm) Thực hiện phép tính.\na) 5/4 − 3/8 · 20/9 + 7/3\nNhập kết quả dạng phân số tối giản.",
     "answer": "11/4",
     "explanation": "5/4 − 3/8 · 20/9 + 7/3 = 5/4 − 5/6 + 7/3 = 15/12 − 10/12 + 28/12 = 33/12 = 11/4. (HDC ghi 33/12.)"},
    {"type": "fill", "topic": "Số thực",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Bài 3. (1,5 điểm) Thực hiện phép tính.\nb) (1 − 1/2)² + |−3/5| : √(16/25)\nNhập kết quả.",
     "answer": "1",
     "explanation": "(1 − 1/2)² + |−3/5| : √(16/25) = 1/4 + 3/5 : 4/5 = 1/4 + 3/4 = 1. (Ký hiệu | | và √ khôi phục theo HDC.)"},
    {"type": "fill", "topic": "Số hữu tỉ",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Bài 4. (1,5 điểm) Tìm số thực x, biết:\na) x + 0,75 = −2/3\nNhập x dạng phân số tối giản (ví dụ x=-5/7).",
     "answer": "x=-17/12",
     "explanation": "x + 3/4 = −2/3 → x = −2/3 − 3/4 = −8/12 − 9/12 = −17/12."},
    {"type": "fill", "topic": "Số thực",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Bài 4. (1,5 điểm) Tìm số thực x, biết:\nb) |1/2 − x| = 4/5\nNhập hai giá trị của x theo thứ tự tăng dần, dạng phân số tối giản, cách nhau bằng dấu chấm phẩy (ví dụ -1/2;3/4).",
     "answer": "-3/10;13/10",
     "explanation": "1/2 − x = 4/5 → x = 1/2 − 4/5 = −3/10; hoặc 1/2 − x = −4/5 → x = 1/2 + 4/5 = 13/10."},
    {"type": "fill", "topic": "Hình khối",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Bài 5. (1,5 điểm) Một xe tải đông lạnh chở hàng có thùng xe dạng hình hộp chữ nhật với kích thước như hình bên (theo hình: chiều dài 3 m, chiều rộng 2 m, chiều cao 1,5 m). Bạn hãy tính:\na) Thể tích của thùng xe.\nNhập kết quả (m³), ví dụ 7,5.",
     "answer": "9",
     "explanation": "V = 3 · 2 · 1,5 = 9 (m³). Kích thước lấy từ nhãn hình trong file (3 m, 2 m, 1,5 m) và HDC."},
    {"type": "essay", "topic": "Tam giác",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Bài 6. (2,5 điểm) Cho △ABC có AB = AC và AB > BC. Gọi M là trung điểm của BC.\na) Chứng minh △ABM = △ACM từ đó suy ra ∠BAM = ∠CAM.",
     "essay_lines": 8, "essay_word_min": None, "essay_word_max": None,
     "answer": "(Bài làm tự chấm tay)",
     "explanation": "HDC: Chứng minh được △ABM = △ACM (c-c-c): AB = AC (gt), BM = CM (M trung điểm BC), AM chung. Suy ra ∠BAM = ∠CAM (hai góc tương ứng)."},
    {"type": "essay", "topic": "Tam giác",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Bài 6. (2,5 điểm) Cho △ABC có AB = AC và AB > BC. Gọi M là trung điểm của BC.\nb) Trên cạnh AB lấy điểm D, trên cạnh AC lấy điểm E sao cho AD = AE. Chứng minh DE // BC.",
     "essay_lines": 8, "essay_word_min": None, "essay_word_max": None,
     "answer": "(Bài làm tự chấm tay)",
     "explanation": "HDC: Chứng minh được AM ⊥ BC; chứng minh được AM ⊥ DE; suy ra DE // BC."},
    {"type": "essay", "topic": "Tam giác",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Bài 6. (2,5 điểm) Cho △ABC có AB = AC và AB > BC. Gọi M là trung điểm của BC. Trên cạnh AB lấy điểm D, trên cạnh AC lấy điểm E sao cho AD = AE.\nc) Gọi N là trung điểm của BD. Trên tia đối của tia NM lấy điểm K sao cho NK = NM. Chứng minh K, D, E thẳng hàng.",
     "essay_lines": 10, "essay_word_min": None, "essay_word_max": None,
     "answer": "(Bài làm tự chấm tay)",
     "explanation": "HDC: Chứng minh được △KND = △MNB (c-g-c) suy ra ∠DKN = ∠BMN; chứng minh KD // BM hay KD // BC; kết hợp DE // BC suy ra K, D, E thẳng hàng."},
]

# ═════════════════════════════════════════════════════════════════════════════
# ĐỀ 2 — PHÒNG GD&ĐT TP THÁI BÌNH — KSCL HK1 2023-2024 (biến thể 1)
# Đáp án TN theo HDC: 1D 2C 3B 4A 5A 6A 7C 8C 9B 10D 11B 12D
# ═════════════════════════════════════════════════════════════════════════════
_DE_2 = [
    {"type": "choice", "topic": "Số hữu tỉ",
     "section_start": "I. TRẮC NGHIỆM (3,0 điểm)",
     "section_instruction": "Chọn một chữ cái đứng trước câu trả lời đúng.",
     "passage_text": None,
     "q": "Câu 2. Nếu x thỏa mãn 5ˣ = (5²)³ thì giá trị của x là:",
     "options": ["A. 5", "B. 8", "C. 6", "D. 5⁶"],
     "answer": "C. 6",
     "explanation": "(5²)³ = 5⁶ nên x = 6."},
    {"type": "choice", "topic": "Số hữu tỉ",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Câu 3. Chữ số thập phân thứ sáu của số 0,2(345) là:",
     "options": ["A. 5", "B. 4", "C. 3", "D. 2"],
     "answer": "B. 4",
     "explanation": "0,2(345) = 0,2345345… Các chữ số thập phân: 2, 3, 4, 5, 3, 4,… → chữ số thứ sáu là 4."},
    {"type": "choice", "topic": "Số thực",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Câu 4. Căn bậc hai số học của 9 là:",
     "options": ["A. 3", "B. −3", "C. 81", "D. ±3"],
     "answer": "A. 3",
     "explanation": "√9 = 3."},
    {"type": "choice", "topic": "Số thực",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Câu 6. Từ năm 1997, Chính phủ Việt Nam quyết định lấy ngày 26/12 là ngày Dân số Việt Nam. Dân số của Việt Nam là 100 050 299 người vào ngày 27/12/2023 theo số liệu từ Liên Hợp Quốc (nguồn: https://danso.org/viet-nam/). Làm tròn số dân này với độ chính xác 500, ta được kết quả là:",
     "options": ["A. 100 050 000", "B. 100 000 000", "C. 100 100 000", "D. 100 050 300"],
     "answer": "A. 100 050 000",
     "explanation": "Độ chính xác 500 → làm tròn đến hàng nghìn: 100 050 299 ≈ 100 050 000."},
    {"type": "choice", "topic": "Đại lượng tỉ lệ",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Câu 7. Cho hai đại lượng x và y liên hệ với nhau bởi công thức y = (1/3)x. Khẳng định nào sau đây là đúng?",
     "options": ["A. y tỉ lệ thuận với x theo hệ số tỉ lệ 3",
                 "B. y tỉ lệ nghịch với x theo hệ số tỉ lệ 3",
                 "C. y tỉ lệ thuận với x theo hệ số tỉ lệ 1/3",
                 "D. y tỉ lệ nghịch với x theo hệ số tỉ lệ 1/3"],
     "answer": "C. y tỉ lệ thuận với x theo hệ số tỉ lệ 1/3",
     "explanation": "y = kx với k = 1/3 → y tỉ lệ thuận với x theo hệ số 1/3."},
    {"type": "choice", "topic": "Hình khối",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Câu 8. Hình hộp chữ nhật, hình lập phương, hình lăng trụ đứng tam giác và hình lăng trụ đứng tứ giác có chung đặc điểm nào dưới đây?",
     "options": ["A. Có 6 mặt", "B. Có 8 đỉnh", "C. Các mặt đáy song song", "D. Mỗi đỉnh có 3 góc vuông"],
     "answer": "C. Các mặt đáy song song",
     "explanation": "Lăng trụ đứng tam giác có 5 mặt, 6 đỉnh; đặc điểm chung là hai mặt đáy song song."},
    {"type": "choice", "topic": "Hình khối",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Câu 9. Một hình lập phương có diện tích toàn phần là 216 cm². Độ dài cạnh của hình lập phương đó là:",
     "options": ["A. 4 cm", "B. 6 cm", "C. 18 cm", "D. 36 cm"],
     "answer": "B. 6 cm",
     "explanation": "Diện tích một mặt: 216 : 6 = 36 cm² → cạnh = 6 cm."},
    {"type": "choice", "topic": "Góc và đường thẳng song song",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Câu 11. Hai góc đối đỉnh thì:",
     "options": ["A. Kề nhau", "B. Bằng nhau", "C. Kề bù", "D. Bù nhau"],
     "answer": "B. Bằng nhau",
     "explanation": "Tính chất: hai góc đối đỉnh thì bằng nhau."},
    {"type": "choice", "topic": "Góc và đường thẳng song song",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Câu 12. Cho ba đường thẳng phân biệt a, b, c. Khẳng định nào sau đây là đúng?",
     "options": ["A. Nếu a // b; b // c thì a ⊥ c",
                 "B. Nếu a ⊥ b; b ⊥ c thì a ⊥ c",
                 "C. Nếu a ⊥ b; b // c thì a // c",
                 "D. Nếu a // b; b // c thì a // c"],
     "answer": "D. Nếu a // b; b // c thì a // c",
     "explanation": "Hai đường thẳng phân biệt cùng song song với đường thẳng thứ ba thì song song với nhau."},
    # ── PHẦN TỰ LUẬN ─────────────────────────────────────────────────────────
    {"type": "fill", "topic": "Số hữu tỉ",
     "section_start": "II. TỰ LUẬN (7,0 điểm)",
     "section_instruction": None, "passage_text": None,
     "q": "Bài 1. (3,0 điểm) 2. Tìm x, biết:\na) 2x − 3/4 = 1/4\nNhập x dạng phân số tối giản (ví dụ x=3/5).",
     "answer": "x=1/2",
     "explanation": "2x = 1/4 + 3/4 = 1 → x = 1/2. (Dấu phép tính khôi phục theo HDC: '2x = 1/4 + 3/4 = 1'.)"},
    {"type": "fill", "topic": "Số thực",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Bài 1. (3,0 điểm) 2. Tìm x, biết:\nb) |x − 3| : 5 = 1/2\nNhập hai giá trị của x theo thứ tự tăng dần, dạng phân số tối giản, cách nhau bằng dấu chấm phẩy (ví dụ 1/3;7/2).",
     "answer": "1/2;11/2",
     "explanation": "|x − 3| = 5/2 → x − 3 = 5/2 hoặc x − 3 = −5/2 → x = 11/2 hoặc x = 1/2. (Biểu thức khôi phục theo HDC; text thô mất ký hiệu.)"},
    {"type": "fill", "topic": "Đại lượng tỉ lệ",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Bài 1. (3,0 điểm) 3. Cho biết x, y tỉ lệ nghịch với nhau và khi x = −4 thì y = 5. Viết công thức tính y theo x.\nNhập hệ số tỉ lệ k trong công thức y = k/x.",
     "answer": "-20",
     "explanation": "k = x · y = (−4) · 5 = −20. Công thức: y = −20/x."},
    {"type": "fill", "topic": "Đại lượng tỉ lệ",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Bài 2. (1,0 điểm) Một lớp 7 của một trường THCS có số học sinh gồm ba loại học lực: Tốt, Khá, Đạt. Biết số học sinh có học lực Tốt, Khá, Đạt lần lượt tỉ lệ với các số 6; 3; 2 và số học sinh có học lực Tốt nhiều hơn số học sinh có học lực Khá là 12 em. Tìm số học sinh của lớp 7 đó.\nNhập số học sinh của lớp.",
     "answer": "44",
     "explanation": "a/6 = b/3 = c/2 = (a − b)/(6 − 3) = 12/3 = 4 → a = 24, b = 12, c = 8. Lớp có 24 + 12 + 8 = 44 học sinh."},
    {"type": "fill", "topic": "Hình khối",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Bài 3. (2,5 điểm) 1. Căn phòng nhà bạn An có một cửa lớn hình chữ nhật và một cửa sổ hình vuông với kích thước bên trong căn phòng (như hình vẽ: phòng dài 10 m, rộng 4 m, cao 3 m; cửa lớn 2 m × 1,5 m; cửa sổ cạnh 1 m). Bố bạn An cần trả bao nhiêu tiền để sơn bốn bức tường xung quanh bên trong căn phòng này (không sơn cửa)? Biết rằng để sơn mỗi mét vuông phải tốn 100 000 đồng (đã bao gồm tất cả các chi phí).\nNhập số tiền (đồng), chỉ gồm chữ số.",
     "answer": "8000000",
     "explanation": "Diện tích xung quanh: 2 · (10 + 4) · 3 = 84 m². Diện tích cửa: 2 · 1,5 + 1² = 4 m². Diện tích sơn: 84 − 4 = 80 m². Tiền: 80 · 100 000 = 8 000 000 đồng. (Kích thước lấy từ HDC vì hình vẽ không có trong text.)"},
    {"type": "essay", "topic": "Góc và đường thẳng song song",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Bài 3. (2,5 điểm) 2. Vẽ góc xOy bằng 60°. Trên tia Oy lấy điểm A. Vẽ tia Az sao cho tia Az nằm cùng phía với tia Ox đối với đường thẳng OA và ∠yAz = 60°.\na) Chứng minh: Ox // Az.",
     "essay_lines": 6, "essay_word_min": None, "essay_word_max": None,
     "answer": "(Bài làm tự chấm tay)",
     "explanation": "HDC: Ta có ∠xOy = ∠yAz = 60° (gt). Mà hai góc này ở vị trí đồng vị → Ox // Az (dấu hiệu nhận biết)."},
    {"type": "essay", "topic": "Góc và đường thẳng song song",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Bài 3. (2,5 điểm) 2. Vẽ góc xOy bằng 60°. Trên tia Oy lấy điểm A. Vẽ tia Az sao cho tia Az nằm cùng phía với tia Ox đối với đường thẳng OA và ∠yAz = 60°.\nb) Vẽ tia phân giác của góc OAz cắt tia Ox tại M. Tia Az có là tia phân giác của góc MAy không? Vì sao?",
     "essay_lines": 8, "essay_word_min": None, "essay_word_max": None,
     "answer": "(Bài làm tự chấm tay)",
     "explanation": "HDC: ∠OAz + ∠zAy = 180° (kề bù) → ∠OAz = 120°. AM là tia phân giác của ∠OAz → ∠MAz = 1/2 · 120° = 60° = ∠yAz. Lại có tia Az nằm trong góc MAy nên Az là tia phân giác của góc MAy."},
    {"type": "fill", "topic": "Số hữu tỉ",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Bài 4. (0,5 điểm) Cho các số a, b, c ≥ 0 thỏa mãn: 2a + 13c = 48 và a + 4b = 4024. Tìm giá trị lớn nhất của biểu thức P = a + 2b + 3c.\nNhập giá trị lớn nhất của P.",
     "answer": "2024",
     "explanation": "2a + 13c = 48 và 2a + 8b = 8048 → 4a + 8b + 13c = 8096 → 4(a + 2b + 3c) + c = 8096 → 4P + c = 8096. Vì c ≥ 0 nên P ≤ 2024. Dấu '=' khi c = 0, a = 24, b = 1000. Max P = 2024."},
]

# ═════════════════════════════════════════════════════════════════════════════
# ĐỀ 3 — PHÒNG GD&ĐT NÔNG CỐNG (THANH HÓA) — KSCL HK1 2023-2024, ĐỀ A
# Đáp án TN theo HDC: 1D 2B 3D 4C 5B 6C
# ═════════════════════════════════════════════════════════════════════════════
_DE_3 = [
    {"type": "choice", "topic": "Số hữu tỉ",
     "section_start": "I. TRẮC NGHIỆM KHÁCH QUAN (3,0 điểm)",
     "section_instruction": "Hãy khoanh tròn chữ cái đứng trước câu trả lời đúng trong các câu sau:",
     "passage_text": None,
     "q": "Câu 1. Trong các số sau, số thập phân vô hạn tuần hoàn là:",
     "options": ["A. 2,345", "B. 2,333", "C. 2,3", "D. 2,(3)"],
     "answer": "D. 2,(3)",
     "explanation": "2,(3) = 2,333… là số thập phân vô hạn tuần hoàn."},
    {"type": "choice", "topic": "Số thực",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Câu 2. Trong các số sau, số vô tỉ là:",
     "options": ["A. −2", "B. √2", "C. 0", "D. 1/2"],
     "answer": "B. √2",
     "explanation": "√2 là số vô tỉ. (Ký hiệu √ và phân số khôi phục từ text thô 'A. 2− B. 2 C. 0 D. 12' theo đáp án B.)"},
    {"type": "choice", "topic": "Số thực",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Câu 3. Nếu √x = 9 thì x bằng:",
     "options": ["A. 3", "B. 9", "C. 18", "D. 81"],
     "answer": "D. 81",
     "explanation": "√x = 9 → x = 9² = 81. (Ký hiệu √ khôi phục theo đáp án D.)"},
    {"type": "choice", "topic": "Số thực",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Câu 4. Cho |x| = 3/5 thì:",
     "options": ["A. x = 3/5", "B. x = −3/5", "C. x = 3/5 hoặc x = −3/5", "D. x = 5/3 hoặc x = −5/3"],
     "answer": "C. x = 3/5 hoặc x = −3/5",
     "explanation": "|x| = 3/5 → x = 3/5 hoặc x = −3/5. (Ký hiệu | | và phân số khôi phục theo đáp án C.)"},
    {"type": "choice", "topic": "Tam giác",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Câu 5. Cho tam giác ABC cân tại A, biết ∠A = 80°. Số đo góc C là:",
     "options": ["A. 40°", "B. 50°", "C. 80°", "D. 100°"],
     "answer": "B. 50°",
     "explanation": "Tam giác cân tại A: ∠B = ∠C = (180° − 80°) : 2 = 50°."},
    {"type": "choice", "topic": "Tam giác",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Câu 6. Nếu △MNP = △EFQ thì hai cạnh tương ứng bằng nhau là:",
     "options": ["A. NP = EQ", "B. MP = FQ", "C. MN = EF", "D. MP = EF"],
     "answer": "C. MN = EF",
     "explanation": "△MNP = △EFQ: M↔E, N↔F, P↔Q nên MN = EF."},
    # ── PHẦN TỰ LUẬN ─────────────────────────────────────────────────────────
    {"type": "fill", "topic": "Số thực",
     "section_start": "II. TỰ LUẬN (7,0 điểm)",
     "section_instruction": None, "passage_text": None,
     "q": "Câu 7. (1,5 điểm) Thực hiện phép tính.\na. √36 − √9\nNhập kết quả.",
     "answer": "3",
     "explanation": "√36 − √9 = 6 − 3 = 3."},
    {"type": "fill", "topic": "Số hữu tỉ",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Câu 7. (1,5 điểm) Thực hiện phép tính.\nb. 8/13 · 1/4 + 8/13 · 3/4 + 5/13\nNhập kết quả.",
     "answer": "1",
     "explanation": "= 8/13 · (1/4 + 3/4) + 5/13 = 8/13 + 5/13 = 1."},
    {"type": "fill", "topic": "Số thực",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Câu 8. (1,0 điểm) Tìm x, biết.\na. 3x − 1/3 = √(25/9)\nNhập x dạng phân số tối giản (ví dụ x=4/7).",
     "answer": "x=2/3",
     "explanation": "3x − 1/3 = 5/3 → 3x = 2 → x = 2/3. (Ký hiệu √ khôi phục theo HDC.)"},
    {"type": "fill", "topic": "Số thực",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Câu 8. (1,0 điểm) Tìm x, biết.\nb. |2x − 2| − 3,75 = 0,25\nNhập hai giá trị của x theo thứ tự tăng dần, cách nhau bằng dấu chấm phẩy (ví dụ -2;5).",
     "answer": "-1;3",
     "explanation": "|2x − 2| = 4 → 2x − 2 = 4 hoặc 2x − 2 = −4 → x = 3 hoặc x = −1."},
    {"type": "essay", "topic": "Thống kê",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Câu 9. (1,5 điểm) Bảng thống kê sau cho biết sự yêu thích các môn thể thao của học sinh lớp 7A.\nMôn thể thao: Bóng đá – Bóng chuyền – Đá cầu – Bóng bàn\nTỉ lệ: 40% – 30% – 20% – 10%\nVẽ biểu đồ hình quạt tròn biểu diễn bảng thống kê trên.",
     "essay_lines": 6, "essay_word_min": None, "essay_word_max": None,
     "answer": "(Bài làm tự chấm tay)",
     "explanation": "HDC: Học sinh vẽ đúng biểu đồ hình quạt tròn. Nếu thiếu tiêu đề trừ 0,25đ, không chú giải trừ 0,25đ."},
    {"type": "essay", "topic": "Tam giác",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Câu 10. (2,5 điểm) Cho tam giác ABC cân tại A. Gọi M là trung điểm của BC. Trên tia đối của tia MA lấy điểm D sao cho MD = MA. Qua M kẻ ME vuông góc với AB tại E, MF vuông góc với DC tại F. Chứng minh rằng:\na. △ABM = △ACM",
     "essay_lines": 6, "essay_word_min": None, "essay_word_max": None,
     "answer": "(Bài làm tự chấm tay)",
     "explanation": "HDC: Xét △ABM và △ACM có: AB = AC (gt), AM cạnh chung, BM = CM (gt) → △ABM = △ACM (c.c.c)."},
    {"type": "essay", "topic": "Tam giác",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Câu 10. (2,5 điểm) Cho tam giác ABC cân tại A. Gọi M là trung điểm của BC. Trên tia đối của tia MA lấy điểm D sao cho MD = MA. Qua M kẻ ME vuông góc với AB tại E, MF vuông góc với DC tại F. Chứng minh rằng:\nb. AB // CD",
     "essay_lines": 8, "essay_word_min": None, "essay_word_max": None,
     "answer": "(Bài làm tự chấm tay)",
     "explanation": "HDC: Xét △ABM và △DCM có BM = CM (gt), MA = MD (gt), ∠AMB = ∠DMC (đối đỉnh) → △ABM = △DCM (c.g.c) → ∠ABM = ∠DCM (2 góc tương ứng). Mà 2 góc này ở vị trí so le trong → AB // CD."},
    {"type": "essay", "topic": "Tam giác",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Câu 10. (2,5 điểm) Cho tam giác ABC cân tại A. Gọi M là trung điểm của BC. Trên tia đối của tia MA lấy điểm D sao cho MD = MA. Qua M kẻ ME vuông góc với AB tại E, MF vuông góc với DC tại F. Chứng minh rằng:\nc. M là trung điểm của EF.",
     "essay_lines": 10, "essay_word_min": None, "essay_word_max": None,
     "answer": "(Bài làm tự chấm tay)",
     "explanation": "HDC: Xét △EBM và △FCM có ∠BEM = ∠CFM = 90°, ∠EBM = ∠FCM (cmt), BM = CM (gt) → △EBM = △FCM (cạnh huyền – góc nhọn) → ME = MF (1) và ∠BME = ∠CMF. Mà ∠BME + ∠CME = 180° (kề bù) → ∠CMF + ∠CME = 180° → E, M, F thẳng hàng (2). Từ (1) và (2) → M là trung điểm của EF."},
    {"type": "fill", "topic": "Số thực",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Câu 11. (0,5 điểm) Tìm giá trị nhỏ nhất của biểu thức: A = (x − 1)² + |2x − y| + 2024.\nNhập giá trị nhỏ nhất của A.",
     "answer": "2024",
     "explanation": "(x − 1)² ≥ 0 và |2x − y| ≥ 0 với mọi x, y → A ≥ 2024. Dấu bằng khi x − 1 = 0 và 2x − y = 0 → x = 1, y = 2. Min A = 2024."},
]

# ═════════════════════════════════════════════════════════════════════════════
# ĐỀ 4 — PHÒNG GD&ĐT KIẾN XƯƠNG (THÁI BÌNH) — KSCL HK1 2023-2024
# Đáp án TN theo HDC: 1B 2C 3B 4A 5C
# ═════════════════════════════════════════════════════════════════════════════
_DE_4 = [
    {"type": "choice", "topic": "Đại lượng tỉ lệ",
     "section_start": "I/ TRẮC NGHIỆM (2,5 điểm)",
     "section_instruction": "Chọn chữ cái in hoa đứng trước câu trả lời em cho là đúng trong mỗi câu sau:",
     "passage_text": None,
     "q": "Câu 2: Cho biết đại lượng y tỉ lệ thuận với đại lượng x và khi x = 4 thì y = 12. Tìm hệ số tỉ lệ k của y đối với x?",
     "options": ["A. k = 1/3", "B. k = 48", "C. k = 3", "D. k = 8"],
     "answer": "C. k = 3",
     "explanation": "y = kx → k = y/x = 12/4 = 3. (Option A '13' trong text thô là 1/3.)"},
    {"type": "choice", "topic": "Số thực",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Câu 3: Cho biết số π = 3,141592653… Kết quả làm tròn số π với độ chính xác 0,005 là:",
     "options": ["A. π ≈ 3,142", "B. π ≈ 3,14", "C. π ≈ 3,141", "D. π ≈ 3,15"],
     "answer": "B. π ≈ 3,14",
     "explanation": "Độ chính xác 0,005 → làm tròn đến hàng phần trăm: π ≈ 3,14."},
    {"type": "choice", "topic": "Góc và đường thẳng song song",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Câu 5: Cho đường thẳng c cắt hai đường thẳng a và b, trong các góc tạo thành có một cặp góc so le trong bằng nhau thì:",
     "options": ["A. a ⊥ b", "B. a cắt b", "C. a // b", "D. a trùng với b"],
     "answer": "C. a // b",
     "explanation": "Dấu hiệu nhận biết hai đường thẳng song song."},
    # ── PHẦN TỰ LUẬN ─────────────────────────────────────────────────────────
    {"type": "fill", "topic": "Số hữu tỉ",
     "section_start": "II/ TỰ LUẬN (7,5 điểm)",
     "section_instruction": None, "passage_text": None,
     "q": "Bài 1: (1,5 điểm) Thực hiện phép tính (tính hợp lý nếu có thể):\na) 15/34 + 7/21 + 19/34 − 20/15 + 7/3\nNhập kết quả dạng phân số tối giản.",
     "answer": "7/3",
     "explanation": "= (15/34 + 19/34) + (1/3 − 4/3) + 7/3 = 1 + (−1) + 7/3 = 7/3. (Phân số khôi phục theo HDC: 7/21 = 1/3, 20/15 = 4/3.)"},
    {"type": "fill", "topic": "Số hữu tỉ",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Bài 1: (1,5 điểm) Thực hiện phép tính (tính hợp lý nếu có thể):\nb) 10/12 + (−5/6)² · 6/25 − 2023⁰\nNhập kết quả.",
     "answer": "0",
     "explanation": "= 5/6 + 25/36 · 6/25 − 1 = 5/6 + 1/6 − 1 = 0. (Phân số khôi phục theo HDC: kết quả 0.)"},
    {"type": "fill", "topic": "Số thực",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Bài 1: (1,5 điểm) Thực hiện phép tính (tính hợp lý nếu có thể):\nc) √36 + 10 · √1,21 − 2/5 · √(25/4)\nNhập kết quả.",
     "answer": "16",
     "explanation": "= 6 + 10 · 1,1 − 2/5 · 5/2 = 6 + 11 − 1 = 16."},
    {"type": "fill", "topic": "Số hữu tỉ",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Bài 2: (1,5 điểm) Tìm x, biết:\na) x + 2/5 = 7/10\nNhập x dạng phân số tối giản (ví dụ x=1/5).",
     "answer": "x=3/10",
     "explanation": "x = 7/10 − 2/5 = 7/10 − 4/10 = 3/10."},
    {"type": "fill", "topic": "Số thực",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Bài 2: (1,5 điểm) Tìm x, biết:\nb) |x − 2/5| + 3/4 = 11/4\nNhập hai giá trị của x theo thứ tự tăng dần, dạng phân số tối giản, cách nhau bằng dấu chấm phẩy (ví dụ -1/5;7/5).",
     "answer": "-8/5;12/5",
     "explanation": "|x − 2/5| = 11/4 − 3/4 = 2 → x − 2/5 = 2 → x = 12/5; hoặc x − 2/5 = −2 → x = −8/5. (Dấu phép tính khôi phục theo HDC.)"},
    {"type": "fill", "topic": "Đại lượng tỉ lệ",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Bài 3: (1,5 điểm) Ba lớp 7A, 7B, 7C tham gia lao động trồng cây. Biết rằng số cây của lớp 7A; 7B; 7C trồng được lần lượt tỉ lệ với 6; 4; 5 và tổng số cây của hai lớp 7A; 7B trồng được nhiều hơn số cây của lớp 7C là 40 cây. Tính số cây mỗi lớp trồng được.\n(Ý 1) Nhập số cây lớp 7A trồng được.",
     "answer": "48",
     "explanation": "a/6 = b/4 = c/5 = (a + b − c)/(6 + 4 − 5) = 40/5 = 8 → a = 48, b = 32, c = 40."},
    {"type": "fill", "topic": "Đại lượng tỉ lệ",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Bài 3: (1,5 điểm) Ba lớp 7A, 7B, 7C tham gia lao động trồng cây. Biết rằng số cây của lớp 7A; 7B; 7C trồng được lần lượt tỉ lệ với 6; 4; 5 và tổng số cây của hai lớp 7A; 7B trồng được nhiều hơn số cây của lớp 7C là 40 cây. Tính số cây mỗi lớp trồng được.\n(Ý 2) Nhập số cây lớp 7B trồng được.",
     "answer": "32",
     "explanation": "b = 4 · 8 = 32 cây."},
    {"type": "fill", "topic": "Đại lượng tỉ lệ",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Bài 3: (1,5 điểm) Ba lớp 7A, 7B, 7C tham gia lao động trồng cây. Biết rằng số cây của lớp 7A; 7B; 7C trồng được lần lượt tỉ lệ với 6; 4; 5 và tổng số cây của hai lớp 7A; 7B trồng được nhiều hơn số cây của lớp 7C là 40 cây. Tính số cây mỗi lớp trồng được.\n(Ý 3) Nhập số cây lớp 7C trồng được.",
     "answer": "40",
     "explanation": "c = 5 · 8 = 40 cây."},
    {"type": "fill", "topic": "Số thực",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Bài 5: (0,5 điểm) Tìm x, biết: |x + 1/(1.2.3)| + |x + 1/(2.3.4)| + |x + 1/(3.4.5)| + ... + |x + 1/(18.19.20)| = 19x.\nNhập x dạng phân số tối giản (ví dụ x=3/40).",
     "answer": "x=189/760",
     "explanation": "VT ≥ 0 → 19x ≥ 0 → x ≥ 0, khi đó bỏ được dấu trị tuyệt đối: 18x + (1/(1.2.3) + … + 1/(18.19.20)) = 19x → x = 1/(1.2.3) + … + 1/(18.19.20) → 2x = 1/(1.2) − 1/(19.20) = 189/380 → x = 189/760."},
]

# ═════════════════════════════════════════════════════════════════════════════
# ĐỀ 5 — THCS TÀO XUYÊN (TP THANH HÓA) — KIỂM TRA HK1 2023-2024
# Đáp án TN theo HDC: 1C 2A 3B 4A 5A 6A 7B 8A 9C 10D 11B 12D
# ═════════════════════════════════════════════════════════════════════════════
_DE_5 = [
    {"type": "choice", "topic": "Số hữu tỉ",
     "section_start": "I. PHẦN TRẮC NGHIỆM (3,0 điểm)",
     "section_instruction": "Khoanh tròn vào chữ cái trước câu trả lời đúng:",
     "passage_text": None,
     "q": "Câu 1. Số đối của số hữu tỉ −1/2 là:",
     "options": ["A. −2", "B. 2", "C. 1/2", "D. −1/2"],
     "answer": "C. 1/2",
     "explanation": "Số đối của −1/2 là 1/2. (Phân số khôi phục từ text thô '- 21', 'A. 2- B. 2 C. 12 D. 2- 1'.)"},
    {"type": "choice", "topic": "Số thực",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Câu 2. Làm tròn số thập phân 1,298603 đến chữ số thập phân thứ 3 là?",
     "options": ["A. 1,299", "B. 1,298", "C. 1,290", "D. 1,2986"],
     "answer": "A. 1,299",
     "explanation": "Chữ số thập phân thứ 4 là 6 ≥ 5 → 1,299."},
    {"type": "choice", "topic": "Số hữu tỉ",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Câu 3. Chọn khẳng định đúng",
     "options": ["A. 3/2 ∈ Z", "B. 3/2 ∈ Q", "C. −5/9 ∉ Q", "D. −5 ∈ N"],
     "answer": "B. 3/2 ∈ Q",
     "explanation": "3/2 là số hữu tỉ. (Phân số khôi phục từ text thô '32 Z∈', '32 Q∈', '- 5 9∉ Q'.)"},
    {"type": "choice", "topic": "Số hữu tỉ",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Câu 4. Kết quả của phép tính 3¹⁰ : 3 viết dưới dạng lũy thừa là",
     "options": ["A. 3⁹", "B. 3¹⁰", "C. 3¹¹", "D. 10"],
     "answer": "A. 3⁹",
     "explanation": "3¹⁰ : 3 = 3¹⁰⁻¹ = 3⁹."},
    {"type": "choice", "topic": "Số thực",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Câu 5. Trong các kết quả sau, kết quả nào đúng?",
     "options": ["A. √16 = 4", "B. √25 = −5", "C. √9 = 0,3", "D. √8 = 4"],
     "answer": "A. √16 = 4",
     "explanation": "√16 = 4. (Ký hiệu √ khôi phục; text thô '16 = 4', '25 = - 5', '9 = 0,3', '8 = 4'.)"},
    {"type": "choice", "topic": "Số thực",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Câu 6. Nếu √x = 3 thì x bằng?",
     "options": ["A. 9", "B. −9", "C. 3", "D. −3"],
     "answer": "A. 9",
     "explanation": "√x = 3 → x = 9."},
    {"type": "choice", "topic": "Số thực",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Câu 7: Số nào là số vô tỷ?",
     "options": ["A. 10", "B. √10", "C. √100", "D. √9"],
     "answer": "B. √10",
     "explanation": "√10 là số vô tỉ; √100 = 10, √9 = 3 là số hữu tỉ. (Ký hiệu √ khôi phục theo đáp án B.)"},
    {"type": "choice", "topic": "Tam giác",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Câu 9. Cho △ABC = △MNE. Biết ∠A = 30°; ∠N = 65°. Số đo của góc C bằng",
     "options": ["A. 30°", "B. 65°", "C. 85°", "D. 95°"],
     "answer": "C. 85°",
     "explanation": "∠B = ∠N = 65° → ∠C = 180° − 30° − 65° = 85°."},
    {"type": "choice", "topic": "Thống kê",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Câu 10. Dựa vào bảng thống kê sau, em hãy cho biết tỉ lệ % xếp loại học lực Khá và Tốt của học sinh lớp 7 là:\nXếp loại: Tốt – Khá – Đạt – Chưa đạt\nTỉ lệ (%): 10 – 25 – 45 – 20",
     "options": ["A. 10%", "B. 20%", "C. 25%", "D. 35%"],
     "answer": "D. 35%",
     "explanation": "10% + 25% = 35%."},
    {"type": "choice", "topic": "Tam giác",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Câu 12: Cho △ABC vuông ở A, ∠ABC = 60°. Tia phân giác của góc ACB cắt AB tại K. Số đo của góc AKC bằng",
     "options": ["A. 15°", "B. 30°", "C. 60°", "D. 75°"],
     "answer": "D. 75°",
     "explanation": "∠ACB = 90° − 60° = 30° → ∠ACK = 15° → ∠AKC = 90° − 15° = 75°. (Tên góc 60° bị mất trong text thô, khôi phục là ∠ABC theo đáp án D.)"},
    # ── PHẦN TỰ LUẬN ─────────────────────────────────────────────────────────
    {"type": "fill", "topic": "Số hữu tỉ",
     "section_start": "II. PHẦN TỰ LUẬN (7,0 điểm)",
     "section_instruction": None, "passage_text": None,
     "q": "Câu 13 (1,5 điểm). Thực hiện các phép tính:\nb) 13 : 5/2 − 23 : 5/2\nNhập kết quả.",
     "answer": "-4",
     "explanation": "= 13 · 2/5 − 23 · 2/5 = 2/5 · (13 − 23) = 2/5 · (−10) = −4."},
    {"type": "fill", "topic": "Số thực",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Câu 13 (1,5 điểm). Thực hiện các phép tính:\nc) 0,5 · √36 − 1/4 · √16 + (−1/3)²\nNhập kết quả dạng phân số tối giản.",
     "answer": "19/9",
     "explanation": "= 0,5 · 6 − 1/4 · 4 + 1/9 = 3 − 1 + 1/9 = 19/9."},
    {"type": "fill", "topic": "Số hữu tỉ",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Câu 14 (1,5 điểm). Tìm x biết:\na) 2/5 − x = 1/4\nNhập x dạng phân số tối giản (ví dụ x=1/20).",
     "answer": "x=3/20",
     "explanation": "x = 2/5 − 1/4 = 8/20 − 5/20 = 3/20."},
    {"type": "fill", "topic": "Số thực",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Câu 14 (1,5 điểm). Tìm x biết:\nb) |x + 2/3| − 2/5 = 3/5\nNhập hai giá trị của x theo thứ tự tăng dần, dạng phân số tối giản, cách nhau bằng dấu chấm phẩy (ví dụ -1/3;2/3).",
     "answer": "-5/3;1/3",
     "explanation": "|x + 2/3| = 1 → x + 2/3 = 1 → x = 1/3; hoặc x + 2/3 = −1 → x = −5/3."},
    {"type": "fill", "topic": "Số hữu tỉ",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Câu 14 (1,5 điểm). Tìm x biết:\nc) (4/3)^(2x+1) = (16/9)³\nNhập x dạng phân số tối giản (ví dụ x=7/2).",
     "answer": "x=5/2",
     "explanation": "(16/9)³ = (4/3)⁶ → 2x + 1 = 6 → x = 5/2. (Số mũ khôi phục theo HDC: '2x+1 = 6'.)"},
    {"type": "essay", "topic": "Tam giác",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Câu 16 (2,5 điểm). Cho △ABC vuông tại A. Gọi M là trung điểm BC. Trên tia đối của tia MA lấy điểm E sao cho MA = ME.\na) Chứng minh △MAB = △MEC",
     "essay_lines": 6, "essay_word_min": None, "essay_word_max": None,
     "answer": "(Bài làm tự chấm tay)",
     "explanation": "HDC: Xét △MAB và △MEC có MA = ME (gt), ∠AMB = ∠EMC (đối đỉnh), MB = MC (gt) → △MAB = △MEC (c.g.c)."},
    {"type": "essay", "topic": "Tam giác",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Câu 16 (2,5 điểm). Cho △ABC vuông tại A. Gọi M là trung điểm BC. Trên tia đối của tia MA lấy điểm E sao cho MA = ME.\nb) Vì sao AB // EC?",
     "essay_lines": 6, "essay_word_min": None, "essay_word_max": None,
     "answer": "(Bài làm tự chấm tay)",
     "explanation": "HDC: Do △MAB = △MEC (câu a) → ∠MAB = ∠MEC (2 góc tương ứng), mà hai góc này ở vị trí so le trong → AB // EC."},
    {"type": "essay", "topic": "Tam giác",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Câu 16 (2,5 điểm). Cho △ABC vuông tại A. Gọi M là trung điểm BC. Trên tia đối của tia MA lấy điểm E sao cho MA = ME.\nc) Chứng minh △BEC vuông tại E",
     "essay_lines": 8, "essay_word_min": None, "essay_word_max": None,
     "answer": "(Bài làm tự chấm tay)",
     "explanation": "HDC: Xét △AMC và △EMB có MA = ME (gt), ∠AMC = ∠EMB (đối đỉnh), MB = MC (gt) → △AMC = △EMB (c.g.c) → ∠MEB = ∠MAC (2). Từ (1) ∠MAB = ∠MEC và (2) suy ra ∠BEC = ∠BEM + ∠MEC = ∠MAC + ∠MAB = 90°. Vậy △BEC vuông tại E."},
    {"type": "essay", "topic": "Số hữu tỉ",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Câu 17 (0,5 điểm). Tìm các giá trị nguyên của x và y biết: 5y − 6x = 2xy − 12",
     "essay_lines": 8, "essay_word_min": None, "essay_word_max": None,
     "answer": "(Bài làm tự chấm tay)",
     "explanation": "HDC: 2xy + 6x − 5y − 12 = 0 → 2x(y + 3) − 5(y + 3) + 3 = 0 → (y + 3)(2x − 5) = −3 = 1·(−3) = (−3)·1 = (−1)·3 = 3·(−1). Lập bảng: (x; y) = (4; −4); (2; 0); (3; −6); (1; −2)."},
]

EXAMS = {1: _DE_1, 2: _DE_2, 3: _DE_3, 4: _DE_4, 5: _DE_5}
