# -*- coding: utf-8 -*-
"""Đề Toán 9 giữa HK1 — nguồn: "14. 10 đề thi Toán 9 giữa kì 1 – Kết Nối Tri Thức có đáp án.pdf"
(Google Drive fileId 1DgY-ppG_DyOzi4kup5wW5jmZWTKbRKc_, GV Nguyễn Thế Bình).

LƯU Ý QUAN TRỌNG: dù tên file ghi "10 đề", file PDF thực tế (39 trang) CHỈ CHỨA 2 ĐỀ
(Mã đề MT101 = Đề số 01, Mã đề MT102 = Đề số 02), mỗi đề kèm bảng đáp án trắc nghiệm và
hướng dẫn giải tự luận. Kết thúc Đề 02 là "-----HẾT-----" và hết file. Trên Drive không có
file Toán 9 giữa kì 1 nào khác được chia sẻ, nên module này chỉ có 2 đề (EXAMS = {1, 2}).
Text thô dùng đối chiếu: tools/raw_lop79/de_toan_9_giua_hk1/raw.txt.

Mỗi đề: 8 câu trắc nghiệm (2,0 điểm) + 5 bài tự luận (8,0 điểm); thời gian 90 phút.
Cấu trúc file: A. TRẮC NGHIỆM / B. TỰ LUẬN (không có phần Đúng/Sai hay trả lời ngắn).

Các câu bị bỏ qua / điều chỉnh:
- Không bỏ câu nào. Hai bài hình thực tế (Đề 1 Bài 4, Đề 2 Bài 4) có hình vẽ nhưng lời văn
  mô tả đủ dữ kiện; phần trong ngoặc vuông [...] là chú thích thay hình, không thuộc đề gốc.
- Đề 1 Bài 4b (góc α ≈ 68°46′) và Bài 5 (chứng minh BĐT), Đề 2 Bài 4b và Bài 5 (nghiệm
  chứa tham số a, b, c) để dạng essay vì đáp số không chấm được bằng so sánh chuỗi.
- Đề 2 Bài 4: đề ghi góc A = 4°, góc B = 6° nhưng hướng dẫn giải lại dùng góc A = 6°,
  góc B = 4° (đáp số 6 giờ 6 phút). Ghi rõ trong explanation.
- Các bài tự luận được tách theo từng ý a), b), c); mỗi ý lặp lại dữ kiện bài toán.
- Với fill dạng bất phương trình, học sinh nhập ký hiệu ASCII: <, >, <=, >= (đã ghi rõ trong q).
"""

DURATION = 90   # phút — "Thời gian: 90 phút (không kể thời gian giao đề)" theo đề gốc

SOURCES = {
    1: "Đề 1 — Mã đề MT101, \"14. 10 đề thi Toán 9 giữa kì 1 – Kết Nối Tri Thức có đáp án.pdf\" (fileId 1DgY-ppG_DyOzi4kup5wW5jmZWTKbRKc_)",
    2: "Đề 2 — Mã đề MT102, \"14. 10 đề thi Toán 9 giữa kì 1 – Kết Nối Tri Thức có đáp án.pdf\" (fileId 1DgY-ppG_DyOzi4kup5wW5jmZWTKbRKc_)",
}

# ═══════════════════════════════════════════════════════════════════════════════
# ĐỀ 1 — MÃ ĐỀ MT101
# ═══════════════════════════════════════════════════════════════════════════════
_DE_1 = [
    # ── A. TRẮC NGHIỆM (2,0 điểm) ─────────────────────────────────────────────
    {"type": "choice", "topic": "Phương trình bậc nhất hai ẩn",
     "section_start": "A. TRẮC NGHIỆM (2,0 điểm)",
     "section_instruction": None,
     "passage_text": None,
     "q": "Câu 1. Phương trình nào sau đây là phương trình bậc nhất hai ẩn?",
     "options": ["A. 2x² + 2 = 0.",
                 "B. 3y − 1 = 5y(y − 2).",
                 "C. 2x + y/2 − 1 = 0.",
                 "D. 3/(2x) + y = 0."],
     "answer": "C. 2x + y/2 − 1 = 0.",
     "explanation": "Phương trình bậc nhất hai ẩn có dạng ax + by = c với a ≠ 0 hoặc b ≠ 0. Phương trình 2x + y/2 − 1 = 0 viết thành 2x + (1/2)y = 1, là phương trình bậc nhất hai ẩn với a = 2 và b = 1/2."},
    {"type": "choice", "topic": "Phương trình bậc nhất hai ẩn",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Câu 2. Phương trình x − 5y + 7 = 0 nhận cặp số nào sau đây làm nghiệm?",
     "options": ["A. (0; 1).", "B. (−1; 2).", "C. (3; 2).", "D. (2; 4)."],
     "answer": "C. (3; 2).",
     "explanation": "Thay x = 3; y = 2 vào phương trình: 3 − 5·2 + 7 = 0. Các cặp còn lại không thỏa mãn."},
    {"type": "choice", "topic": "Hệ phương trình",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Câu 3. Cặp số nào sau đây là nghiệm của hệ phương trình {3x + 4y = 42 ; 10x − 9y = 6}?",
     "options": ["A. (6; −6).", "B. (6; 6).", "C. (−354/13; 402/13).", "D. (354/13; 402/13)."],
     "answer": "B. (6; 6).",
     "explanation": "Nhân phương trình thứ nhất với 10, phương trình thứ hai với 3 rồi trừ vế: 67y = 402 ⇒ y = 6; thay vào 3x + 4y = 42 ⇒ x = 6. Hệ có nghiệm duy nhất (6; 6)."},
    {"type": "choice", "topic": "Phương trình chứa ẩn ở mẫu",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Câu 4. Điều kiện xác định của phương trình 1/(x − 3) − 3 = 2/((x − 3)(x + 4)) là",
     "options": ["A. x ≠ 4; x ≠ −3.", "B. x ≠ 3; x ≠ −4.", "C. x ≠ 3; x ≠ 6.", "D. x ≠ 0; x ≠ −3."],
     "answer": "B. x ≠ 3; x ≠ −4.",
     "explanation": "Điều kiện xác định: x − 3 ≠ 0 và x + 4 ≠ 0, hay x ≠ 3 và x ≠ −4."},
    {"type": "choice", "topic": "Bất đẳng thức",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Câu 5. Bất đẳng thức nào sau đây đúng với mọi số thực a?",
     "options": ["A. 5a > 3a.", "B. 3a > 5a.", "C. 5 + a > 3 + a.", "D. −3a > −6a."],
     "answer": "C. 5 + a > 3 + a.",
     "explanation": "5a > 3a chỉ đúng khi a > 0; 3a > 5a chỉ đúng khi a < 0; −3a > −6a chỉ đúng khi a > 0. Do 5 > 3 nên 5 + a > 3 + a với mọi a."},
    {"type": "choice", "topic": "Tỉ số lượng giác",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Câu 6. Cho tam giác ABC vuông tại A có đường cao AH và ∠B = α. Tỉ số HA/BA bằng:",
     "options": ["A. sin α.", "B. cos α.", "C. tan α.", "D. cot α."],
     "answer": "A. sin α.",
     "explanation": "Xét △ABH vuông tại H, ta có AH/AB = sin B, hay HA/BA = sin α."},
    {"type": "choice", "topic": "Tỉ số lượng giác",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Câu 7. Cho α = 40° và β = 50°. Khẳng định nào sau đây là đúng?",
     "options": ["A. sin α = sin β.", "B. cos α = cos β.", "C. tan α = cot β.", "D. tan α = tan β."],
     "answer": "C. tan α = cot β.",
     "explanation": "α + β = 40° + 50° = 90° nên α và β là hai góc nhọn phụ nhau, do đó sin α = cos β và tan α = cot β."},
    {"type": "choice", "topic": "Tỉ số lượng giác",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Câu 8. Cho tam giác ABC vuông tại A có BC = 10, AC = 6. Tỉ số lượng giác tan C có kết quả gần nhất với giá trị nào dưới đây?",
     "options": ["A. 1,33.", "B. 0,88.", "C. 0,68.", "D. 0,75."],
     "answer": "A. 1,33.",
     "explanation": "Theo định lí Pythagore: AB² = BC² − AC² = 100 − 36 = 64 ⇒ AB = 8. tan C = AB/AC = 8/6 ≈ 1,33."},

    # ── B. TỰ LUẬN (8,0 điểm) ────────────────────────────────────────────────
    {"type": "fill", "topic": "Phương trình tích",
     "section_start": "B. TỰ LUẬN (8,0 điểm)",
     "section_instruction": None,
     "passage_text": None,
     "q": "Bài 1. (2,0 điểm) Giải các phương trình và bất phương trình sau:\na) 9x²(2x − 3) = 0.\nNhập các nghiệm theo thứ tự tăng dần, cách nhau bằng dấu chấm phẩy, dạng x=a;x=b (phân số tối giản).",
     "answer": "x=0;x=3/2",
     "explanation": "9x² = 0 hoặc 2x − 3 = 0 ⇒ x = 0 hoặc x = 3/2. Vậy phương trình có hai nghiệm x = 0; x = 3/2."},
    {"type": "fill", "topic": "Phương trình chứa ẩn ở mẫu",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Bài 1. (2,0 điểm) Giải các phương trình và bất phương trình sau:\nb) (x + 3)/(x − 3) = 3/(x² − 3x) + 1/x.\nNhập nghiệm dạng x=a.",
     "answer": "x=-2",
     "explanation": "ĐKXĐ: x ≠ 0; x ≠ 3. Quy đồng mẫu x(x − 3): x(x + 3) = 3 + (x − 3) ⇔ x² + 3x = x ⇔ x² + 2x = 0 ⇔ x(x + 2) = 0 ⇒ x = 0 (không thỏa mãn) hoặc x = −2 (thỏa mãn). Vậy nghiệm là x = −2."},
    {"type": "fill", "topic": "Bất phương trình bậc nhất một ẩn",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Bài 1. (2,0 điểm) Giải các phương trình và bất phương trình sau:\nc) 3x − 8 > 4x − 12.\nNhập nghiệm dạng x<a hoặc x>a (dùng ký hiệu <, >).",
     "answer": "x<4",
     "explanation": "3x − 4x > −12 + 8 ⇔ −x > −4 ⇔ x < 4. Vậy nghiệm của bất phương trình là x < 4."},
    {"type": "fill", "topic": "Bất phương trình bậc nhất một ẩn",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Bài 1. (2,0 điểm) Giải các phương trình và bất phương trình sau:\nd) (x − 1)/2 − (7x + 3)/15 ≤ (2x + 1)/3 + (3 − 2x)/5.\nNhập nghiệm dạng x<=a hoặc x>=a (dùng ký hiệu <=, >=).",
     "answer": "x>=-7",
     "explanation": "Quy đồng mẫu 30: 15(x − 1) − 2(7x + 3) ≤ 10(2x + 1) + 6(3 − 2x) ⇔ x − 21 ≤ 8x + 28 ⇔ −7x ≤ 49 ⇔ x ≥ −7. Vậy nghiệm của bất phương trình là x ≥ −7."},
    {"type": "fill", "topic": "Hệ phương trình",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Bài 2. (3,0 điểm)\na) Tìm các hệ số x và y trong phản ứng hóa học đã được cân bằng sau: xAg + yCl₂ → 2AgCl. Từ đó, hãy hoàn thiện phương trình phản ứng hóa học sau khi được cân bằng.\nNhập kết quả dạng x=a;y=b.",
     "answer": "x=2;y=1",
     "explanation": "Số nguyên tử Ag và Cl ở hai vế bằng nhau nên x = 2 và 2y = 2 ⇒ x = 2, y = 1. Phương trình sau cân bằng: 2Ag + Cl₂ → 2AgCl."},
    {"type": "fill", "topic": "Hệ phương trình",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Bài 2. (3,0 điểm)\nb) Cho hệ phương trình {2mx + y = m ; x − my = −1 − 6m}. Tìm giá trị của tham số m để cặp số (−2; 1) là nghiệm của hệ phương trình đã cho.\nNhập kết quả dạng m=a (phân số tối giản).",
     "answer": "m=1/5",
     "explanation": "Thay x = −2, y = 1 vào hệ: {−4m + 1 = m ; −2 − m = −1 − 6m} ⇔ {5m = 1 ; 5m = 1} ⇒ m = 1/5."},
    {"type": "fill", "topic": "Giải bài toán bằng cách lập hệ phương trình",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Bài 2. (3,0 điểm)\nc) Giải bài toán sau bằng cách lập hệ phương trình:\nMột số có hai chữ số. Nếu đổi chỗ hai chữ số của nó thì được số mới lớn hơn số đã cho là 63. Tổng của số đã cho và số mới tạo thành bằng 99. Tìm số đã cho.\nNhập số đã cho.",
     "answer": "18",
     "explanation": "Gọi số cần tìm là xy (x, y là chữ số, 0 < x ≤ 9, 0 ≤ y ≤ 9). Số mới là yx. Ta có 10y + x = 10x + y + 63 ⇒ x − y = −7 (1); (10x + y) + (10y + x) = 99 ⇒ x + y = 9 (2). Từ (1), (2): x = 1, y = 8. Vậy số cần tìm là 18."},
    {"type": "fill", "topic": "Tỉ số lượng giác",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Bài 3. (1,0 điểm) Rút gọn các biểu thức sau:\na) A = cos40° − sin50° + tan20°·cot20°.\nNhập giá trị của A.",
     "answer": "1",
     "explanation": "sin50° = cos40°, tan20°·cot20° = 1 nên A = cos40° − cos40° + 1 = 1."},
    {"type": "fill", "topic": "Tỉ số lượng giác",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Bài 3. (1,0 điểm) Rút gọn các biểu thức sau:\nb) B = sin10°/cos80° − cos20°/sin70° + tan15°/cot75°.\nNhập giá trị của B.",
     "answer": "1",
     "explanation": "cos80° = sin10°, sin70° = cos20°, cot75° = tan15° nên B = 1 − 1 + 1 = 1."},
    {"type": "fill", "topic": "Hệ thức lượng trong tam giác vuông",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Bài 4. (1,5 điểm) Từ một đài quan sát, một người đặt mắt tại vị trí B. Người đó nhìn thấy một chiếc ô tô ở vị trí C theo phương BC tạo với phương nằm ngang Bx một góc là ∠CBx = 25° với Bx // AC. Khi đó, khoảng cách giữa ô tô và chân đài quan sát là AC = 1,221 km. Nếu ô tô từ vị trí C tiếp tục đi về phía chân đài quan sát với tốc độ 60 km/h thì sau 1 phút, người đó nhìn thấy ô tô ở vị trí D với góc ∠DBx = α (hình vẽ). [Chú thích thay hình: A là chân đài quan sát, AB thẳng đứng vuông góc với mặt đất AC; C, D, A thẳng hàng, D nằm giữa C và A.]\na) Tính chiều cao của đài quan sát (làm tròn kết quả đến hàng đơn vị của mét), biết độ cao từ tầm mắt của người đó đến đỉnh đài quan sát là 3 m.\nNhập kết quả (mét).",
     "answer": "572",
     "explanation": "Đổi 1,221 km = 1 221 m. Do Bx // AC nên ∠ACB = ∠CBx = 25° (so le trong). △ABC vuông tại A nên AB = AC·tan∠ACB = 1 221·tan25° ≈ 569 (m). Chiều cao đài quan sát khoảng 3 + 569 = 572 (m)."},
    {"type": "essay", "topic": "Hệ thức lượng trong tam giác vuông",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Bài 4. (1,5 điểm) Từ một đài quan sát, một người đặt mắt tại vị trí B. Người đó nhìn thấy một chiếc ô tô ở vị trí C theo phương BC tạo với phương nằm ngang Bx một góc là ∠CBx = 25° với Bx // AC. Khi đó, khoảng cách giữa ô tô và chân đài quan sát là AC = 1,221 km. Nếu ô tô từ vị trí C tiếp tục đi về phía chân đài quan sát với tốc độ 60 km/h thì sau 1 phút, người đó nhìn thấy ô tô ở vị trí D với góc ∠DBx = α (hình vẽ). [Chú thích thay hình: A là chân đài quan sát, AB thẳng đứng vuông góc với mặt đất AC; C, D, A thẳng hàng, D nằm giữa C và A.]\nb) Tính số đo góc α (làm tròn kết quả đến hàng đơn vị của phút).",
     "essay_lines": 8, "essay_word_min": None, "essay_word_max": None,
     "answer": "(Bài làm tự chấm tay)",
     "explanation": "Đổi 60 km/h = 1 000 m/phút. Do Bx // AC và AB ⊥ AC nên ∠ABx = ∠BAC = 90°. CD = 1 000·1 = 1 000 (m) ⇒ AD = AC − CD = 1 221 − 1 000 = 221 (m). △ABD vuông tại A: tan∠ABD = AD/AB ≈ 221/569 ⇒ ∠ABD ≈ 21°14′. Mà ∠DBx + ∠ABD = ∠ABx = 90° ⇒ α = ∠DBx ≈ 90° − 21°14′ = 68°46′."},
    {"type": "fill", "topic": "Hệ thức lượng trong tam giác vuông",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Bài 4. (1,5 điểm) Từ một đài quan sát, một người đặt mắt tại vị trí B. Người đó nhìn thấy một chiếc ô tô ở vị trí C theo phương BC tạo với phương nằm ngang Bx một góc là ∠CBx = 25° với Bx // AC. Khi đó, khoảng cách giữa ô tô và chân đài quan sát là AC = 1,221 km. Nếu ô tô từ vị trí C tiếp tục đi về phía chân đài quan sát với tốc độ 60 km/h thì sau 1 phút, người đó nhìn thấy ô tô ở vị trí D với góc ∠DBx = α (hình vẽ). [Chú thích thay hình: A là chân đài quan sát, AB thẳng đứng vuông góc với mặt đất AC; C, D, A thẳng hàng, D nằm giữa C và A.]\nc) Tính khoảng cách từ mắt người quan sát đến vị trí D (làm tròn kết quả đến hàng đơn vị của mét).\nNhập kết quả (mét).",
     "answer": "610",
     "explanation": "△ABD vuông tại A nên AB = BD·cos∠ABD ⇒ BD = AB/cos∠ABD ≈ 569/cos21°14′ ≈ 610 (m). Vậy khoảng cách từ mắt người quan sát đến vị trí D khoảng 610 mét."},
    {"type": "essay", "topic": "Bất đẳng thức",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Bài 5. (0,5 điểm) Cho các số thực dương x, y, z thỏa mãn 1/x + 1/y + 1/z = 4. Chứng minh bất đẳng thức sau:\n1/(2x + y + z) + 1/(x + 2y + z) + 1/(x + y + 2z) ≤ 1.",
     "essay_lines": 12, "essay_word_min": None, "essay_word_max": None,
     "answer": "(Bài làm tự chấm tay)",
     "explanation": "Trước hết, với a > 0, b > 0 luôn có 1/a + 1/b ≥ 4/(a + b) (*) vì 1/a + 1/b − 4/(a + b) = (a − b)²/(ab(a + b)) ≥ 0. Áp dụng (*) cho 2x và y + z: 1/(2x + y + z) ≤ (1/4)(1/(2x) + 1/(y + z)); lại áp dụng (*) cho y và z: 1/(y + z) ≤ (1/4)(1/y + 1/z). Do đó 1/(2x + y + z) ≤ (1/4)(1/(2x) + 1/(4y) + 1/(4z)). Tương tự cho hai số hạng còn lại rồi cộng vế: tổng ≤ (1/4)(1/x + 1/y + 1/z) = (1/4)·4 = 1. Đẳng thức xảy ra khi x = y = z = 3/4."},
]

# ═══════════════════════════════════════════════════════════════════════════════
# ĐỀ 2 — MÃ ĐỀ MT102
# ═══════════════════════════════════════════════════════════════════════════════
_DE_2 = [
    # ── A. TRẮC NGHIỆM (2,0 điểm) ─────────────────────────────────────────────
    {"type": "choice", "topic": "Phương trình bậc nhất hai ẩn",
     "section_start": "A. TRẮC NGHIỆM (2,0 điểm)",
     "section_instruction": None,
     "passage_text": None,
     "q": "Câu 1. Phương trình nào sau đây không là phương trình bậc nhất hai ẩn?",
     "options": ["A. x − 2y = 3.", "B. 0x + 0y = −1.", "C. −2x + 0y = 3.", "D. 0x − 3y = 2."],
     "answer": "B. 0x + 0y = −1.",
     "explanation": "Phương trình bậc nhất hai ẩn có dạng ax + by = c với a ≠ 0 hoặc b ≠ 0. Phương trình 0x + 0y = −1 có a = b = 0 nên không là phương trình bậc nhất hai ẩn."},
    {"type": "choice", "topic": "Phương trình bậc nhất hai ẩn",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Câu 2. Phương trình nào dưới đây nhận cặp số (−2; 4) làm nghiệm?",
     "options": ["A. x − 2y = 0.", "B. 2x + y = 0.", "C. x − y = 2.", "D. x + 2y + 1 = 0."],
     "answer": "B. 2x + y = 0.",
     "explanation": "Thay x = −2; y = 4 vào 2x + y = 0: 2·(−2) + 4 = 0. Các phương trình còn lại không thỏa mãn."},
    {"type": "choice", "topic": "Hệ phương trình",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Câu 3. Cho hệ phương trình {x − y = 8 ; 2x + 3y = −9}. Cho các khẳng định sau:\n(i) Từ phương trình thứ nhất của hệ, biểu diễn y theo x, ta được: y = x − 8.\n(ii) Từ phương trình thứ nhất của hệ, biểu diễn x theo y, ta được: x = 8 − y.\n(iii) Nghiệm của hệ là cặp số (3; −5).\nSố khẳng định đúng trong các khẳng định trên là",
     "options": ["A. 0.", "B. 1.", "C. 2.", "D. 3."],
     "answer": "C. 2.",
     "explanation": "Từ x − y = 8 suy ra x = 8 + y (nên (ii) sai) và y = x − 8 ((i) đúng). Thế y = x − 8 vào 2x + 3y = −9: 5x = 15 ⇒ x = 3, y = −5 ((iii) đúng). Có 2 khẳng định đúng."},
    {"type": "choice", "topic": "Phương trình chứa ẩn ở mẫu",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Câu 4. Điều kiện xác định của phương trình 1/(x(x² + 4)) = (x + 1)/x − 1/(x − 2) là",
     "options": ["A. x ≠ 0, x ≠ −2 và x ≠ 2.", "B. x ≠ 0 và x ≠ −2.", "C. x ≠ 0 và x ≠ −4.", "D. x ≠ 0 và x ≠ 2."],
     "answer": "D. x ≠ 0 và x ≠ 2.",
     "explanation": "x² + 4 > 0 với mọi x nên điều kiện xác định là x ≠ 0 và x − 2 ≠ 0, hay x ≠ 0 và x ≠ 2."},
    {"type": "choice", "topic": "Bất đẳng thức",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Câu 5. Nếu a, b, c là ba số mà a < b và ac > bc thì c là",
     "options": ["A. số âm.", "B. số dương.", "C. số 0.", "D. số tùy ý."],
     "answer": "A. số âm.",
     "explanation": "a < b mà ac > bc nên nhân hai vế với c đã đổi chiều bất đẳng thức, suy ra c < 0."},
    {"type": "choice", "topic": "Tỉ số lượng giác",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Câu 6. Cho tam giác ABC vuông tại A. Khi đó, sin ∠ABC bằng:",
     "options": ["A. AC/BC.", "B. BC/AC.", "C. AB/BC.", "D. AB/AC."],
     "answer": "A. AC/BC.",
     "explanation": "Tam giác ABC vuông tại A: sin ∠ABC = cạnh đối / cạnh huyền = AC/BC."},
    {"type": "choice", "topic": "Tỉ số lượng giác",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Câu 7. Cho tam giác ABC vuông tại A có đường cao AH và ∠B = α. Tỉ số HA/HC bằng:",
     "options": ["A. sin α.", "B. cos α.", "C. tan α.", "D. cot α."],
     "answer": "D. cot α.",
     "explanation": "Xét △ACH vuông tại H: HA/HC = tan C. Mà ∠B + ∠C = 90° nên tan C = cot B = cot α."},
    {"type": "choice", "topic": "Hệ thức lượng trong tam giác vuông",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Câu 8. Cho tam giác ABC vuông tại A có AC = 10, ∠C = 30°. Số đo góc B và độ dài cạnh BC (làm tròn kết quả đến hàng phần trăm) bằng",
     "options": ["A. ∠B = 60°; BC = 20.", "B. ∠B = 60°; BC ≈ 8,08.", "C. ∠B = 60°; BC ≈ 11,55.", "D. ∠B = 60°; BC ≈ 14,14."],
     "answer": "C. ∠B = 60°; BC ≈ 11,55.",
     "explanation": "∠B = 90° − 30° = 60°. cos C = AC/BC ⇒ BC = AC/cos30° = 10/cos30° ≈ 11,55."},

    # ── B. TỰ LUẬN (8,0 điểm) ────────────────────────────────────────────────
    {"type": "fill", "topic": "Phương trình tích",
     "section_start": "B. TỰ LUẬN (8,0 điểm)",
     "section_instruction": None,
     "passage_text": None,
     "q": "Bài 1. (2,0 điểm) Giải các phương trình và bất phương trình sau:\na) ((2/3)x + 6)(8 − 2x) = 0.\nNhập các nghiệm theo thứ tự tăng dần, cách nhau bằng dấu chấm phẩy, dạng x=a;x=b.",
     "answer": "x=-9;x=4",
     "explanation": "(2/3)x + 6 = 0 hoặc 8 − 2x = 0 ⇒ x = −9 hoặc x = 4. Vậy phương trình có hai nghiệm x = −9; x = 4."},
    {"type": "fill", "topic": "Phương trình chứa ẩn ở mẫu",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Bài 1. (2,0 điểm) Giải các phương trình và bất phương trình sau:\nb) (2x + 1)/(x + 1) + 2/x = 2/(x(x + 1)).\nNhập nghiệm dạng x=a (phân số tối giản).",
     "answer": "x=-3/2",
     "explanation": "ĐKXĐ: x ≠ −1, x ≠ 0. Quy đồng mẫu x(x + 1): (2x + 1)x + 2(x + 1) = 2 ⇔ 2x² + 3x = 0 ⇔ x(2x + 3) = 0 ⇒ x = 0 (không thỏa mãn) hoặc x = −3/2 (thỏa mãn). Vậy nghiệm là x = −3/2."},
    {"type": "fill", "topic": "Bất phương trình bậc nhất một ẩn",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Bài 1. (2,0 điểm) Giải các phương trình và bất phương trình sau:\nc) 3(x − 2) − 5 ≥ 3(2x − 1).\nNhập nghiệm dạng x<=a hoặc x>=a (dùng ký hiệu <=, >=; phân số tối giản).",
     "answer": "x<=-8/3",
     "explanation": "3x − 6 − 5 ≥ 6x − 3 ⇔ 3x − 6x ≥ −3 + 11 ⇔ −3x ≥ 8 ⇔ x ≤ −8/3. Vậy nghiệm của bất phương trình là x ≤ −8/3."},
    {"type": "fill", "topic": "Bất phương trình bậc nhất một ẩn",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Bài 1. (2,0 điểm) Giải các phương trình và bất phương trình sau:\nd) (2x − 1)/3 − (x + 2)/2 < (5x + 4)/6.\nNhập nghiệm dạng x<a hoặc x>a (dùng ký hiệu <, >).",
     "answer": "x>-3",
     "explanation": "Quy đồng mẫu 6: 2(2x − 1) − 3(x + 2) < 5x + 4 ⇔ x − 8 < 5x + 4 ⇔ −4x < 12 ⇔ x > −3. Vậy nghiệm của bất phương trình là x > −3."},
    {"type": "fill", "topic": "Hệ phương trình",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Bài 2. (3,0 điểm)\na) Tìm các hệ số x và y trong phản ứng hóa học đã được cân bằng sau: xKClO₃ → 2KCl + yO₂. Từ đó, hãy hoàn thiện phương trình phản ứng hóa học sau khi được cân bằng.\nNhập kết quả dạng x=a;y=b.",
     "answer": "x=2;y=3",
     "explanation": "Số nguyên tử K, Cl, O ở hai vế bằng nhau: x = 2 và 3x = 2y ⇒ x = 2, y = 3. Phương trình sau cân bằng: 2KClO₃ → 2KCl + 3O₂."},
    {"type": "fill", "topic": "Hệ phương trình",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Bài 2. (3,0 điểm)\nb) Xác định hàm số y = ax + b để đồ thị hàm số đó đi qua hai điểm A(1; −1) và B(4; 5).\nNhập hàm số dạng y=ax+b (ví dụ y=2x+1 hoặc y=-x-3).",
     "answer": "y=2x-3",
     "explanation": "Đồ thị đi qua A(1; −1) và B(4; 5) nên {a + b = −1 ; 4a + b = 5}. Trừ vế: 3a = 6 ⇒ a = 2, b = −3. Vậy y = 2x − 3."},
    {"type": "fill", "topic": "Giải bài toán bằng cách lập hệ phương trình",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Bài 2. (3,0 điểm)\nc) Giải bài toán sau bằng cách lập hệ phương trình:\nMột chiếc thuyền xuôi dòng và ngược dòng trên khúc sông dài 40 km hết 4 giờ 30 phút. Biết thời gian thuyền xuôi dòng 5 km bằng thời gian thuyền ngược dòng 4 km. Tính vận tốc dòng nước.\nNhập vận tốc dòng nước (km/h).",
     "answer": "2",
     "explanation": "Gọi x, y (km/h) là vận tốc thuyền khi nước yên lặng và vận tốc dòng nước (x > y > 0). Ta có 40/(x + y) + 40/(x − y) = 4,5 và 5/(x + y) = 4/(x − y). Đặt a = 1/(x + y), b = 1/(x − y): 40a + 40b = 4,5 và 5a = 4b ⇒ a = 1/20, b = 1/16 ⇒ x + y = 20, x − y = 16 ⇒ x = 18, y = 2. Vậy vận tốc dòng nước là 2 km/h."},
    {"type": "fill", "topic": "Tỉ số lượng giác",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Bài 3. (1,0 điểm) Rút gọn các biểu thức sau:\na) A = sin35° + sin67° − cos23° − cos55°.\nNhập giá trị của A.",
     "answer": "0",
     "explanation": "cos23° = sin67°, cos55° = sin35° nên A = sin35° + sin67° − sin67° − sin35° = 0."},
    {"type": "fill", "topic": "Tỉ số lượng giác",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Bài 3. (1,0 điểm) Rút gọn các biểu thức sau:\nb) B = cot20°·cot40°·cot50°·cot70°.\nNhập giá trị của B.",
     "answer": "1",
     "explanation": "cot50° = tan40°, cot70° = tan20° nên B = (cot20°·tan20°)·(cot40°·tan40°) = 1·1 = 1."},
    {"type": "fill", "topic": "Hệ thức lượng trong tam giác vuông",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Bài 4. (1,5 điểm) Lúc 6 giờ sáng, bạn An đi từ nhà (điểm A) đến trường (điểm B) phải leo lên và xuống một con dốc đỉnh C được mô tả như hình vẽ dưới. Cho biết đoạn AB dài 762 m, ∠A = 4°, ∠B = 6°. [Chú thích thay hình: tam giác ABC với đỉnh C ở trên, AB nằm ngang; chiều cao con dốc là đường cao CH hạ từ C xuống AB.]\na) Tính chiều cao con dốc (làm tròn kết quả đến hàng đơn vị của mét).\nNhập kết quả (mét).",
     "answer": "32",
     "explanation": "Kẻ CH ⊥ AB. Trong △ACH và △BCH vuông tại H: AH = CH/tan A, BH = CH/tan B ⇒ AB = CH·(1/tan4° + 1/tan6°) ⇒ CH = 762/(1/tan4° + 1/tan6°) ≈ 32 (m). Vậy chiều cao của con dốc là 32 m."},
    {"type": "essay", "topic": "Hệ thức lượng trong tam giác vuông",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Bài 4. (1,5 điểm) Lúc 6 giờ sáng, bạn An đi từ nhà (điểm A) đến trường (điểm B) phải leo lên và xuống một con dốc đỉnh C được mô tả như hình vẽ dưới. Cho biết đoạn AB dài 762 m, ∠A = 4°, ∠B = 6°. [Chú thích thay hình: tam giác ABC với đỉnh C ở trên, AB nằm ngang; chiều cao con dốc là đường cao CH hạ từ C xuống AB.]\nb) Hỏi bạn An đến trường lúc mấy giờ (làm tròn kết quả đến phút)? Biết rằng tốc độ lên dốc là 4 km/h và tốc độ xuống dốc là 19 km/h.",
     "essay_lines": 8, "essay_word_min": None, "essay_word_max": None,
     "answer": "(Bài làm tự chấm tay)",
     "explanation": "Hướng dẫn giải gốc: AC = CH/sin∠CAH ≈ 32/sin6° (m), CB = CH/sin∠CBH ≈ 32/sin4° (m); thời gian đi t = AC/4 + CB/19 ≈ 0,1007 giờ ≈ 6 phút ⇒ An đến trường lúc 6 giờ 6 phút. LƯU Ý: hướng dẫn giải gốc dùng góc A = 6°, góc B = 4° (ngược với đề ghi ∠A = 4°, ∠B = 6°). Nếu tính đúng theo dữ kiện đề (AC = 32/sin4° ≈ 459 m, CB = 32/sin6° ≈ 306 m) thì t ≈ 0,1147 + 0,0161 ≈ 0,131 giờ ≈ 8 phút ⇒ 6 giờ 8 phút. Chấm theo lập luận; chấp nhận cả hai đáp số nếu cách giải đúng."},
    {"type": "essay", "topic": "Bất phương trình bậc nhất một ẩn",
     "section_start": None, "section_instruction": None, "passage_text": None,
     "q": "Bài 5. (0,5 điểm) Giải bất phương trình ẩn x sau: (x − ab)/(a + b) + (x − bc)/(b + c) + (x − ac)/(a + c) > a + b + c với a, b, c > 0.",
     "essay_lines": 10, "essay_word_min": None, "essay_word_max": None,
     "answer": "(Bài làm tự chấm tay)",
     "explanation": "Chuyển vế: ((x − ab)/(a + b) − c) + ((x − bc)/(b + c) − a) + ((x − ac)/(a + c) − b) > 0 ⇔ (x − ab − ac − bc)/(a + b) + (x − bc − ab − ac)/(b + c) + (x − ac − ab − bc)/(a + c) > 0 ⇔ (x − ab − bc − ac)·(1/(a + b) + 1/(b + c) + 1/(a + c)) > 0. Vì 1/(a + b) + 1/(b + c) + 1/(a + c) > 0 (do a, b, c > 0) nên x − ab − bc − ac > 0. Vậy nghiệm của bất phương trình là x > ab + bc + ac."},
]

EXAMS = {1: _DE_1, 2: _DE_2}
